UPDATE `command` SET `permission`='744' WHERE `name`='ticket assign';
UPDATE `command` SET `permission`='744' WHERE `name`='ticket comment';
UPDATE `command` SET `permission`='744' WHERE `name`='ticket unassign';
UPDATE `command` SET `permission`='542' WHERE `name`='ban';
UPDATE `command` SET `permission`='542' WHERE `name`='ban account';
UPDATE `command` SET `permission`='542' WHERE `name`='ban character';
UPDATE `command` SET `permission`='195' WHERE `name`='ban ip';
UPDATE `command` SET `permission`='195' WHERE `name`='ban playeraccount';
UPDATE `command` SET `permission`='542' WHERE `name`='baninfo';
UPDATE `command` SET `permission`='542' WHERE `name`='baninfo account';
UPDATE `command` SET `permission`='542' WHERE `name`='baninfo character';
UPDATE `command` SET `permission`='542' WHERE `name`='baninfo ip';
UPDATE `command` SET `permission`='542' WHERE `name`='banlist';
UPDATE `command` SET `permission`='542' WHERE `name`='banlist account';
UPDATE `command` SET `permission`='542' WHERE `name`='banlist character';
UPDATE `command` SET `permission`='542' WHERE `name`='banlist ip';
UPDATE `command` SET `permission`='542' WHERE `name`='unban';
UPDATE `command` SET `permission`='542' WHERE `name`='unban account';
UPDATE `command` SET `permission`='542' WHERE `name`='unban character';
UPDATE `command` SET `permission`='542' WHERE `name`='unban ip';
UPDATE `command` SET `permission`='194' WHERE `name`='lookup area';
UPDATE `command` SET `permission`='194' WHERE `name`='lookup creature';
UPDATE `command` SET `permission`='194' WHERE `name`='lookup event';
UPDATE `command` SET `permission`='194' WHERE `name`='lookup faction';
UPDATE `command` SET `permission`='194' WHERE `name`='lookup item';
UPDATE `command` SET `permission`='194' WHERE `name`='lookup itemset';
UPDATE `command` SET `permission`='194' WHERE `name`='lookup map';
UPDATE `command` SET `permission`='194' WHERE `name`='lookup object';
UPDATE `command` SET `permission`='194' WHERE `name`='lookup player account';
UPDATE `command` SET `permission`='195' WHERE `name`='lookup player email';
UPDATE `command` SET `permission`='195' WHERE `name`='lookup player ip';
UPDATE `command` SET `permission`='194' WHERE `name`='lookup quest';
UPDATE `command` SET `permission`='194' WHERE `name`='lookup skill';
UPDATE `command` SET `permission`='194' WHERE `name`='lookup spell';
UPDATE `command` SET `permission`='194' WHERE `name`='lookup taxinode';
UPDATE `command` SET `permission`='194' WHERE `name`='lookup tele';
UPDATE `command` SET `permission`='194' WHERE `name`='lookup';
UPDATE `command` SET `permission`='542' WHERE `name`='additem';
UPDATE `command` SET `permission`='542' WHERE `name`='additemset';
UPDATE `command` SET `permission`='542' WHERE `name`='honor add';
UPDATE `command` SET `permission`='542' WHERE `name`='honor add kill';
UPDATE `command` SET `permission`='542' WHERE `name`='honor update';
UPDATE `command` SET `permission`='542' WHERE `name`='honor';
UPDATE `command` SET `permission`='195' WHERE `name`='modify talentpoints';
UPDATE `command` SET `permission`='195' WHERE `name`='npc delete';
UPDATE `command` SET `permission`='195' WHERE `name`='npc add item';
UPDATE `command` SET `permission`='195' WHERE `name`='npc add';
UPDATE `command` SET `permission`='542' WHERE `name`='quest add';
UPDATE `command` SET `permission`='542' WHERE `name`='quest complete';
UPDATE `command` SET `permission`='542' WHERE `name`='quest remove';
UPDATE `command` SET `permission`='542' WHERE `name`='quest';
UPDATE `command` SET `permission`='194' WHERE `name`='gm fly';
UPDATE `command` SET `permission`='194' WHERE `name`='gm chat';
UPDATE `command` SET `permission`='194' WHERE `name`='gm visible';
UPDATE `command` SET `permission`='194' WHERE `name`='gm';
UPDATE `command` SET `permission`='542' WHERE `name`='levelup';
UPDATE `command` SET `permission`='542' WHERE `name`='learn all my talents';
UPDATE `command` SET `permission`='542' WHERE `name`='learn all my spells';
UPDATE `command` SET `permission`='542' WHERE `name`='learn all my pettalents';
UPDATE `command` SET `permission`='542' WHERE `name`='learn all my class';
UPDATE `command` SET `permission`='542' WHERE `name`='learn all gm';
UPDATE `command` SET `permission`='542' WHERE `name`='learn all lang';
UPDATE `command` SET `permission`='542' WHERE `name`='learn all default';
UPDATE `command` SET `permission`='542' WHERE `name`='learn';
UPDATE `command` SET `permission`='195' WHERE `name`='announce';


