DELETE FROM `quest_template` WHERE  `id` = 800554;
DELETE FROM `quest_template_addon` WHERE `id` = 800554;
DELETE FROM `creature_questender` WHERE `id` = 800053   AND `quest` = 800554;
DELETE FROM `creature_queststarter` WHERE `id` = 800053   AND `quest` = 800554;



REPLACE INTO `quest_template` (`ID`, `Method`, `QuestLevel`, `MinLevel`, `QuestSortID`, `QuestType`, `SuggestedGroupNum`, `LimitTime`, `RequiredRaces`, `RequiredFactionId1`, `RequiredFactionId2`, `RequiredFactionValue1`, `RequiredFactionValue2`, `NextQuestIdChain`, `RewardXPId`, `RewardOrRequiredMoney`, `RewardMoneyMaxLevel`, `RewardSpell`, `RewardSpellCast`, `RewardHonor`, `RewardHonorMultiplier`, `SourceItemId`, `Flags`, `RewardTitle`, `RequiredPlayerKills`, `RewardTalents`, `RewardArenaPoints`, `RewardItem1`, `RewardItem2`, `RewardItem3`, `RewardItem4`, `RewardAmount1`, `RewardAmount2`, `RewardAmount3`, `RewardAmount4`, `RewardChoiceItemID1`, `RewardChoiceItemID2`, `RewardChoiceItemID3`, `RewardChoiceItemID4`, `RewardChoiceItemID5`, `RewardChoiceItemID6`, `RewardChoiceItemQuantity1`, `RewardChoiceItemQuantity2`, `RewardChoiceItemQuantity3`, `RewardChoiceItemQuantity4`, `RewardChoiceItemQuantity5`, `RewardChoiceItemQuantity6`, `RewardFactionID1`, `RewardFactionID2`, `RewardFactionID3`, `RewardFactionID4`, `RewardFactionID5`, `RewardFactionValue1`, `RewardFactionValue2`, `RewardFactionValue3`, `RewardFactionValue4`, `RewardFactionValue5`, `RewardFactionOverride1`, `RewardFactionOverride2`, `RewardFactionOverride3`, `RewardFactionOverride4`, `RewardFactionOverride5`, `PointMapId`, `PointX`, `PointY`, `PointOption`, `LogTitle`, `LogDescription`, `QuestDescription`, `EndText`, `OfferRewardText`, `RequestItemsText`, `QuestCompletionLog`, `RequiredNpcOrGo1`, `RequiredNpcOrGo2`, `RequiredNpcOrGo3`, `RequiredNpcOrGo4`, `RequiredNpcOrGoCount1`, `RequiredNpcOrGoCount2`, `RequiredNpcOrGoCount3`, `RequiredNpcOrGoCount4`, `RequiredSourceItemId1`, `RequiredSourceItemId2`, `RequiredSourceItemId3`, `RequiredSourceItemId4`, `RequiredSourceItemCount1`, `RequiredSourceItemCount2`, `RequiredSourceItemCount3`, `RequiredSourceItemCount4`, `RequiredItemId1`, `RequiredItemId2`, `RequiredItemId3`, `RequiredItemId4`, `RequiredItemId5`, `RequiredItemId6`, `RequiredItemCount1`, `RequiredItemCount2`, `RequiredItemCount3`, `RequiredItemCount4`, `RequiredItemCount5`, `RequiredItemCount6`, `Unknown0`, `ObjectiveText1`, `ObjectiveText2`, `ObjectiveText3`, `ObjectiveText4`, `DetailsEmote1`, `DetailsEmote2`, `DetailsEmote3`, `DetailsEmote4`, `DetailsEmoteDelay1`, `DetailsEmoteDelay2`, `DetailsEmoteDelay3`, `DetailsEmoteDelay4`, `EmoteOnIncomplete`, `EmoteOnComplete`, `OfferRewardEmote1`, `OfferRewardEmote2`, `OfferRewardEmote3`, `OfferRewardEmote4`, `OfferRewardEmoteDelay1`, `OfferRewardEmoteDelay2`, `OfferRewardEmoteDelay3`, `OfferRewardEmoteDelay4`, `VerifiedBuild`) VALUES
(/*  ID    */800554,
 /*  Method  */ 2,
 /*  QuestLevel  */ 80,
 /*  MinLevel   */80,
 /*  QuestSortID  */ -1,
 /*  QuestType*/ 0,
 /*  SuggestedGroupNum  */ 0,
 /*  LimitTime  */ 0,
 /*  RequiredRaces   */1791,
 /*  RequiredFactionId1   */ 0,
 /*  RequiredFactionId2  */ 0,
 /*  RequiredFactionValue1  */ 0,
 /*  RequiredFactionValue2   */ 0,
 /*  NextQuestIdChain  */ 0,
 /*  RewardXPId   */70,
 /*  RewardOrRequiredMoney  */ 20000,
 /*  RewardMoneyMaxLevel  */ 20000,
 /*  RewardSpell   */ 0,
 /*  RewardSpellCast  */ 0,
 /*  RewardHonor  */ 0,
 /*  RewardHonorMultiplier  */ 0,
 /*  SourceItemId  */ 0,
 /*  Flags  */ 4096,
 /*  RewardTitle  */ 0,
 /*  RequiredPlayerKills  */ 0,
 /*  RewardTalents  */ 0,
 /*  RewardArenaPoints  */ 0,
 /*  RewardIten    */ 700518,
 /*  RewardItem2   */ 0,
 /*  RewardItem3   */ 0,
 /*  RewardItem4   */ 0,
 /*  RewardAmount1 */ 1,
 /*  RewardAmount2 */ 0,
 /*  RewardAmount3 */ 0,
 /*  RewardAmount4 */ 0,
 /*  RewardChoiceItemID1  */ 0,
 /*  RewardChoiceItemID2  */ 0,
 /*  RewardChoiceItemID3  */ 0,
 /*  RewardChoiceItemID4  */ 0,
 /*  RewardChoiceItemID5  */ 0,
 /*  RewardChoiceItemID6  */ 0,
 /*  RewardChoiceItemQuantity1  */ 0,
 /*  RewardChoiceItemQuantity2  */ 0,
 /*  RewardChoiceItemQuantity3  */ 0,
 /*  RewardChoiceItemQuantity4  */ 0,
 /*  RewardChoiceItemQuantity5  */ 0,
 /*  RewardChoiceItemQuantity6  */ 0,
 /*  RewardFactionID1  */ 0,
 /*  RewardFactionID2  */ 0,
 /*  RewardFactionID3  */ 0,
 /*  RewardFactionID4  */ 0,
 /*  RewardFactionID5  */ 0,
 /*  RewardFactionValue1  */ 0,
 /*  RewardFactionValue2  */ 0,
 /*  RewardFactionValue3  */ 0,
 /*  RewardFactionValue4  */ 0,
 /*  RewardFactionValue5 */ 0,
 /*  RewardFactionOverride1  */ 0,
 /*  RewardFactionOverride2  */ 0,
 /*  RewardFactionOverride3  */ 0,
 /*  RewardFactionOverride4  */ 0,
 /*  RewardFactionOverride5  */ 0,
 /*  PointMapId  */ 0,
 /*  PointX  */ 0,
 /*  PointY  */ 0,
 /*  PointOption  */ 0,
 /*  LogTitle  */ 'Erweißt Euch würdig',
 /*  LogDescription  */  'Sammelt 30 Waffen der Unterstützer',
 /*  QuestDescription   */ 'Hallo $C $N, schön das ihr euren Weg hierher gefunden habt. Ich hab eine wichtige Aufgabe für Euch, die für das Königshaus ernorm wichtig ist. Sammelt 30 Waffen der Unterstützer. Sie sind über ganz Azeroth und die Scherbenwelt verteilt. Um genauere Angaben zu finden geht auf die Homepage und sucht im Arsenal nach den Waffen.',
 /*  EndText   */  '',
 /*  OfferRewardText  */  'Seid ihr fertig?',
 /*  RequestItemsText  */ 'Sammelt 30 Waffen der Unterstützer.',
 /*  QuestCompletionLog  */ 'Es ist Eure Sache was ihr tut.',
 /*  RequiredNpcOrGo1  */ 0,
 /*  RequiredNpcOrGo2  */ 0,
 /*  RequiredNpcOrGo3  */ 0,
 /*  RequiredNpcOrGo4  */ 0,
 /*  RequiredNpcOrGoCount1  */ 0,
 /*  RequiredNpcOrGoCount2  */ 0,
 /*  RequiredNpcOrGoCount3  */ 0,
 /*  RequiredNpcOrGoCount4  */ 0,
 /*  RequiredSourceItemId1  */ 0,
 /*  RequiredSourceItemId2  */ 0,
 /*  RequiredSourceItemId3  */ 0,
 /*  RequiredSourceItemId4  */ 0,
 /*  RequiredSourceItemCount1  */ 0,
 /*  RequiredSourceItemCount2  */ 0,
 /*  RequiredSourceItemCount3  */ 0,
 /*  RequiredSourceItemCount4  */ 0,
 /*  RequiredItemId1  */ 700519,
 /*  RequiredItemId2  */ 0,
 /*  RequiredItemId3  */ 0,
 /*  RequiredItemId4  */ 0,
 /*  RequiredItemId5  */ 0,
 /*  RequiredItemId6  */ 0,
 /*  RequiredItemCount1  */ 30,
 /*  RequiredItemCount2  */ 0,
 /*  RequiredItemCount3  */ 0,
 /*  RequiredItemCount4  */ 0,
 /*  RequiredItemCount5  */ 0,
 /*  RequiredItemCount6  */ 0,
 /*  Unknown0  */ 0,
 /*  ObjectiveText1  */'',
 /*  ObjectiveText2  */'',
 /*  ObjectiveText3  */'',
 /*  ObjectiveText4  */ '',
 /*  DetailsEmote1  */ 0,
 /*  DetailsEmote2  */ 0,
 /*  DetailsEmote3  */ 0,
 /*  DetailsEmote4   */ 0,
 /*  DetailsEmoteDelay1  */ 0,
 /*  DetailsEmoteDelay2  */ 0,
 /*  DetailsEmoteDelay3  */ 0,
 /*  DetailsEmoteDelay4  */ 0,
 /*  EmoteOnIncomplete  */ 0,
 /*  EmoteOnComplete  */ 0,
 /*  OfferRewardEmote1  */ 0,
 /*  OfferRewardEmote2  */ 0,
 /*  OfferRewardEmote3  */ 0,
 /*  OfferRewardEmote4  */ 0,
 /*  OfferRewardEmoteDelay1  */ 0,
 /*  OfferRewardEmoteDelay2  */ 0,
 /*  OfferRewardEmoteDelay3  */ 0,
 /*  OfferRewardEmoteDelay4  */ 0,
 1);



REPLACE INTO `quest_template_addon` (`ID`, `MaxLevel`, `AllowableClasses`, `SourceSpellID`, `PrevQuestID`, `NextQuestID`, `ExclusiveGroup`, `RewardMailTemplateID`, `RewardMailDelay`, `RequiredSkillID`, `RequiredSkillPoints`, `RequiredMinRepFaction`, `RequiredMaxRepFaction`, `RequiredMinRepValue`, `RequiredMaxRepValue`, `ProvidedItemCount`, `SpecialFlags`) VALUES
( /*  ID  */800554,
  /*  MaxLevel  */80,
  /*  AllowableClasses  */2047,
  /*  SourceSpellID  */ 0,
  /*   PrevQuestID */ 870002,
  /*  NextQuestID  */0,
  /*  ExclusiveGroup  */ 0,
  /*   RewardMailTemplateID */ 0,
  /*  RewardMailDelay  */ 0,
  /*  RequiredSkillID  */ 0,
  /*  RequiredSkillPoints  */ 0,
  /*  RequiredMinRepFaction  */ 0,
  /*  RequiredMaxRepFaction  */ 0,
  /*   RequiredMinRepValue */ 0,
  /*  RequiredMaxRepValue  */ 0,
  /*  ProvidedItemCount  */ 0,
  /*   SpecialFlags */ 0);


REPLACE INTO `creature_questender` (`id`, `quest`) VALUES
(800053, 800554);

REPLACE INTO `creature_queststarter` (`id`, `quest`) VALUES
(800053, 800554);
DELETE FROM `quest_template` WHERE  `id` = 802036;
DELETE FROM `quest_template_addon` WHERE `id` = 802036;
DELETE FROM `creature_questender` WHERE `id` = 16991   AND `quest` = 802036;
DELETE FROM `creature_queststarter` WHERE `id` = 16991   AND `quest` = 802036;



REPLACE INTO `quest_template` (`ID`, `Method`, `QuestLevel`, `MinLevel`, `QuestSortID`, `QuestType`, `SuggestedGroupNum`, `LimitTime`, `RequiredRaces`, `RequiredFactionId1`, `RequiredFactionId2`, `RequiredFactionValue1`, `RequiredFactionValue2`, `NextQuestIdChain`, `RewardXPId`, `RewardOrRequiredMoney`, `RewardMoneyMaxLevel`, `RewardSpell`, `RewardSpellCast`, `RewardHonor`, `RewardHonorMultiplier`, `SourceItemId`, `Flags`, `RewardTitle`, `RequiredPlayerKills`, `RewardTalents`, `RewardArenaPoints`, `RewardItem1`, `RewardItem2`, `RewardItem3`, `RewardItem4`, `RewardAmount1`, `RewardAmount2`, `RewardAmount3`, `RewardAmount4`, `RewardChoiceItemID1`, `RewardChoiceItemID2`, `RewardChoiceItemID3`, `RewardChoiceItemID4`, `RewardChoiceItemID5`, `RewardChoiceItemID6`, `RewardChoiceItemQuantity1`, `RewardChoiceItemQuantity2`, `RewardChoiceItemQuantity3`, `RewardChoiceItemQuantity4`, `RewardChoiceItemQuantity5`, `RewardChoiceItemQuantity6`, `RewardFactionID1`, `RewardFactionID2`, `RewardFactionID3`, `RewardFactionID4`, `RewardFactionID5`, `RewardFactionValue1`, `RewardFactionValue2`, `RewardFactionValue3`, `RewardFactionValue4`, `RewardFactionValue5`, `RewardFactionOverride1`, `RewardFactionOverride2`, `RewardFactionOverride3`, `RewardFactionOverride4`, `RewardFactionOverride5`, `PointMapId`, `PointX`, `PointY`, `PointOption`, `LogTitle`, `LogDescription`, `QuestDescription`, `EndText`, `OfferRewardText`, `RequestItemsText`, `QuestCompletionLog`, `RequiredNpcOrGo1`, `RequiredNpcOrGo2`, `RequiredNpcOrGo3`, `RequiredNpcOrGo4`, `RequiredNpcOrGoCount1`, `RequiredNpcOrGoCount2`, `RequiredNpcOrGoCount3`, `RequiredNpcOrGoCount4`, `RequiredSourceItemId1`, `RequiredSourceItemId2`, `RequiredSourceItemId3`, `RequiredSourceItemId4`, `RequiredSourceItemCount1`, `RequiredSourceItemCount2`, `RequiredSourceItemCount3`, `RequiredSourceItemCount4`, `RequiredItemId1`, `RequiredItemId2`, `RequiredItemId3`, `RequiredItemId4`, `RequiredItemId5`, `RequiredItemId6`, `RequiredItemCount1`, `RequiredItemCount2`, `RequiredItemCount3`, `RequiredItemCount4`, `RequiredItemCount5`, `RequiredItemCount6`, `Unknown0`, `ObjectiveText1`, `ObjectiveText2`, `ObjectiveText3`, `ObjectiveText4`, `DetailsEmote1`, `DetailsEmote2`, `DetailsEmote3`, `DetailsEmote4`, `DetailsEmoteDelay1`, `DetailsEmoteDelay2`, `DetailsEmoteDelay3`, `DetailsEmoteDelay4`, `EmoteOnIncomplete`, `EmoteOnComplete`, `OfferRewardEmote1`, `OfferRewardEmote2`, `OfferRewardEmote3`, `OfferRewardEmote4`, `OfferRewardEmoteDelay1`, `OfferRewardEmoteDelay2`, `OfferRewardEmoteDelay3`, `OfferRewardEmoteDelay4`, `VerifiedBuild`) VALUES
(/*  ID    */802036,
 /*  Method  */ 2,
 /*  QuestLevel  */ 80,
 /*  MinLevel   */80,
 /*  QuestSortID  */ -1,
 /*  QuestType*/ 0,
 /*  SuggestedGroupNum  */ 0,
 /*  LimitTime  */ 0,
 /*  RequiredRaces   */1791,
 /*  RequiredFactionId1   */ 0,
 /*  RequiredFactionId2  */ 0,
 /*  RequiredFactionValue1  */ 0,
 /*  RequiredFactionValue2   */ 0,
 /*  NextQuestIdChain  */ 0,
 /*  RewardXPId   */70,
 /*  RewardOrRequiredMoney  */ 4000000,
 /*  RewardMoneyMaxLevel  */ 4000000,
 /*  RewardSpell   */ 0,
 /*  RewardSpellCast  */ 0,
 /*  RewardHonor  */ 0,
 /*  RewardHonorMultiplier  */ 0,
 /*  SourceItemId  */ 0,
 /*  Flags  */ 0,
 /*  RewardTitle  */ 0,
 /*  RequiredPlayerKills  */ 0,
 /*  RewardTalents  */ 0,
 /*  RewardArenaPoints  */ 0,
 /*  RewardIten    */ 41600,
 /*  RewardItem2   */ 700515,
 /*  RewardItem3   */ 0,
 /*  RewardItem4   */ 0,
 /*  RewardAmount1 */ 1,
 /*  RewardAmount2 */ 1,
 /*  RewardAmount3 */ 0,
 /*  RewardAmount4 */ 0,
 /*  RewardChoiceItemID1  */ 0,
 /*  RewardChoiceItemID2  */ 0,
 /*  RewardChoiceItemID3  */ 0,
 /*  RewardChoiceItemID4  */ 0,
 /*  RewardChoiceItemID5  */ 0,
 /*  RewardChoiceItemID6  */ 0,
 /*  RewardChoiceItemQuantity1  */ 0,
 /*  RewardChoiceItemQuantity2  */ 0,
 /*  RewardChoiceItemQuantity3  */ 0,
 /*  RewardChoiceItemQuantity4  */ 0,
 /*  RewardChoiceItemQuantity5  */ 0,
 /*  RewardChoiceItemQuantity6  */ 0,
 /*  RewardFactionID1  */ 0,
 /*  RewardFactionID2  */ 0,
 /*  RewardFactionID3  */ 0,
 /*  RewardFactionID4  */ 0,
 /*  RewardFactionID5  */ 0,
 /*  RewardFactionValue1  */ 0,
 /*  RewardFactionValue2  */ 0,
 /*  RewardFactionValue3  */ 0,
 /*  RewardFactionValue4  */ 0,
 /*  RewardFactionValue5 */ 0,
 /*  RewardFactionOverride1  */ 0,
 /*  RewardFactionOverride2  */ 0,
 /*  RewardFactionOverride3  */ 0,
 /*  RewardFactionOverride4  */ 0,
 /*  RewardFactionOverride5  */ 0,
 /*  PointMapId  */ 0,
 /*  PointX  */ 0,
 /*  PointY  */ 0,
 /*  PointOption  */ 0,
 /*  LogTitle  */ 'Die erste Spur',
 /*  LogDescription  */  'Wir haben eine erste Spur, bringt Kayoulas zerbrochene Anhängerstücke zu mir.',
 /*  QuestDescription   */ 'Hallo $N, ich habe aufregende Neuigkeiten für Euch. Wir haben durch die Auktionspapiere einen ersten Unterhändler ausfindig machen können. Anscheinend soll er am Überfall auf Exitares Frau beteiligt gewesen sein. Geht zu ihm und prüft ob er beteiligt war, und bringt entsprechende Beweise zu mir zurück. Ob er dabei am Leben bleibt oder nicht, ist mir egal. Macht was ihr wollt mit ihm.',
 /*  EndText   */  '',
 /*  OfferRewardText  */  'Seid ihr fertig?',
 /*  RequestItemsText  */ 'Wir haben eine erste Spur, bringt Kayoulas zerbrochener Anhänger zu mir.',
 /*  QuestCompletionLog  */ 'Es ist Eure Sache was ihr tut.',
 /*  RequiredNpcOrGo1  */ 0,
 /*  RequiredNpcOrGo2  */ 0,
 /*  RequiredNpcOrGo3  */ 0,
 /*  RequiredNpcOrGo4  */ 0,
 /*  RequiredNpcOrGoCount1  */ 0,
 /*  RequiredNpcOrGoCount2  */ 0,
 /*  RequiredNpcOrGoCount3  */ 0,
 /*  RequiredNpcOrGoCount4  */ 0,
 /*  RequiredSourceItemId1  */ 0,
 /*  RequiredSourceItemId2  */ 0,
 /*  RequiredSourceItemId3  */ 0,
 /*  RequiredSourceItemId4  */ 0,
 /*  RequiredSourceItemCount1  */ 0,
 /*  RequiredSourceItemCount2  */ 0,
 /*  RequiredSourceItemCount3  */ 0,
 /*  RequiredSourceItemCount4  */ 0,
 /*  RequiredItemId1  */ 700510,
 /*  RequiredItemId2  */ 700512,
 /*  RequiredItemId3  */ 700513,
 /*  RequiredItemId4  */ 700514,
 /*  RequiredItemId5  */ 0,
 /*  RequiredItemId6  */ 0,
 /*  RequiredItemCount1  */ 1,
 /*  RequiredItemCount2  */ 1,
 /*  RequiredItemCount3  */ 1,
 /*  RequiredItemCount4  */ 1,
 /*  RequiredItemCount5  */ 0,
 /*  RequiredItemCount6  */ 0,
 /*  Unknown0  */ 0,
 /*  ObjectiveText1  */'',
 /*  ObjectiveText2  */'',
 /*  ObjectiveText3  */'',
 /*  ObjectiveText4  */ '',
 /*  DetailsEmote1  */ 0,
 /*  DetailsEmote2  */ 0,
 /*  DetailsEmote3  */ 0,
 /*  DetailsEmote4   */ 0,
 /*  DetailsEmoteDelay1  */ 0,
 /*  DetailsEmoteDelay2  */ 0,
 /*  DetailsEmoteDelay3  */ 0,
 /*  DetailsEmoteDelay4  */ 0,
 /*  EmoteOnIncomplete  */ 0,
 /*  EmoteOnComplete  */ 0,
 /*  OfferRewardEmote1  */ 0,
 /*  OfferRewardEmote2  */ 0,
 /*  OfferRewardEmote3  */ 0,
 /*  OfferRewardEmote4  */ 0,
 /*  OfferRewardEmoteDelay1  */ 0,
 /*  OfferRewardEmoteDelay2  */ 0,
 /*  OfferRewardEmoteDelay3  */ 0,
 /*  OfferRewardEmoteDelay4  */ 0,
 1);



REPLACE INTO `quest_template_addon` (`ID`, `MaxLevel`, `AllowableClasses`, `SourceSpellID`, `PrevQuestID`, `NextQuestID`, `ExclusiveGroup`, `RewardMailTemplateID`, `RewardMailDelay`, `RequiredSkillID`, `RequiredSkillPoints`, `RequiredMinRepFaction`, `RequiredMaxRepFaction`, `RequiredMinRepValue`, `RequiredMaxRepValue`, `ProvidedItemCount`, `SpecialFlags`) VALUES
( /*  ID  */802036,
  /*  MaxLevel  */80,
  /*  AllowableClasses  */2047,
  /*  SourceSpellID  */ 0,
  /*   PrevQuestID */ 802035,
  /*  NextQuestID  */802037,
  /*  ExclusiveGroup  */ 0,
  /*   RewardMailTemplateID */ 0,
  /*  RewardMailDelay  */ 0,
  /*  RequiredSkillID  */ 0,
  /*  RequiredSkillPoints  */ 0,
  /*  RequiredMinRepFaction  */ 0,
  /*  RequiredMaxRepFaction  */ 0,
  /*   RequiredMinRepValue */ 0,
  /*  RequiredMaxRepValue  */ 0,
  /*  ProvidedItemCount  */ 0,
  /*   SpecialFlags */ 0);


REPLACE INTO `creature_questender` (`id`, `quest`) VALUES
(16991, 802036);

REPLACE INTO `creature_queststarter` (`id`, `quest`) VALUES
(16991, 802036);
DELETE FROM `quest_template` WHERE  `id` = 802037;
DELETE FROM `quest_template_addon` WHERE `id` = 802037;
DELETE FROM `creature_questender` WHERE `id` = 16991   AND `quest` = 802037;
DELETE FROM `creature_queststarter` WHERE `id` = 16991   AND `quest` = 802037;



REPLACE INTO `quest_template` (`ID`, `Method`, `QuestLevel`, `MinLevel`, `QuestSortID`, `QuestType`, `SuggestedGroupNum`, `LimitTime`, `RequiredRaces`, `RequiredFactionId1`, `RequiredFactionId2`, `RequiredFactionValue1`, `RequiredFactionValue2`, `NextQuestIdChain`, `RewardXPId`, `RewardOrRequiredMoney`, `RewardMoneyMaxLevel`, `RewardSpell`, `RewardSpellCast`, `RewardHonor`, `RewardHonorMultiplier`, `SourceItemId`, `Flags`, `RewardTitle`, `RequiredPlayerKills`, `RewardTalents`, `RewardArenaPoints`, `RewardItem1`, `RewardItem2`, `RewardItem3`, `RewardItem4`, `RewardAmount1`, `RewardAmount2`, `RewardAmount3`, `RewardAmount4`, `RewardChoiceItemID1`, `RewardChoiceItemID2`, `RewardChoiceItemID3`, `RewardChoiceItemID4`, `RewardChoiceItemID5`, `RewardChoiceItemID6`, `RewardChoiceItemQuantity1`, `RewardChoiceItemQuantity2`, `RewardChoiceItemQuantity3`, `RewardChoiceItemQuantity4`, `RewardChoiceItemQuantity5`, `RewardChoiceItemQuantity6`, `RewardFactionID1`, `RewardFactionID2`, `RewardFactionID3`, `RewardFactionID4`, `RewardFactionID5`, `RewardFactionValue1`, `RewardFactionValue2`, `RewardFactionValue3`, `RewardFactionValue4`, `RewardFactionValue5`, `RewardFactionOverride1`, `RewardFactionOverride2`, `RewardFactionOverride3`, `RewardFactionOverride4`, `RewardFactionOverride5`, `PointMapId`, `PointX`, `PointY`, `PointOption`, `LogTitle`, `LogDescription`, `QuestDescription`, `EndText`, `OfferRewardText`, `RequestItemsText`, `QuestCompletionLog`, `RequiredNpcOrGo1`, `RequiredNpcOrGo2`, `RequiredNpcOrGo3`, `RequiredNpcOrGo4`, `RequiredNpcOrGoCount1`, `RequiredNpcOrGoCount2`, `RequiredNpcOrGoCount3`, `RequiredNpcOrGoCount4`, `RequiredSourceItemId1`, `RequiredSourceItemId2`, `RequiredSourceItemId3`, `RequiredSourceItemId4`, `RequiredSourceItemCount1`, `RequiredSourceItemCount2`, `RequiredSourceItemCount3`, `RequiredSourceItemCount4`, `RequiredItemId1`, `RequiredItemId2`, `RequiredItemId3`, `RequiredItemId4`, `RequiredItemId5`, `RequiredItemId6`, `RequiredItemCount1`, `RequiredItemCount2`, `RequiredItemCount3`, `RequiredItemCount4`, `RequiredItemCount5`, `RequiredItemCount6`, `Unknown0`, `ObjectiveText1`, `ObjectiveText2`, `ObjectiveText3`, `ObjectiveText4`, `DetailsEmote1`, `DetailsEmote2`, `DetailsEmote3`, `DetailsEmote4`, `DetailsEmoteDelay1`, `DetailsEmoteDelay2`, `DetailsEmoteDelay3`, `DetailsEmoteDelay4`, `EmoteOnIncomplete`, `EmoteOnComplete`, `OfferRewardEmote1`, `OfferRewardEmote2`, `OfferRewardEmote3`, `OfferRewardEmote4`, `OfferRewardEmoteDelay1`, `OfferRewardEmoteDelay2`, `OfferRewardEmoteDelay3`, `OfferRewardEmoteDelay4`, `VerifiedBuild`) VALUES
(/*  ID    */802037,
 /*  Method  */ 2,
 /*  QuestLevel  */ 80,
 /*  MinLevel   */80,
 /*  QuestSortID  */ -1,
 /*  QuestType*/ 62,
 /*  SuggestedGroupNum  */ 0,
 /*  LimitTime  */ 0,
 /*  RequiredRaces   */1791,
 /*  RequiredFactionId1   */ 0,
 /*  RequiredFactionId2  */ 0,
 /*  RequiredFactionValue1  */ 0,
 /*  RequiredFactionValue2   */ 0,
 /*  NextQuestIdChain  */ 0,
 /*  RewardXPId   */70,
 /*  RewardOrRequiredMoney  */ 2000000,
 /*  RewardMoneyMaxLevel  */ 2000000,
 /*  RewardSpell   */ 0,
 /*  RewardSpellCast  */ 0,
 /*  RewardHonor  */ 0,
 /*  RewardHonorMultiplier  */ 0,
 /*  SourceItemId  */ 0,
 /*  Flags  */ 0,
 /*  RewardTitle  */ 0,
 /*  RequiredPlayerKills  */ 0,
 /*  RewardTalents  */ 0,
 /*  RewardArenaPoints  */ 0,
 /*  RewardIten    */ 700517,
 /*  RewardItem2   */ 0,
 /*  RewardItem3   */ 0,
 /*  RewardItem4   */ 0,
 /*  RewardAmount1 */ 1,
 /*  RewardAmount2 */ 0,
 /*  RewardAmount3 */ 0,
 /*  RewardAmount4 */ 0,
 /*  RewardChoiceItemID1  */ 0,
 /*  RewardChoiceItemID2  */ 0,
 /*  RewardChoiceItemID3  */ 0,
 /*  RewardChoiceItemID4  */ 0,
 /*  RewardChoiceItemID5  */ 0,
 /*  RewardChoiceItemID6  */ 0,
 /*  RewardChoiceItemQuantity1  */ 0,
 /*  RewardChoiceItemQuantity2  */ 0,
 /*  RewardChoiceItemQuantity3  */ 0,
 /*  RewardChoiceItemQuantity4  */ 0,
 /*  RewardChoiceItemQuantity5  */ 0,
 /*  RewardChoiceItemQuantity6  */ 0,
 /*  RewardFactionID1  */ 0,
 /*  RewardFactionID2  */ 0,
 /*  RewardFactionID3  */ 0,
 /*  RewardFactionID4  */ 0,
 /*  RewardFactionID5  */ 0,
 /*  RewardFactionValue1  */ 0,
 /*  RewardFactionValue2  */ 0,
 /*  RewardFactionValue3  */ 0,
 /*  RewardFactionValue4  */ 0,
 /*  RewardFactionValue5 */ 0,
 /*  RewardFactionOverride1  */ 0,
 /*  RewardFactionOverride2  */ 0,
 /*  RewardFactionOverride3  */ 0,
 /*  RewardFactionOverride4  */ 0,
 /*  RewardFactionOverride5  */ 0,
 /*  PointMapId  */ 0,
 /*  PointX  */ 0,
 /*  PointY  */ 0,
 /*  PointOption  */ 0,
 /*  LogTitle  */ 'Die Verfeinerung',
 /*  LogDescription  */  'Bringt mir die glitzernde Spinnenseide.',
 /*  QuestDescription   */ 'Hallo $N, wir haben den fertiggestellten Anhänger hier. Nun muss er mit glitzernder Spinnenseide umgarnt werden. Diese können wir nur bei der Königin der Spinnen finden. Maexxa. Geht zu ihr und entwedet ihr diesen extrem seltenen Seidenstoff. ',
 /*  EndText   */  '',
 /*  OfferRewardText  */  'Seid ihr fertig?',
 /*  RequestItemsText  */ 'Bringt mir die glitzernde Spinnenseide.',
 /*  QuestCompletionLog  */ 'Es ist Eure Sache was ihr tut.',
 /*  RequiredNpcOrGo1  */ 0,
 /*  RequiredNpcOrGo2  */ 0,
 /*  RequiredNpcOrGo3  */ 0,
 /*  RequiredNpcOrGo4  */ 0,
 /*  RequiredNpcOrGoCount1  */ 0,
 /*  RequiredNpcOrGoCount2  */ 0,
 /*  RequiredNpcOrGoCount3  */ 0,
 /*  RequiredNpcOrGoCount4  */ 0,
 /*  RequiredSourceItemId1  */ 0,
 /*  RequiredSourceItemId2  */ 0,
 /*  RequiredSourceItemId3  */ 0,
 /*  RequiredSourceItemId4  */ 0,
 /*  RequiredSourceItemCount1  */ 0,
 /*  RequiredSourceItemCount2  */ 0,
 /*  RequiredSourceItemCount3  */ 0,
 /*  RequiredSourceItemCount4  */ 0,
 /*  RequiredItemId1  */ 700515,
 /*  RequiredItemId2  */ 700516,
 /*  RequiredItemId3  */ 0,
 /*  RequiredItemId4  */ 0,
 /*  RequiredItemId5  */ 0,
 /*  RequiredItemId6  */ 0,
 /*  RequiredItemCount1  */ 1,
 /*  RequiredItemCount2  */ 1,
 /*  RequiredItemCount3  */ 0,
 /*  RequiredItemCount4  */ 0,
 /*  RequiredItemCount5  */ 0,
 /*  RequiredItemCount6  */ 0,
 /*  Unknown0  */ 0,
 /*  ObjectiveText1  */'',
 /*  ObjectiveText2  */'',
 /*  ObjectiveText3  */'',
 /*  ObjectiveText4  */ '',
 /*  DetailsEmote1  */ 0,
 /*  DetailsEmote2  */ 0,
 /*  DetailsEmote3  */ 0,
 /*  DetailsEmote4   */ 0,
 /*  DetailsEmoteDelay1  */ 0,
 /*  DetailsEmoteDelay2  */ 0,
 /*  DetailsEmoteDelay3  */ 0,
 /*  DetailsEmoteDelay4  */ 0,
 /*  EmoteOnIncomplete  */ 0,
 /*  EmoteOnComplete  */ 0,
 /*  OfferRewardEmote1  */ 0,
 /*  OfferRewardEmote2  */ 0,
 /*  OfferRewardEmote3  */ 0,
 /*  OfferRewardEmote4  */ 0,
 /*  OfferRewardEmoteDelay1  */ 0,
 /*  OfferRewardEmoteDelay2  */ 0,
 /*  OfferRewardEmoteDelay3  */ 0,
 /*  OfferRewardEmoteDelay4  */ 0,
 1);



REPLACE INTO `quest_template_addon` (`ID`, `MaxLevel`, `AllowableClasses`, `SourceSpellID`, `PrevQuestID`, `NextQuestID`, `ExclusiveGroup`, `RewardMailTemplateID`, `RewardMailDelay`, `RequiredSkillID`, `RequiredSkillPoints`, `RequiredMinRepFaction`, `RequiredMaxRepFaction`, `RequiredMinRepValue`, `RequiredMaxRepValue`, `ProvidedItemCount`, `SpecialFlags`) VALUES
( /*  ID  */802037,
  /*  MaxLevel  */80,
  /*  AllowableClasses  */2047,
  /*  SourceSpellID  */ 0,
  /*   PrevQuestID */ 802036,
  /*  NextQuestID  */802038,
  /*  ExclusiveGroup  */ 0,
  /*   RewardMailTemplateID */ 0,
  /*  RewardMailDelay  */ 0,
  /*  RequiredSkillID  */ 0,
  /*  RequiredSkillPoints  */ 0,
  /*  RequiredMinRepFaction  */ 0,
  /*  RequiredMaxRepFaction  */ 0,
  /*   RequiredMinRepValue */ 0,
  /*  RequiredMaxRepValue  */ 0,
  /*  ProvidedItemCount  */ 0,
  /*   SpecialFlags */ 0);


REPLACE INTO `creature_questender` (`id`, `quest`) VALUES
(16991, 802037);

REPLACE INTO `creature_queststarter` (`id`, `quest`) VALUES
(16991, 802037);
DELETE FROM `quest_template` WHERE  `id` = 802309;
DELETE FROM `quest_template_addon` WHERE `id` = 802309;
DELETE FROM `creature_questender` WHERE `id` = 800006   AND `quest` = 802309;
DELETE FROM `creature_queststarter` WHERE `id` = 800006   AND `quest` = 802309;


REPLACE INTO `quest_template` (`ID`, `Method`, `QuestLevel`, `MinLevel`, `QuestSortID`, `QuestType`, `SuggestedGroupNum`, `LimitTime`, `RequiredRaces`, `RequiredFactionId1`, `RequiredFactionId2`, `RequiredFactionValue1`, `RequiredFactionValue2`, `NextQuestIdChain`, `RewardXPId`, `RewardOrRequiredMoney`, `RewardMoneyMaxLevel`, `RewardSpell`, `RewardSpellCast`, `RewardHonor`, `RewardHonorMultiplier`, `SourceItemId`, `Flags`, `RewardTitle`, `RequiredPlayerKills`, `RewardTalents`, `RewardArenaPoints`, `RewardItem1`, `RewardItem2`, `RewardItem3`, `RewardItem4`, `RewardAmount1`, `RewardAmount2`, `RewardAmount3`, `RewardAmount4`, `RewardChoiceItemID1`, `RewardChoiceItemID2`, `RewardChoiceItemID3`, `RewardChoiceItemID4`, `RewardChoiceItemID5`, `RewardChoiceItemID6`, `RewardChoiceItemQuantity1`, `RewardChoiceItemQuantity2`, `RewardChoiceItemQuantity3`, `RewardChoiceItemQuantity4`, `RewardChoiceItemQuantity5`, `RewardChoiceItemQuantity6`, `RewardFactionID1`, `RewardFactionID2`, `RewardFactionID3`, `RewardFactionID4`, `RewardFactionID5`, `RewardFactionValue1`, `RewardFactionValue2`, `RewardFactionValue3`, `RewardFactionValue4`, `RewardFactionValue5`, `RewardFactionOverride1`, `RewardFactionOverride2`, `RewardFactionOverride3`, `RewardFactionOverride4`, `RewardFactionOverride5`, `PointMapId`, `PointX`, `PointY`, `PointOption`, `LogTitle`, `LogDescription`, `QuestDescription`, `EndText`, `OfferRewardText`, `RequestItemsText`, `QuestCompletionLog`, `RequiredNpcOrGo1`, `RequiredNpcOrGo2`, `RequiredNpcOrGo3`, `RequiredNpcOrGo4`, `RequiredNpcOrGoCount1`, `RequiredNpcOrGoCount2`, `RequiredNpcOrGoCount3`, `RequiredNpcOrGoCount4`, `RequiredSourceItemId1`, `RequiredSourceItemId2`, `RequiredSourceItemId3`, `RequiredSourceItemId4`, `RequiredSourceItemCount1`, `RequiredSourceItemCount2`, `RequiredSourceItemCount3`, `RequiredSourceItemCount4`, `RequiredItemId1`, `RequiredItemId2`, `RequiredItemId3`, `RequiredItemId4`, `RequiredItemId5`, `RequiredItemId6`, `RequiredItemCount1`, `RequiredItemCount2`, `RequiredItemCount3`, `RequiredItemCount4`, `RequiredItemCount5`, `RequiredItemCount6`, `Unknown0`, `ObjectiveText1`, `ObjectiveText2`, `ObjectiveText3`, `ObjectiveText4`, `DetailsEmote1`, `DetailsEmote2`, `DetailsEmote3`, `DetailsEmote4`, `DetailsEmoteDelay1`, `DetailsEmoteDelay2`, `DetailsEmoteDelay3`, `DetailsEmoteDelay4`, `EmoteOnIncomplete`, `EmoteOnComplete`, `OfferRewardEmote1`, `OfferRewardEmote2`, `OfferRewardEmote3`, `OfferRewardEmote4`, `OfferRewardEmoteDelay1`, `OfferRewardEmoteDelay2`, `OfferRewardEmoteDelay3`, `OfferRewardEmoteDelay4`, `VerifiedBuild`) VALUES
(/*  ID    */802309,
 /*  Method  */ 2,
 /*  QuestLevel  */ 80,
 /*  MinLevel   */80,
 /*  QuestSortID  */ -1,
 /*  QuestType*/ 62,
 /*  SuggestedGroupNum  */ 0,
 /*  LimitTime  */ 0,
 /*  RequiredRaces   */1791,
 /*  RequiredFactionId1   */ 0,
 /*  RequiredFactionId2  */ 0,
 /*  RequiredFactionValue1  */ 0,
 /*  RequiredFactionValue2   */ 0,
 /*  NextQuestIdChain  */ 0,
 /*  RewardXPId   */70,
 /*  RewardOrRequiredMoney  */ 5000000,
 /*  RewardMoneyMaxLevel  */ 10000000,
 /*  RewardSpell   */ 0,
 /*  RewardSpellCast  */ 0,
 /*  RewardHonor  */ 0,
 /*  RewardHonorMultiplier  */ 0,
 /*  SourceItemId  */ 1381,
 /*  Flags  */ 0,
 /*  RewardTitle  */ 0,
 /*  RequiredPlayerKills  */ 0,
 /*  RewardTalents  */ 0,
 /*  RewardArenaPoints  */ 0,
 /*  RewardIten */ 0,
 /*  RewardItem2  */ 0,
 /*  RewardItem3  */ 0,
 /*  RewardItem4  */ 0,
 /*  RewardAmount1*/ 0,
 /*  RewardAmount2  */ 0,
 /*  RewardAmount3 */ 0,
 /*  RewardAmount4  */ 0,
 /*  RewardChoiceItemID1  */ 49632,
 /*  RewardChoiceItemID2  */ 0,
 /*  RewardChoiceItemID3  */ 0,
 /*  RewardChoiceItemID4  */ 0,
 /*  RewardChoiceItemID5 */  0,
 /*  RewardChoiceItemID6 */  0,
 /*  RewardChoiceItemQuantity1  */ 5,
 /*  RewardChoiceItemQuantity2  */ 0,
 /*  RewardChoiceItemQuantity3  */ 0,
 /*  RewardChoiceItemQuantity4  */ 0,
 /*  RewardChoiceItemQuantity5  */ 0,
 /*  RewardChoiceItemQuantity6  */ 0,
 /*  RewardFactionID1  */ 0,
 /*  RewardFactionID2  */ 0,
 /*  RewardFactionID3  */ 0,
 /*  RewardFactionID4  */ 0,
 /*  RewardFactionID5  */ 0,
 /*  RewardFactionValue1  */ 0,
 /*  RewardFactionValue2  */ 0,
 /*  RewardFactionValue3  */ 0,
 /*  RewardFactionValue4  */ 0,
 /*  RewardFactionValue5 */ 0,
 /*  RewardFactionOverride1  */ 0,
 /*  RewardFactionOverride2  */ 0,
 /*  RewardFactionOverride3  */ 0,
 /*  RewardFactionOverride4  */ 0,
 /*  RewardFactionOverride5  */ 0,
 /*  PointMapId  */ 0,
 /*  PointX  */ 0,
 /*  PointY  */ 0,
 /*  PointOption  */ 0,
 /*  LogTitle  */ 'Das flammende Herz',
 /*  LogDescription  */  'Bringt Torvan das flammende Herz',
 /*  QuestDescription   */ 'Jetzt wo ihr mir mein Gold gebracht habt, kann ich ja normal mit Euch reden. Bringt mir das flammende Herz des Verdammniswandlers! És ist ein wertvolles episches Stück! Damit lässt sich auf dem Schwarzmarkt ein guter Preis erzielen.',
 /*  EndText   */  '',
 /*  OfferRewardText  */  'Seid ihr fertig?',
 /*  RequestItemsText  */ 'Bringt Torvan das flammende Herz',
 /*  QuestCompletionLog  */ 'Es ist Eure Sache was ihr tut.',
 /*  RequiredNpcOrGo1  */ 0,
 /*  RequiredNpcOrGo2  */ 0,
 /*  RequiredNpcOrGo3  */ 0,
 /*  RequiredNpcOrGo4  */ 0,
 /*  RequiredNpcOrGoCount1  */ 0,
 /*  RequiredNpcOrGoCount2  */ 0,
 /*  RequiredNpcOrGoCount3  */ 0,
 /*  RequiredNpcOrGoCount4  */ 0,
 /*  RequiredSourceItemId1  */ 0,
 /*  RequiredSourceItemId2  */ 0,
 /*  RequiredSourceItemId3  */ 0,
 /*  RequiredSourceItemId4  */ 0,
 /*  RequiredSourceItemCount1  */ 0,
 /*  RequiredSourceItemCount2  */ 0,
 /*  RequiredSourceItemCount3  */ 0,
 /*  RequiredSourceItemCount4  */ 0,
 /*  RequiredItemId1  */ 700507,
 /*  RequiredItemId2  */ 0,
 /*  RequiredItemId3  */ 0,
 /*  RequiredItemId4  */ 0,
 /*  RequiredItemId5  */ 0,
 /*  RequiredItemId6  */ 0,
 /*  RequiredItemCount1  */ 1,
 /*  RequiredItemCount2  */ 0,
 /*  RequiredItemCount3  */ 0,
 /*  RequiredItemCount4  */ 0,
 /*  RequiredItemCount5  */ 0,
 /*  RequiredItemCount6  */ 0,
 /*  Unknown0  */ 0,
 /*  ObjectiveText1  */'',
 /*  ObjectiveText2  */'',
 /*  ObjectiveText3  */'',
 /*  ObjectiveText4  */ '',
 /*  DetailsEmote1  */ 0,
 /*  DetailsEmote2  */ 0,
 /*  DetailsEmote3  */ 0,
 /*  DetailsEmote4   */ 0,
 /*  DetailsEmoteDelay1  */ 0,
 /*  DetailsEmoteDelay2  */ 0,
 /*  DetailsEmoteDelay3  */ 0,
 /*  DetailsEmoteDelay4  */ 0,
 /*  EmoteOnIncomplete  */ 0,
 /*  EmoteOnComplete  */ 0,
 /*  OfferRewardEmote1  */ 0,
 /*  OfferRewardEmote2  */ 0,
 /*  OfferRewardEmote3  */ 0,
 /*  OfferRewardEmote4  */ 0,
 /*  OfferRewardEmoteDelay1  */ 0,
 /*  OfferRewardEmoteDelay2  */ 0,
 /*  OfferRewardEmoteDelay3  */ 0,
 /*  OfferRewardEmoteDelay4  */ 0,
 1);



REPLACE INTO `quest_template_addon` (`ID`, `MaxLevel`, `AllowableClasses`, `SourceSpellID`, `PrevQuestID`, `NextQuestID`, `ExclusiveGroup`, `RewardMailTemplateID`, `RewardMailDelay`, `RequiredSkillID`, `RequiredSkillPoints`, `RequiredMinRepFaction`, `RequiredMaxRepFaction`, `RequiredMinRepValue`, `RequiredMaxRepValue`, `ProvidedItemCount`, `SpecialFlags`) VALUES
( /*  ID  */802309,
  /*  MaxLevel  */80,
  /*  AllowableClasses  */2047,
  /*  SourceSpellID  */ 0,
  /*   PrevQuestID */ 802308,
  /*  NextQuestID  */ 802310,
  /*  ExclusiveGroup  */ 0,
  /*   RewardMailTemplateID */ 0,
  /*  RewardMailDelay  */ 0,
  /*  RequiredSkillID  */ 0,
  /*  RequiredSkillPoints  */ 0,
  /*  RequiredMinRepFaction  */ 0,
  /*  RequiredMaxRepFaction  */ 0,
  /*   RequiredMinRepValue */ 0,
  /*  RequiredMaxRepValue  */ 0,
  /*  ProvidedItemCount  */ 0,
  /*   SpecialFlags */ 0);


REPLACE INTO `creature_questender` (`id`, `quest`) VALUES
(800006, 802309);

REPLACE INTO `creature_queststarter` (`id`, `quest`) VALUES
(800006, 802309);

DELETE FROM `quest_template` WHERE  `id` = 802310;
DELETE FROM `quest_template_addon` WHERE `id` = 802310;
DELETE FROM `creature_questender` WHERE `id` = 800006   AND `quest` = 802310;
DELETE FROM `creature_queststarter` WHERE `id` = 800006   AND `quest` = 802310;


REPLACE INTO `quest_template` (`ID`, `Method`, `QuestLevel`, `MinLevel`, `QuestSortID`, `QuestType`, `SuggestedGroupNum`, `LimitTime`, `RequiredRaces`, `RequiredFactionId1`, `RequiredFactionId2`, `RequiredFactionValue1`, `RequiredFactionValue2`, `NextQuestIdChain`, `RewardXPId`, `RewardOrRequiredMoney`, `RewardMoneyMaxLevel`, `RewardSpell`, `RewardSpellCast`, `RewardHonor`, `RewardHonorMultiplier`, `SourceItemId`, `Flags`, `RewardTitle`, `RequiredPlayerKills`, `RewardTalents`, `RewardArenaPoints`, `RewardItem1`, `RewardItem2`, `RewardItem3`, `RewardItem4`, `RewardAmount1`, `RewardAmount2`, `RewardAmount3`, `RewardAmount4`, `RewardChoiceItemID1`, `RewardChoiceItemID2`, `RewardChoiceItemID3`, `RewardChoiceItemID4`, `RewardChoiceItemID5`, `RewardChoiceItemID6`, `RewardChoiceItemQuantity1`, `RewardChoiceItemQuantity2`, `RewardChoiceItemQuantity3`, `RewardChoiceItemQuantity4`, `RewardChoiceItemQuantity5`, `RewardChoiceItemQuantity6`, `RewardFactionID1`, `RewardFactionID2`, `RewardFactionID3`, `RewardFactionID4`, `RewardFactionID5`, `RewardFactionValue1`, `RewardFactionValue2`, `RewardFactionValue3`, `RewardFactionValue4`, `RewardFactionValue5`, `RewardFactionOverride1`, `RewardFactionOverride2`, `RewardFactionOverride3`, `RewardFactionOverride4`, `RewardFactionOverride5`, `PointMapId`, `PointX`, `PointY`, `PointOption`, `LogTitle`, `LogDescription`, `QuestDescription`, `EndText`, `OfferRewardText`, `RequestItemsText`, `QuestCompletionLog`, `RequiredNpcOrGo1`, `RequiredNpcOrGo2`, `RequiredNpcOrGo3`, `RequiredNpcOrGo4`, `RequiredNpcOrGoCount1`, `RequiredNpcOrGoCount2`, `RequiredNpcOrGoCount3`, `RequiredNpcOrGoCount4`, `RequiredSourceItemId1`, `RequiredSourceItemId2`, `RequiredSourceItemId3`, `RequiredSourceItemId4`, `RequiredSourceItemCount1`, `RequiredSourceItemCount2`, `RequiredSourceItemCount3`, `RequiredSourceItemCount4`, `RequiredItemId1`, `RequiredItemId2`, `RequiredItemId3`, `RequiredItemId4`, `RequiredItemId5`, `RequiredItemId6`, `RequiredItemCount1`, `RequiredItemCount2`, `RequiredItemCount3`, `RequiredItemCount4`, `RequiredItemCount5`, `RequiredItemCount6`, `Unknown0`, `ObjectiveText1`, `ObjectiveText2`, `ObjectiveText3`, `ObjectiveText4`, `DetailsEmote1`, `DetailsEmote2`, `DetailsEmote3`, `DetailsEmote4`, `DetailsEmoteDelay1`, `DetailsEmoteDelay2`, `DetailsEmoteDelay3`, `DetailsEmoteDelay4`, `EmoteOnIncomplete`, `EmoteOnComplete`, `OfferRewardEmote1`, `OfferRewardEmote2`, `OfferRewardEmote3`, `OfferRewardEmote4`, `OfferRewardEmoteDelay1`, `OfferRewardEmoteDelay2`, `OfferRewardEmoteDelay3`, `OfferRewardEmoteDelay4`, `VerifiedBuild`) VALUES
(/*  ID    */802310,
 /*  Method  */ 2,
 /*  QuestLevel  */ 80,
 /*  MinLevel   */80,
 /*  QuestSortID  */ -1,
 /*  QuestType*/ 62,
 /*  SuggestedGroupNum  */ 0,
 /*  LimitTime  */ 0,
 /*  RequiredRaces   */1791,
 /*  RequiredFactionId1   */ 0,
 /*  RequiredFactionId2  */ 0,
 /*  RequiredFactionValue1  */ 0,
 /*  RequiredFactionValue2   */ 0,
 /*  NextQuestIdChain  */ 0,
 /*  RewardXPId   */70,
 /*  RewardOrRequiredMoney  */ 50000000,
 /*  RewardMoneyMaxLevel  */ 10000000,
 /*  RewardSpell   */ 0,
 /*  RewardSpellCast  */ 0,
 /*  RewardHonor  */ 0,
 /*  RewardHonorMultiplier  */ 0,
 /*  SourceItemId  */ 1381,
 /*  Flags  */ 0,
 /*  RewardTitle  */ 0,
 /*  RequiredPlayerKills  */ 0,
 /*  RewardTalents  */ 0,
 /*  RewardArenaPoints  */ 0,
 /*  RewardIten */ 0,
 /*  RewardItem2  */ 0,
 /*  RewardItem3  */ 0,
 /*  RewardItem4  */ 0,
 /*  RewardAmount1*/ 0,
 /*  RewardAmount2  */ 0,
 /*  RewardAmount3 */ 0,
 /*  RewardAmount4  */ 0,
 /*  RewardChoiceItemID1  */ 0,
 /*  RewardChoiceItemID2  */ 0,
 /*  RewardChoiceItemID3  */ 0,
 /*  RewardChoiceItemID4  */ 0,
 /*  RewardChoiceItemID5 */  0,
 /*  RewardChoiceItemID6 */  0,
 /*  RewardChoiceItemQuantity1  */ 0,
 /*  RewardChoiceItemQuantity2  */ 0,
 /*  RewardChoiceItemQuantity3  */ 0,
 /*  RewardChoiceItemQuantity4  */ 0,
 /*  RewardChoiceItemQuantity5  */ 0,
 /*  RewardChoiceItemQuantity6  */ 0,
 /*  RewardFactionID1  */ 0,
 /*  RewardFactionID2  */ 0,
 /*  RewardFactionID3  */ 0,
 /*  RewardFactionID4  */ 0,
 /*  RewardFactionID5  */ 0,
 /*  RewardFactionValue1  */ 0,
 /*  RewardFactionValue2  */ 0,
 /*  RewardFactionValue3  */ 0,
 /*  RewardFactionValue4  */ 0,
 /*  RewardFactionValue5 */ 0,
 /*  RewardFactionOverride1  */ 0,
 /*  RewardFactionOverride2  */ 0,
 /*  RewardFactionOverride3  */ 0,
 /*  RewardFactionOverride4  */ 0,
 /*  RewardFactionOverride5  */ 0,
 /*  PointMapId  */ 0,
 /*  PointX  */ 0,
 /*  PointY  */ 0,
 /*  PointOption  */ 0,
 /*  LogTitle  */ 'Das brennende Herz',
 /*  LogDescription  */  'Bringt Torvan das brennende Herz',
 /*  QuestDescription   */ 'Der Verkauf des flammenden Herzen hat mir eine Menge Gold eingebracht. Ich habe von einem weiteren Herzen gehört. Bringt mir das brennende Herz des Verdammniswandlers Kazzak! És ist ein wertvolles episches Stück! Damit lässt sich auf dem Schwarzmarkt ein guter Preis erzielen. Wenn ihr mir beides gebracht habt, bekommt ihr ein Teil des Erlöses.',
 /*  EndText   */  '',
 /*  OfferRewardText  */  'Seid ihr fertig?',
 /*  RequestItemsText  */ 'Bringt Torvan das brennende Herz',
 /*  QuestCompletionLog  */ 'Es ist Eure Sache was ihr tut.',
 /*  RequiredNpcOrGo1  */ 0,
 /*  RequiredNpcOrGo2  */ 0,
 /*  RequiredNpcOrGo3  */ 0,
 /*  RequiredNpcOrGo4  */ 0,
 /*  RequiredNpcOrGoCount1  */ 0,
 /*  RequiredNpcOrGoCount2  */ 0,
 /*  RequiredNpcOrGoCount3  */ 0,
 /*  RequiredNpcOrGoCount4  */ 0,
 /*  RequiredSourceItemId1  */ 0,
 /*  RequiredSourceItemId2  */ 0,
 /*  RequiredSourceItemId3  */ 0,
 /*  RequiredSourceItemId4  */ 0,
 /*  RequiredSourceItemCount1  */ 0,
 /*  RequiredSourceItemCount2  */ 0,
 /*  RequiredSourceItemCount3  */ 0,
 /*  RequiredSourceItemCount4  */ 0,
 /*  RequiredItemId1  */ 700508,
 /*  RequiredItemId2  */ 0,
 /*  RequiredItemId3  */ 0,
 /*  RequiredItemId4  */ 0,
 /*  RequiredItemId5  */ 0,
 /*  RequiredItemId6  */ 0,
 /*  RequiredItemCount1  */ 1,
 /*  RequiredItemCount2  */ 0,
 /*  RequiredItemCount3  */ 0,
 /*  RequiredItemCount4  */ 0,
 /*  RequiredItemCount5  */ 0,
 /*  RequiredItemCount6  */ 0,
 /*  Unknown0  */ 0,
 /*  ObjectiveText1  */'',
 /*  ObjectiveText2  */'',
 /*  ObjectiveText3  */'',
 /*  ObjectiveText4  */ '',
 /*  DetailsEmote1  */ 0,
 /*  DetailsEmote2  */ 0,
 /*  DetailsEmote3  */ 0,
 /*  DetailsEmote4   */ 0,
 /*  DetailsEmoteDelay1  */ 0,
 /*  DetailsEmoteDelay2  */ 0,
 /*  DetailsEmoteDelay3  */ 0,
 /*  DetailsEmoteDelay4  */ 0,
 /*  EmoteOnIncomplete  */ 0,
 /*  EmoteOnComplete  */ 0,
 /*  OfferRewardEmote1  */ 0,
 /*  OfferRewardEmote2  */ 0,
 /*  OfferRewardEmote3  */ 0,
 /*  OfferRewardEmote4  */ 0,
 /*  OfferRewardEmoteDelay1  */ 0,
 /*  OfferRewardEmoteDelay2  */ 0,
 /*  OfferRewardEmoteDelay3  */ 0,
 /*  OfferRewardEmoteDelay4  */ 0,
 1);



REPLACE INTO `quest_template_addon` (`ID`, `MaxLevel`, `AllowableClasses`, `SourceSpellID`, `PrevQuestID`, `NextQuestID`, `ExclusiveGroup`, `RewardMailTemplateID`, `RewardMailDelay`, `RequiredSkillID`, `RequiredSkillPoints`, `RequiredMinRepFaction`, `RequiredMaxRepFaction`, `RequiredMinRepValue`, `RequiredMaxRepValue`, `ProvidedItemCount`, `SpecialFlags`) VALUES
( /*  ID  */802310,
  /*  MaxLevel  */80,
  /*  AllowableClasses  */2047,
  /*  SourceSpellID  */ 0,
  /*   PrevQuestID */ 802308,
  /*  NextQuestID  */ 802311,
  /*  ExclusiveGroup  */ 0,
  /*   RewardMailTemplateID */ 0,
  /*  RewardMailDelay  */ 0,
  /*  RequiredSkillID  */ 0,
  /*  RequiredSkillPoints  */ 0,
  /*  RequiredMinRepFaction  */ 0,
  /*  RequiredMaxRepFaction  */ 0,
  /*   RequiredMinRepValue */ 0,
  /*  RequiredMaxRepValue  */ 0,
  /*  ProvidedItemCount  */ 0,
  /*   SpecialFlags */ 0);


REPLACE INTO `creature_questender` (`id`, `quest`) VALUES
(800006, 802310);

REPLACE INTO `creature_queststarter` (`id`, `quest`) VALUES
(800006, 802310);

DELETE FROM `quest_template` WHERE  `id` = 870002;
DELETE FROM `quest_template_addon` WHERE `id` = 870002;
DELETE FROM `creature_questender` WHERE `id` = 800053   AND `quest` = 870002;
DELETE FROM `creature_queststarter` WHERE `id` = 800028   AND `quest` = 870002;

REPLACE INTO `quest_template` (`ID`, `Method`, `QuestLevel`, `MinLevel`, `QuestSortID`, `QuestType`, `SuggestedGroupNum`, `LimitTime`, `RequiredRaces`, `RequiredFactionId1`, `RequiredFactionId2`, `RequiredFactionValue1`, `RequiredFactionValue2`, `NextQuestIdChain`, `RewardXPId`, `RewardOrRequiredMoney`, `RewardMoneyMaxLevel`, `RewardSpell`, `RewardSpellCast`, `RewardHonor`, `RewardHonorMultiplier`, `SourceItemId`, `Flags`, `RewardTitle`, `RequiredPlayerKills`, `RewardTalents`, `RewardArenaPoints`, `RewardItem1`, `RewardItem2`, `RewardItem3`, `RewardItem4`, `RewardAmount1`, `RewardAmount2`, `RewardAmount3`, `RewardAmount4`, `RewardChoiceItemID1`, `RewardChoiceItemID2`, `RewardChoiceItemID3`, `RewardChoiceItemID4`, `RewardChoiceItemID5`, `RewardChoiceItemID6`, `RewardChoiceItemQuantity1`, `RewardChoiceItemQuantity2`, `RewardChoiceItemQuantity3`, `RewardChoiceItemQuantity4`, `RewardChoiceItemQuantity5`, `RewardChoiceItemQuantity6`, `RewardFactionID1`, `RewardFactionID2`, `RewardFactionID3`, `RewardFactionID4`, `RewardFactionID5`, `RewardFactionValue1`, `RewardFactionValue2`, `RewardFactionValue3`, `RewardFactionValue4`, `RewardFactionValue5`, `RewardFactionOverride1`, `RewardFactionOverride2`, `RewardFactionOverride3`, `RewardFactionOverride4`, `RewardFactionOverride5`, `PointMapId`, `PointX`, `PointY`, `PointOption`, `LogTitle`, `LogDescription`, `QuestDescription`, `EndText`, `OfferRewardText`, `RequestItemsText`, `QuestCompletionLog`, `RequiredNpcOrGo1`, `RequiredNpcOrGo2`, `RequiredNpcOrGo3`, `RequiredNpcOrGo4`, `RequiredNpcOrGoCount1`, `RequiredNpcOrGoCount2`, `RequiredNpcOrGoCount3`, `RequiredNpcOrGoCount4`, `RequiredSourceItemId1`, `RequiredSourceItemId2`, `RequiredSourceItemId3`, `RequiredSourceItemId4`, `RequiredSourceItemCount1`, `RequiredSourceItemCount2`, `RequiredSourceItemCount3`, `RequiredSourceItemCount4`, `RequiredItemId1`, `RequiredItemId2`, `RequiredItemId3`, `RequiredItemId4`, `RequiredItemId5`, `RequiredItemId6`, `RequiredItemCount1`, `RequiredItemCount2`, `RequiredItemCount3`, `RequiredItemCount4`, `RequiredItemCount5`, `RequiredItemCount6`, `Unknown0`, `ObjectiveText1`, `ObjectiveText2`, `ObjectiveText3`, `ObjectiveText4`, `DetailsEmote1`, `DetailsEmote2`, `DetailsEmote3`, `DetailsEmote4`, `DetailsEmoteDelay1`, `DetailsEmoteDelay2`, `DetailsEmoteDelay3`, `DetailsEmoteDelay4`, `EmoteOnIncomplete`, `EmoteOnComplete`, `OfferRewardEmote1`, `OfferRewardEmote2`, `OfferRewardEmote3`, `OfferRewardEmote4`, `OfferRewardEmoteDelay1`, `OfferRewardEmoteDelay2`, `OfferRewardEmoteDelay3`, `OfferRewardEmoteDelay4`, `VerifiedBuild`) VALUES
(/*  ID    */870002,
 /*  Method  */ 2,
 /*  QuestLevel  */ 80, 
 /*  MinLevel   */80,
 /*  QuestSortID  */ -1,
 /*  QuestType*/ 0,
 /*  SuggestedGroupNum  */ 0,
 /*  LimitTime  */ 0,
 /*  RequiredRaces   */1791,
 /*  RequiredFactionId1   */ 0,
 /*  RequiredFactionId2  */ 0,
 /*  RequiredFactionValue1  */ 0,
 /*  RequiredFactionValue2   */ 0,
 /*  NextQuestIdChain  */ 0,
 /*  RewardXPId   */0,
 /*  RewardOrRequiredMoney  */ 100000,
 /*  RewardMoneyMaxLevel  */ 100000,	
 /*  RewardSpell   */ 0,
 /*  RewardSpellCast  */ 0,
 /*  RewardHonor  */ 0,
 /*  RewardHonorMultiplier  */ 0,
 /*  SourceItemId  */ 0,
 /*  Flags  */ 0,
 /*  RewardTitle  */ 0,
 /*  RequiredPlayerKills  */ 0,
 /*  RewardTalents  */ 0,
 /*  RewardArenaPoints  */ 0,
 /*  RewardItem1  */ 0,
 /*  RewardItem2  */ 0,
 /*  RewardItem3  */ 0,
 /*  RewardItem4  */ 0,
 /*  RewardAmount1*/ 0,
 /*  RewardAmount2  */ 0,
 /*  RewardAmount3  */ 0,
 /*  RewardAmount4  */ 0,
 /*  RewardChoiceItemID1  */ 0,
 /*  RewardChoiceItemID2  */ 0,
 /*  RewardChoiceItemID3  */ 0,
 /*  RewardChoiceItemID4  */ 0,
 /*  RewardChoiceItemID5  */ 0,
 /*  RewardChoiceItemID6  */ 0,
 /*  RewardChoiceItemQuantity1  */ 0,
 /*  RewardChoiceItemQuantity2  */ 0,
 /*  RewardChoiceItemQuantity3  */ 0,
 /*  RewardChoiceItemQuantity4  */ 0,
 /*  RewardChoiceItemQuantity5  */ 0,
 /*  RewardChoiceItemQuantity6  */ 0,
 /*  RewardFactionID1  */ 0,
 /*  RewardFactionID2  */ 0,
 /*  RewardFactionID3  */ 0,
 /*  RewardFactionID4  */ 0,
 /*  RewardFactionID5  */ 0,
 /*  RewardFactionValue1  */ 0,
 /*  RewardFactionValue2  */ 0,
 /*  RewardFactionValue3  */ 0,
 /*  RewardFactionValue4  */ 0,
 /*  RewardFactionValue5 */ 0,
 /*  RewardFactionOverride1  */ 0,
 /*  RewardFactionOverride2  */ 0,
 /*  RewardFactionOverride3  */ 0,
 /*  RewardFactionOverride4  */ 0,
 /*  RewardFactionOverride5  */ 0,
 /*  PointMapId  */ 0,
 /*  PointX  */ 0,
 /*  PointY  */ 0,
 /*  PointOption  */ 0,
 /*  LogTitle  */ 'Reise zum Außenposten der Sammler',
 /*  LogDescription  */  'Reist zum Außenposten der Sammler um Euch dort mit Moons Stellvertreter zu treffen.',
 /*  QuestDescription   */ 'Hallo $N. Ihr habt es geschafft. Ihr habt bewiesen das ihr würdig seid den Sammlern gegenüber treten zu können. Am Flussnabel ist unser erster Außenposten. Reißt dorthin um in unsere Gemeinschaft aufgenommen zu werden.',
 /*  EndText */  '',
 /*  OfferRewardText bevor man beendet  */  'Reist zum Außenposten der Sammler um Euch dort mit Moons Stellvertreter zu treffen.',
 /*  RequestItemsText  */ 'Hallo $N, hast du die Aufgabe abgeschlossen?',
 /*  Quest Completed Text wird rechts im Questlog angezeigt der Text */ '',
 /*  RequiredNpcOrGo1  */ 0,
 /*  RequiredNpcOrGo2  */ 0,
 /*  RequiredNpcOrGo3  */ 0,
 /*  RequiredNpcOrGo4  */ 0,
 /*  RequiredNpcOrGoCount1  */ 0,
 /*  RequiredNpcOrGoCount2  */ 0,
 /*  RequiredNpcOrGoCount3  */ 0,
 /*  RequiredNpcOrGoCount4  */ 0,
 /*  RequiredSourceItemId1  */ 0,
 /*  RequiredSourceItemId2  */ 0,
 /*  RequiredSourceItemId3  */ 0,
 /*  RequiredSourceItemId4  */ 0,
 /*  RequiredSourceItemCount1  */ 0,
 /*  RequiredSourceItemCount2  */ 0,
 /*  RequiredSourceItemCount3  */ 0,
 /*  RequiredSourceItemCount4  */ 0,
 /*  RequiredItemId1  */ 0,
 /*  RequiredItemId2  */ 0,
 /*  RequiredItemId3  */ 0,
 /*  RequiredItemId4  */ 0,
 /*  RequiredItemId5  */ 0,
 /*  RequiredItemId6  */ 0,
 /*  RequiredItemCount1  */ 0,
 /*  RequiredItemCount2  */ 0,
 /*  RequiredItemCount3  */ 0,
 /*  RequiredItemCount4  */ 0,
 /*  RequiredItemCount5  */ 0,
 /*  RequiredItemCount6  */ 0,
 /*  Unknown0  */ 0,
 /*  ObjectiveText1  */'',
 /*  ObjectiveText2  */'',
 /*  ObjectiveText3  */'',
 /*  ObjectiveText4  */'',
 /*  DetailsEmote1  */ 0,
 /*  DetailsEmote2  */ 0,
 /*  DetailsEmote3  */ 0,
 /*  DetailsEmote4  */ 0,
 /*  DetailsEmoteDelay1  */ 0,
 /*  DetailsEmoteDelay2  */ 0,
 /*  DetailsEmoteDelay3  */ 0,
 /*  DetailsEmoteDelay4  */ 0,
 /*  EmoteOnIncomplete  */ 0,
 /*  EmoteOnComplete  */ 0,
 /*  OfferRewardEmote1  */ 0,
 /*  OfferRewardEmote2  */ 0,
 /*  OfferRewardEmote3  */ 0,
 /*  OfferRewardEmote4  */ 0,
 /*  OfferRewardEmoteDelay1  */ 0,
 /*  OfferRewardEmoteDelay2  */ 0,
 /*  OfferRewardEmoteDelay3  */ 0,
 /*  OfferRewardEmoteDelay4  */ 0,
 1);

REPLACE INTO `quest_template_addon` (`ID`, `MaxLevel`, `AllowableClasses`, `SourceSpellID`, `PrevQuestID`, `NextQuestID`, `ExclusiveGroup`, `RewardMailTemplateID`, `RewardMailDelay`, `RequiredSkillID`, `RequiredSkillPoints`, `RequiredMinRepFaction`, `RequiredMaxRepFaction`, `RequiredMinRepValue`, `RequiredMaxRepValue`, `ProvidedItemCount`, `SpecialFlags`) VALUES
( /*  ID  */870002,
  /*  MaxLevel  */80,
  /*  AllowableClasses  */2047,
  /*  SourceSpellID  */ 0,
  /*  PrevQuestID */ 870001,
  /*  NextQuestID  */870003,
  /*  ExclusiveGroup  */ 0,
  /*  RewardMailTemplateID */ 0,
  /*  RewardMailDelay  */ 0,
  /*  RequiredSkillID  */ 0,
  /*  RequiredSkillPoints  */ 0,
  /*  RequiredMinRepFaction  */ 0,
  /*  RequiredMaxRepFaction  */ 0,
  /*  RequiredMinRepValue */ 0,
  /*  RequiredMaxRepValue  */ 0,
  /*  ProvidedItemCount  */ 0,
  /*  SpecialFlags */ 0);

REPLACE INTO `creature_queststarter` (`id`, `quest`) VALUES
(800028, 870002);

REPLACE INTO `creature_questender` (`id`, `quest`) VALUES
(800053, 870002);


DELETE FROM `quest_template` WHERE  `id` = 870003;
DELETE FROM `quest_template_addon` WHERE `id` = 870003;
DELETE FROM `creature_questender` WHERE `id` = 800056   AND `quest` = 870003;
DELETE FROM `creature_queststarter` WHERE `id` = 800053   AND `quest` = 870003;

REPLACE INTO `quest_template` (`ID`, `Method`, `QuestLevel`, `MinLevel`, `QuestSortID`, `QuestType`, `SuggestedGroupNum`, `LimitTime`, `RequiredRaces`, `RequiredFactionId1`, `RequiredFactionId2`, `RequiredFactionValue1`, `RequiredFactionValue2`, `NextQuestIdChain`, `RewardXPId`, `RewardOrRequiredMoney`, `RewardMoneyMaxLevel`, `RewardSpell`, `RewardSpellCast`, `RewardHonor`, `RewardHonorMultiplier`, `SourceItemId`, `Flags`, `RewardTitle`, `RequiredPlayerKills`, `RewardTalents`, `RewardArenaPoints`, `RewardItem1`, `RewardItem2`, `RewardItem3`, `RewardItem4`, `RewardAmount1`, `RewardAmount2`, `RewardAmount3`, `RewardAmount4`, `RewardChoiceItemID1`, `RewardChoiceItemID2`, `RewardChoiceItemID3`, `RewardChoiceItemID4`, `RewardChoiceItemID5`, `RewardChoiceItemID6`, `RewardChoiceItemQuantity1`, `RewardChoiceItemQuantity2`, `RewardChoiceItemQuantity3`, `RewardChoiceItemQuantity4`, `RewardChoiceItemQuantity5`, `RewardChoiceItemQuantity6`, `RewardFactionID1`, `RewardFactionID2`, `RewardFactionID3`, `RewardFactionID4`, `RewardFactionID5`, `RewardFactionValue1`, `RewardFactionValue2`, `RewardFactionValue3`, `RewardFactionValue4`, `RewardFactionValue5`, `RewardFactionOverride1`, `RewardFactionOverride2`, `RewardFactionOverride3`, `RewardFactionOverride4`, `RewardFactionOverride5`, `PointMapId`, `PointX`, `PointY`, `PointOption`, `LogTitle`, `LogDescription`, `QuestDescription`, `EndText`, `OfferRewardText`, `RequestItemsText`, `QuestCompletionLog`, `RequiredNpcOrGo1`, `RequiredNpcOrGo2`, `RequiredNpcOrGo3`, `RequiredNpcOrGo4`, `RequiredNpcOrGoCount1`, `RequiredNpcOrGoCount2`, `RequiredNpcOrGoCount3`, `RequiredNpcOrGoCount4`, `RequiredSourceItemId1`, `RequiredSourceItemId2`, `RequiredSourceItemId3`, `RequiredSourceItemId4`, `RequiredSourceItemCount1`, `RequiredSourceItemCount2`, `RequiredSourceItemCount3`, `RequiredSourceItemCount4`, `RequiredItemId1`, `RequiredItemId2`, `RequiredItemId3`, `RequiredItemId4`, `RequiredItemId5`, `RequiredItemId6`, `RequiredItemCount1`, `RequiredItemCount2`, `RequiredItemCount3`, `RequiredItemCount4`, `RequiredItemCount5`, `RequiredItemCount6`, `Unknown0`, `ObjectiveText1`, `ObjectiveText2`, `ObjectiveText3`, `ObjectiveText4`, `DetailsEmote1`, `DetailsEmote2`, `DetailsEmote3`, `DetailsEmote4`, `DetailsEmoteDelay1`, `DetailsEmoteDelay2`, `DetailsEmoteDelay3`, `DetailsEmoteDelay4`, `EmoteOnIncomplete`, `EmoteOnComplete`, `OfferRewardEmote1`, `OfferRewardEmote2`, `OfferRewardEmote3`, `OfferRewardEmote4`, `OfferRewardEmoteDelay1`, `OfferRewardEmoteDelay2`, `OfferRewardEmoteDelay3`, `OfferRewardEmoteDelay4`, `VerifiedBuild`) VALUES
(/*  ID    */870003,
 /*  Method  */ 2,
 /*  QuestLevel  */ 80, 
 /*  MinLevel   */80,
 /*  QuestSortID  */ -1,
 /*  QuestType*/ 0,
 /*  SuggestedGroupNum  */ 0,
 /*  LimitTime  */ 0,
 /*  RequiredRaces   */1791,
 /*  RequiredFactionId1   */ 0,
 /*  RequiredFactionId2  */ 0,
 /*  RequiredFactionValue1  */ 0,
 /*  RequiredFactionValue2   */ 0,
 /*  NextQuestIdChain  */ 0,
 /*  RewardXPId   */0,
 /*  RewardOrRequiredMoney  */ 100000,
 /*  RewardMoneyMaxLevel  */ 100000,	
 /*  RewardSpell   */ 0,
 /*  RewardSpellCast  */ 0,
 /*  RewardHonor  */ 0,
 /*  RewardHonorMultiplier  */ 0,
 /*  SourceItemId  */ 0,
 /*  Flags  */ 0,
 /*  RewardTitle  */ 0,
 /*  RequiredPlayerKills  */ 0,
 /*  RewardTalents  */ 0,
 /*  RewardArenaPoints  */ 0,
 /*  RewardItem1  */ 0,
 /*  RewardItem2  */ 0,
 /*  RewardItem3  */ 0,
 /*  RewardItem4  */ 0,
 /*  RewardAmount1*/ 0,
 /*  RewardAmount2  */ 0,
 /*  RewardAmount3  */ 0,
 /*  RewardAmount4  */ 0,
 /*  RewardChoiceItemID1  */ 0,
 /*  RewardChoiceItemID2  */ 0,
 /*  RewardChoiceItemID3  */ 0,
 /*  RewardChoiceItemID4  */ 0,
 /*  RewardChoiceItemID5  */ 0,
 /*  RewardChoiceItemID6  */ 0,
 /*  RewardChoiceItemQuantity1  */ 0,
 /*  RewardChoiceItemQuantity2  */ 0,
 /*  RewardChoiceItemQuantity3  */ 0,
 /*  RewardChoiceItemQuantity4  */ 0,
 /*  RewardChoiceItemQuantity5  */ 0,
 /*  RewardChoiceItemQuantity6  */ 0,
 /*  RewardFactionID1  */ 0,
 /*  RewardFactionID2  */ 0,
 /*  RewardFactionID3  */ 0,
 /*  RewardFactionID4  */ 0,
 /*  RewardFactionID5  */ 0,
 /*  RewardFactionValue1  */ 0,
 /*  RewardFactionValue2  */ 0,
 /*  RewardFactionValue3  */ 0,
 /*  RewardFactionValue4  */ 0,
 /*  RewardFactionValue5 */ 0,
 /*  RewardFactionOverride1  */ 0,
 /*  RewardFactionOverride2  */ 0,
 /*  RewardFactionOverride3  */ 0,
 /*  RewardFactionOverride4  */ 0,
 /*  RewardFactionOverride5  */ 0,
 /*  PointMapId  */ 0,
 /*  PointX  */ 0,
 /*  PointY  */ 0,
 /*  PointOption  */ 0,
 /*  LogTitle  */ 'Die Prinzessin',
 /*  LogDescription  */  'Geht zur Prinzessin der Sammler und hört Euch ihre Geschichte an.',
 /*  QuestDescription   */ 'Hallo $N. Willkommen im Außenposten der Sammler. Macht es Euch bequem, und wenn ihr Interesse habt geht zu Prinzessin Alanna. Sie braucht bestimmt ein offenes Ohr. Wenn ihr Zeit habt, wird sie Euch vielleicht etwas erzählen.',
 /*  EndText */  '',
 /*  OfferRewardText bevor man beendet  */  'Geht zur Prinzessin der Sammler und hört Euch ihre Geschichte an.',
 /*  RequestItemsText  */ 'Hallo $N, hast du die Aufgabe abgeschlossen?',
 /*  Quest Completed Text wird rechts im Questlog angezeigt der Text */ '',
 /*  RequiredNpcOrGo1  */ 0,
 /*  RequiredNpcOrGo2  */ 0,
 /*  RequiredNpcOrGo3  */ 0,
 /*  RequiredNpcOrGo4  */ 0,
 /*  RequiredNpcOrGoCount1  */ 0,
 /*  RequiredNpcOrGoCount2  */ 0,
 /*  RequiredNpcOrGoCount3  */ 0,
 /*  RequiredNpcOrGoCount4  */ 0,
 /*  RequiredSourceItemId1  */ 0,
 /*  RequiredSourceItemId2  */ 0,
 /*  RequiredSourceItemId3  */ 0,
 /*  RequiredSourceItemId4  */ 0,
 /*  RequiredSourceItemCount1  */ 0,
 /*  RequiredSourceItemCount2  */ 0,
 /*  RequiredSourceItemCount3  */ 0,
 /*  RequiredSourceItemCount4  */ 0,
 /*  RequiredItemId1  */ 0,
 /*  RequiredItemId2  */ 0,
 /*  RequiredItemId3  */ 0,
 /*  RequiredItemId4  */ 0,
 /*  RequiredItemId5  */ 0,
 /*  RequiredItemId6  */ 0,
 /*  RequiredItemCount1  */ 0,
 /*  RequiredItemCount2  */ 0,
 /*  RequiredItemCount3  */ 0,
 /*  RequiredItemCount4  */ 0,
 /*  RequiredItemCount5  */ 0,
 /*  RequiredItemCount6  */ 0,
 /*  Unknown0  */ 0,
 /*  ObjectiveText1  */'',
 /*  ObjectiveText2  */'',
 /*  ObjectiveText3  */'',
 /*  ObjectiveText4  */'',
 /*  DetailsEmote1  */ 0,
 /*  DetailsEmote2  */ 0,
 /*  DetailsEmote3  */ 0,
 /*  DetailsEmote4  */ 0,
 /*  DetailsEmoteDelay1  */ 0,
 /*  DetailsEmoteDelay2  */ 0,
 /*  DetailsEmoteDelay3  */ 0,
 /*  DetailsEmoteDelay4  */ 0,
 /*  EmoteOnIncomplete  */ 0,
 /*  EmoteOnComplete  */ 0,
 /*  OfferRewardEmote1  */ 0,
 /*  OfferRewardEmote2  */ 0,
 /*  OfferRewardEmote3  */ 0,
 /*  OfferRewardEmote4  */ 0,
 /*  OfferRewardEmoteDelay1  */ 0,
 /*  OfferRewardEmoteDelay2  */ 0,
 /*  OfferRewardEmoteDelay3  */ 0,
 /*  OfferRewardEmoteDelay4  */ 0,
 1);

REPLACE INTO `quest_template_addon` (`ID`, `MaxLevel`, `AllowableClasses`, `SourceSpellID`, `PrevQuestID`, `NextQuestID`, `ExclusiveGroup`, `RewardMailTemplateID`, `RewardMailDelay`, `RequiredSkillID`, `RequiredSkillPoints`, `RequiredMinRepFaction`, `RequiredMaxRepFaction`, `RequiredMinRepValue`, `RequiredMaxRepValue`, `ProvidedItemCount`, `SpecialFlags`) VALUES
( /*  ID  */870003,
  /*  MaxLevel  */80,
  /*  AllowableClasses  */2047,
  /*  SourceSpellID  */ 0,
  /*  PrevQuestID */ 870002,
  /*  NextQuestID  */870004,
  /*  ExclusiveGroup  */ 0,
  /*  RewardMailTemplateID */ 0,
  /*  RewardMailDelay  */ 0,
  /*  RequiredSkillID  */ 0,
  /*  RequiredSkillPoints  */ 0,
  /*  RequiredMinRepFaction  */ 0,
  /*  RequiredMaxRepFaction  */ 0,
  /*  RequiredMinRepValue */ 0,
  /*  RequiredMaxRepValue  */ 0,
  /*  ProvidedItemCount  */ 0,
  /*  SpecialFlags */ 0);

REPLACE INTO `creature_queststarter` (`id`, `quest`) VALUES
(800053, 870003);

REPLACE INTO `creature_questender` (`id`, `quest`) VALUES
(800056, 870003);


DELETE FROM `quest_template` WHERE  `id` = 870100;
DELETE FROM `quest_template_addon` WHERE `id` = 870100;
DELETE FROM `creature_questender` WHERE `id` = 800056   AND `quest` = 870100;
DELETE FROM `creature_queststarter` WHERE `id` = 800056   AND `quest` = 870100;

REPLACE INTO `quest_template` (`ID`, `Method`, `QuestLevel`, `MinLevel`, `QuestSortID`, `QuestType`, `SuggestedGroupNum`, `LimitTime`, `RequiredRaces`, `RequiredFactionId1`, `RequiredFactionId2`, `RequiredFactionValue1`, `RequiredFactionValue2`, `NextQuestIdChain`, `RewardXPId`, `RewardOrRequiredMoney`, `RewardMoneyMaxLevel`, `RewardSpell`, `RewardSpellCast`, `RewardHonor`, `RewardHonorMultiplier`, `SourceItemId`, `Flags`, `RewardTitle`, `RequiredPlayerKills`, `RewardTalents`, `RewardArenaPoints`, `RewardItem1`, `RewardItem2`, `RewardItem3`, `RewardItem4`, `RewardAmount1`, `RewardAmount2`, `RewardAmount3`, `RewardAmount4`, `RewardChoiceItemID1`, `RewardChoiceItemID2`, `RewardChoiceItemID3`, `RewardChoiceItemID4`, `RewardChoiceItemID5`, `RewardChoiceItemID6`, `RewardChoiceItemQuantity1`, `RewardChoiceItemQuantity2`, `RewardChoiceItemQuantity3`, `RewardChoiceItemQuantity4`, `RewardChoiceItemQuantity5`, `RewardChoiceItemQuantity6`, `RewardFactionID1`, `RewardFactionID2`, `RewardFactionID3`, `RewardFactionID4`, `RewardFactionID5`, `RewardFactionValue1`, `RewardFactionValue2`, `RewardFactionValue3`, `RewardFactionValue4`, `RewardFactionValue5`, `RewardFactionOverride1`, `RewardFactionOverride2`, `RewardFactionOverride3`, `RewardFactionOverride4`, `RewardFactionOverride5`, `PointMapId`, `PointX`, `PointY`, `PointOption`, `LogTitle`, `LogDescription`, `QuestDescription`, `EndText`, `OfferRewardText`, `RequestItemsText`, `QuestCompletionLog`, `RequiredNpcOrGo1`, `RequiredNpcOrGo2`, `RequiredNpcOrGo3`, `RequiredNpcOrGo4`, `RequiredNpcOrGoCount1`, `RequiredNpcOrGoCount2`, `RequiredNpcOrGoCount3`, `RequiredNpcOrGoCount4`, `RequiredSourceItemId1`, `RequiredSourceItemId2`, `RequiredSourceItemId3`, `RequiredSourceItemId4`, `RequiredSourceItemCount1`, `RequiredSourceItemCount2`, `RequiredSourceItemCount3`, `RequiredSourceItemCount4`, `RequiredItemId1`, `RequiredItemId2`, `RequiredItemId3`, `RequiredItemId4`, `RequiredItemId5`, `RequiredItemId6`, `RequiredItemCount1`, `RequiredItemCount2`, `RequiredItemCount3`, `RequiredItemCount4`, `RequiredItemCount5`, `RequiredItemCount6`, `Unknown0`, `ObjectiveText1`, `ObjectiveText2`, `ObjectiveText3`, `ObjectiveText4`, `DetailsEmote1`, `DetailsEmote2`, `DetailsEmote3`, `DetailsEmote4`, `DetailsEmoteDelay1`, `DetailsEmoteDelay2`, `DetailsEmoteDelay3`, `DetailsEmoteDelay4`, `EmoteOnIncomplete`, `EmoteOnComplete`, `OfferRewardEmote1`, `OfferRewardEmote2`, `OfferRewardEmote3`, `OfferRewardEmote4`, `OfferRewardEmoteDelay1`, `OfferRewardEmoteDelay2`, `OfferRewardEmoteDelay3`, `OfferRewardEmoteDelay4`, `VerifiedBuild`) VALUES
(/*  ID    */870100,
 /*  Method  */ 2,
 /*  QuestLevel  */ 80, 
 /*  MinLevel   */80,
 /*  QuestSortID  */ -1,
 /*  QuestType*/ 0,
 /*  SuggestedGroupNum  */ 0,
 /*  LimitTime  */ 0,
 /*  RequiredRaces   */1791,
 /*  RequiredFactionId1   */ 0,
 /*  RequiredFactionId2  */ 0,
 /*  RequiredFactionValue1  */ 0,
 /*  RequiredFactionValue2   */ 0,
 /*  NextQuestIdChain  */ 0,
 /*  RewardXPId   */0,
 /*  RewardOrRequiredMoney  */ 100000,
 /*  RewardMoneyMaxLevel  */ 100000,	
 /*  RewardSpell   */ 0,
 /*  RewardSpellCast  */ 0,
 /*  RewardHonor  */ 0,
 /*  RewardHonorMultiplier  */ 0,
 /*  SourceItemId  */ 0,
 /*  Flags  */ 0,
 /*  RewardTitle  */ 0,
 /*  RequiredPlayerKills  */ 0,
 /*  RewardTalents  */ 0,
 /*  RewardArenaPoints  */ 0,
 /*  RewardItem1  */ 44580,
 /*  RewardItem2  */ 0,
 /*  RewardItem3  */ 0,
 /*  RewardItem4  */ 0,
 /*  RewardAmount1*/ 10,
 /*  RewardAmount2  */ 0,
 /*  RewardAmount3  */ 0,
 /*  RewardAmount4  */ 0,
 /*  RewardChoiceItemID1  */ 0,
 /*  RewardChoiceItemID2  */ 0,
 /*  RewardChoiceItemID3  */ 0,
 /*  RewardChoiceItemID4  */ 0,
 /*  RewardChoiceItemID5  */ 0,
 /*  RewardChoiceItemID6  */ 0,
 /*  RewardChoiceItemQuantity1  */ 0,
 /*  RewardChoiceItemQuantity2  */ 0,
 /*  RewardChoiceItemQuantity3  */ 0,
 /*  RewardChoiceItemQuantity4  */ 0,
 /*  RewardChoiceItemQuantity5  */ 0,
 /*  RewardChoiceItemQuantity6  */ 0,
 /*  RewardFactionID1  */ 0,
 /*  RewardFactionID2  */ 0,
 /*  RewardFactionID3  */ 0,
 /*  RewardFactionID4  */ 0,
 /*  RewardFactionID5  */ 0,
 /*  RewardFactionValue1  */ 0,
 /*  RewardFactionValue2  */ 0,
 /*  RewardFactionValue3  */ 0,
 /*  RewardFactionValue4  */ 0,
 /*  RewardFactionValue5 */ 0,
 /*  RewardFactionOverride1  */ 0,
 /*  RewardFactionOverride2  */ 0,
 /*  RewardFactionOverride3  */ 0,
 /*  RewardFactionOverride4  */ 0,
 /*  RewardFactionOverride5  */ 0,
 /*  PointMapId  */ 0,
 /*  PointX  */ 0,
 /*  PointY  */ 0,
 /*  PointOption  */ 0,
 /*  LogTitle  */ 'Die verlorene Scherbe',
 /*  LogDescription  */  'Bringt mir meine Scherbe zurück sofort.',
 /*  QuestDescription   */ 'Hey $c. Ich hab meine Scherbe verloren und da ich gehört habe ihr müsst für uns arbeiten und vorallem für mich, die wunderschöne Prinzessin, sollt ihr mir die Scherbe zurückholen. Und wenn ihr sie auch nur ein bisschen verkratzt braucht ihr gar nicht zurück kommen. Ich werde mich dann bei Moon beschweren.',
 /*  EndText */  '',
 /*  OfferRewardText bevor man beendet  */  'Bringt mir meine Scherbe zurück sofort.',
 /*  RequestItemsText  */ '$C $N, warst du endlich fähig die Aufgabe abzuschließen?',
 /*  Quest Completed Text wird rechts im Questlog angezeigt der Text */ '',
 /*  RequiredNpcOrGo1  */ 0,
 /*  RequiredNpcOrGo2  */ 0,
 /*  RequiredNpcOrGo3  */ 0,
 /*  RequiredNpcOrGo4  */ 0,
 /*  RequiredNpcOrGoCount1  */ 0,
 /*  RequiredNpcOrGoCount2  */ 0,
 /*  RequiredNpcOrGoCount3  */ 0,
 /*  RequiredNpcOrGoCount4  */ 0,
 /*  RequiredSourceItemId1  */ 0,
 /*  RequiredSourceItemId2  */ 0,
 /*  RequiredSourceItemId3  */ 0,
 /*  RequiredSourceItemId4  */ 0,
 /*  RequiredSourceItemCount1  */ 0,
 /*  RequiredSourceItemCount2  */ 0,
 /*  RequiredSourceItemCount3  */ 0,
 /*  RequiredSourceItemCount4  */ 0,
 /*  RequiredItemId1  */ 700509,
 /*  RequiredItemId2  */ 0,
 /*  RequiredItemId3  */ 0,
 /*  RequiredItemId4  */ 0,
 /*  RequiredItemId5  */ 0,
 /*  RequiredItemId6  */ 0,
 /*  RequiredItemCount1  */ 1,
 /*  RequiredItemCount2  */ 0,
 /*  RequiredItemCount3  */ 0,
 /*  RequiredItemCount4  */ 0,
 /*  RequiredItemCount5  */ 0,
 /*  RequiredItemCount6  */ 0,
 /*  Unknown0  */ 0,
 /*  ObjectiveText1  */'',
 /*  ObjectiveText2  */'',
 /*  ObjectiveText3  */'',
 /*  ObjectiveText4  */'',
 /*  DetailsEmote1  */ 0,
 /*  DetailsEmote2  */ 0,
 /*  DetailsEmote3  */ 0,
 /*  DetailsEmote4  */ 0,
 /*  DetailsEmoteDelay1  */ 0,
 /*  DetailsEmoteDelay2  */ 0,
 /*  DetailsEmoteDelay3  */ 0,
 /*  DetailsEmoteDelay4  */ 0,
 /*  EmoteOnIncomplete  */ 0,
 /*  EmoteOnComplete  */ 0,
 /*  OfferRewardEmote1  */ 0,
 /*  OfferRewardEmote2  */ 0,
 /*  OfferRewardEmote3  */ 0,
 /*  OfferRewardEmote4  */ 0,
 /*  OfferRewardEmoteDelay1  */ 0,
 /*  OfferRewardEmoteDelay2  */ 0,
 /*  OfferRewardEmoteDelay3  */ 0,
 /*  OfferRewardEmoteDelay4  */ 0,
 1);

REPLACE INTO `quest_template_addon` (`ID`, `MaxLevel`, `AllowableClasses`, `SourceSpellID`, `PrevQuestID`, `NextQuestID`, `ExclusiveGroup`, `RewardMailTemplateID`, `RewardMailDelay`, `RequiredSkillID`, `RequiredSkillPoints`, `RequiredMinRepFaction`, `RequiredMaxRepFaction`, `RequiredMinRepValue`, `RequiredMaxRepValue`, `ProvidedItemCount`, `SpecialFlags`) VALUES
( /*  ID  */870100,
  /*  MaxLevel  */80,
  /*  AllowableClasses  */2047,
  /*  SourceSpellID  */ 0,
  /*  PrevQuestID */ 870003,
  /*  NextQuestID  */870101,
  /*  ExclusiveGroup  */ 0,
  /*  RewardMailTemplateID */ 0,
  /*  RewardMailDelay  */ 0,
  /*  RequiredSkillID  */ 0,
  /*  RequiredSkillPoints  */ 0,
  /*  RequiredMinRepFaction  */ 0,
  /*  RequiredMaxRepFaction  */ 0,
  /*  RequiredMinRepValue */ 0,
  /*  RequiredMaxRepValue  */ 0,
  /*  ProvidedItemCount  */ 0,
  /*  SpecialFlags */ 0);

REPLACE INTO `creature_queststarter` (`id`, `quest`) VALUES
(800056, 870100);

REPLACE INTO `creature_questender` (`id`, `quest`) VALUES
(800056, 870100);


DELETE FROM `quest_template` WHERE  `id` = 890002;
DELETE FROM `quest_template_addon` WHERE `id` = 890002;
DELETE FROM `creature_questender` WHERE `id` = 800052   AND `quest` = 890002;
DELETE FROM `creature_queststarter` WHERE `id` = 800052   AND `quest` = 890002;

REPLACE INTO `quest_template` (`ID`, `Method`, `QuestLevel`, `MinLevel`, `QuestSortID`, `QuestType`, `SuggestedGroupNum`, `LimitTime`, `RequiredRaces`, `RequiredFactionId1`, `RequiredFactionId2`, `RequiredFactionValue1`, `RequiredFactionValue2`, `NextQuestIdChain`, `RewardXPId`, `RewardOrRequiredMoney`, `RewardMoneyMaxLevel`, `RewardSpell`, `RewardSpellCast`, `RewardHonor`, `RewardHonorMultiplier`, `SourceItemId`, `Flags`, `RewardTitle`, `RequiredPlayerKills`, `RewardTalents`, `RewardArenaPoints`, `RewardItem1`, `RewardItem2`, `RewardItem3`, `RewardItem4`, `RewardAmount1`, `RewardAmount2`, `RewardAmount3`, `RewardAmount4`, `RewardChoiceItemID1`, `RewardChoiceItemID2`, `RewardChoiceItemID3`, `RewardChoiceItemID4`, `RewardChoiceItemID5`, `RewardChoiceItemID6`, `RewardChoiceItemQuantity1`, `RewardChoiceItemQuantity2`, `RewardChoiceItemQuantity3`, `RewardChoiceItemQuantity4`, `RewardChoiceItemQuantity5`, `RewardChoiceItemQuantity6`, `RewardFactionID1`, `RewardFactionID2`, `RewardFactionID3`, `RewardFactionID4`, `RewardFactionID5`, `RewardFactionValue1`, `RewardFactionValue2`, `RewardFactionValue3`, `RewardFactionValue4`, `RewardFactionValue5`, `RewardFactionOverride1`, `RewardFactionOverride2`, `RewardFactionOverride3`, `RewardFactionOverride4`, `RewardFactionOverride5`, `PointMapId`, `PointX`, `PointY`, `PointOption`, `LogTitle`, `LogDescription`, `QuestDescription`, `EndText`, `OfferRewardText`, `RequestItemsText`, `QuestCompletionLog`, `RequiredNpcOrGo1`, `RequiredNpcOrGo2`, `RequiredNpcOrGo3`, `RequiredNpcOrGo4`, `RequiredNpcOrGoCount1`, `RequiredNpcOrGoCount2`, `RequiredNpcOrGoCount3`, `RequiredNpcOrGoCount4`, `RequiredSourceItemId1`, `RequiredSourceItemId2`, `RequiredSourceItemId3`, `RequiredSourceItemId4`, `RequiredSourceItemCount1`, `RequiredSourceItemCount2`, `RequiredSourceItemCount3`, `RequiredSourceItemCount4`, `RequiredItemId1`, `RequiredItemId2`, `RequiredItemId3`, `RequiredItemId4`, `RequiredItemId5`, `RequiredItemId6`, `RequiredItemCount1`, `RequiredItemCount2`, `RequiredItemCount3`, `RequiredItemCount4`, `RequiredItemCount5`, `RequiredItemCount6`, `Unknown0`, `ObjectiveText1`, `ObjectiveText2`, `ObjectiveText3`, `ObjectiveText4`, `DetailsEmote1`, `DetailsEmote2`, `DetailsEmote3`, `DetailsEmote4`, `DetailsEmoteDelay1`, `DetailsEmoteDelay2`, `DetailsEmoteDelay3`, `DetailsEmoteDelay4`, `EmoteOnIncomplete`, `EmoteOnComplete`, `OfferRewardEmote1`, `OfferRewardEmote2`, `OfferRewardEmote3`, `OfferRewardEmote4`, `OfferRewardEmoteDelay1`, `OfferRewardEmoteDelay2`, `OfferRewardEmoteDelay3`, `OfferRewardEmoteDelay4`, `VerifiedBuild`) VALUES
(/*  ID    */890002,
 /*  Method  */ 2,
 /*  QuestLevel  */ 80, 
 /*  MinLevel   */80,
 /*  QuestSortID  */ -1,
 /*  QuestType*/ 83,
 /*  SuggestedGroupNum  */ 0,
 /*  LimitTime  */ 0,
 /*  RequiredRaces   */1791,
 /*  RequiredFactionId1   */ 0,
 /*  RequiredFactionId2  */ 0,
 /*  RequiredFactionValue1  */ 0,
 /*  RequiredFactionValue2   */ 0,
 /*  NextQuestIdChain  */ 0,
 /*  RewardXPId   */0,
 /*  RewardOrRequiredMoney  */ 50000000,
 /*  RewardMoneyMaxLevel  */ 50000000,	
 /*  RewardSpell   */ 0,
 /*  RewardSpellCast  */ 0,
 /*  RewardHonor  */ 0,
 /*  RewardHonorMultiplier  */ 0,
 /*  SourceItemId  */ 0,
 /*  Flags  */ 0,
 /*  RewardTitle  */ 0,
 /*  RequiredPlayerKills  */ 0,
 /*  RewardTalents  */ 0,
 /*  RewardArenaPoints  */ 0,
 /*  RewardItem1  */ 50250,
 /*  RewardItem2  */ 0,
 /*  RewardItem3  */ 0,
 /*  RewardItem4  */ 0,
 /*  RewardAmount1*/ 1,
 /*  RewardAmount2  */ 0,
 /*  RewardAmount3  */ 0,
 /*  RewardAmount4  */ 0,
 /*  RewardChoiceItemID1  */ 0,
 /*  RewardChoiceItemID2  */ 0,
 /*  RewardChoiceItemID3  */ 0,
 /*  RewardChoiceItemID4  */ 0,
 /*  RewardChoiceItemID5  */ 0,
 /*  RewardChoiceItemID6  */ 0,
 /*  RewardChoiceItemQuantity1  */ 0,
 /*  RewardChoiceItemQuantity2  */ 0,
 /*  RewardChoiceItemQuantity3  */ 0,
 /*  RewardChoiceItemQuantity4  */ 0,
 /*  RewardChoiceItemQuantity5  */ 0,
 /*  RewardChoiceItemQuantity6  */ 0,
 /*  RewardFactionID1  */ 0,
 /*  RewardFactionID2  */ 0,
 /*  RewardFactionID3  */ 0,
 /*  RewardFactionID4  */ 0,
 /*  RewardFactionID5  */ 0,
 /*  RewardFactionValue1  */ 0,
 /*  RewardFactionValue2  */ 0,
 /*  RewardFactionValue3  */ 0,
 /*  RewardFactionValue4  */ 0,
 /*  RewardFactionValue5 */ 0,
 /*  RewardFactionOverride1  */ 0,
 /*  RewardFactionOverride2  */ 0,
 /*  RewardFactionOverride3  */ 0,
 /*  RewardFactionOverride4  */ 0,
 /*  RewardFactionOverride5  */ 0,
 /*  PointMapId  */ 0,
 /*  PointX  */ 0,
 /*  PointY  */ 0,
 /*  PointOption  */ 0,
 /*  LogTitle  */ 'MMOWNING WORLD',
 /*  LogDescription  */  'Sammelt 600 Königstinte, 600 Löwentinte, 450 Meerestinte',
 /*  QuestDescription   */ 'Hallo $N. Heute müsst ihr mir Tinten sammeln. Ich brauche einiges an Tinten da ich die Bibel neu schreiben möchte. Und das per Hand. Da braucht man eben unter Wasser einiges an Tinten.',
 /*  EndText */  '',
 /*  OfferRewardText bevor man beendet  */  'Geht zu Orca und begrüßt ihn hier auf MMOwning World.',
 /*  RequestItemsText  */ 'Hallo $N, hast du die Aufgabe abgeschlossen?',
 /*  Quest Completed Text wird rechts im Questlog angezeigt der Text */ '',
 /*  RequiredNpcOrGo1  */ 0,
 /*  RequiredNpcOrGo2  */ 0,
 /*  RequiredNpcOrGo3  */ 0,
 /*  RequiredNpcOrGo4  */ 0,
 /*  RequiredNpcOrGoCount1  */ 0,
 /*  RequiredNpcOrGoCount2  */ 0,
 /*  RequiredNpcOrGoCount3  */ 0,
 /*  RequiredNpcOrGoCount4  */ 0,
 /*  RequiredSourceItemId1  */ 0,
 /*  RequiredSourceItemId2  */ 0,
 /*  RequiredSourceItemId3  */ 0,
 /*  RequiredSourceItemId4  */ 0,
 /*  RequiredSourceItemCount1  */ 0,
 /*  RequiredSourceItemCount2  */ 0,
 /*  RequiredSourceItemCount3  */ 0,
 /*  RequiredSourceItemCount4  */ 0,
 /*  RequiredItemId1  */ 43116,
 /*  RequiredItemId2  */ 43119,
 /*  RequiredItemId3  */ 43126,
 /*  RequiredItemId4  */ 0,
 /*  RequiredItemId5  */ 0,
 /*  RequiredItemId6  */ 0,
 /*  RequiredItemCount1  */ 600,
 /*  RequiredItemCount2  */ 600,
 /*  RequiredItemCount3  */ 450,
 /*  RequiredItemCount4  */ 0,
 /*  RequiredItemCount5  */ 0,
 /*  RequiredItemCount6  */ 0,
 /*  Unknown0  */ 0,
 /*  ObjectiveText1  */'',
 /*  ObjectiveText2  */'',
 /*  ObjectiveText3  */'',
 /*  ObjectiveText4  */'',
 /*  DetailsEmote1  */ 0,
 /*  DetailsEmote2  */ 0,
 /*  DetailsEmote3  */ 0,
 /*  DetailsEmote4  */ 0,
 /*  DetailsEmoteDelay1  */ 0,
 /*  DetailsEmoteDelay2  */ 0,
 /*  DetailsEmoteDelay3  */ 0,
 /*  DetailsEmoteDelay4  */ 0,
 /*  EmoteOnIncomplete  */ 0,
 /*  EmoteOnComplete  */ 0,
 /*  OfferRewardEmote1  */ 0,
 /*  OfferRewardEmote2  */ 0,
 /*  OfferRewardEmote3  */ 0,
 /*  OfferRewardEmote4  */ 0,
 /*  OfferRewardEmoteDelay1  */ 0,
 /*  OfferRewardEmoteDelay2  */ 0,
 /*  OfferRewardEmoteDelay3  */ 0,
 /*  OfferRewardEmoteDelay4  */ 0,
 1);

REPLACE INTO `quest_template_addon` (`ID`, `MaxLevel`, `AllowableClasses`, `SourceSpellID`, `PrevQuestID`, `NextQuestID`, `ExclusiveGroup`, `RewardMailTemplateID`, `RewardMailDelay`, `RequiredSkillID`, `RequiredSkillPoints`, `RequiredMinRepFaction`, `RequiredMaxRepFaction`, `RequiredMinRepValue`, `RequiredMaxRepValue`, `ProvidedItemCount`, `SpecialFlags`) VALUES
( /*  ID  */890002,
  /*  MaxLevel  */80,
  /*  AllowableClasses  */2047,
  /*  SourceSpellID  */ 0,
  /*  PrevQuestID */ 890000,
  /*  NextQuestID  */890002,
  /*  ExclusiveGroup  */ 0,
  /*  RewardMailTemplateID */ 0,
  /*  RewardMailDelay  */ 0,
  /*  RequiredSkillID  */ 0,
  /*  RequiredSkillPoints  */ 0,
  /*  RequiredMinRepFaction  */ 0,
  /*  RequiredMaxRepFaction  */ 0,
  /*  RequiredMinRepValue */ 0,
  /*  RequiredMaxRepValue  */ 0,
  /*  ProvidedItemCount  */ 0,
  /*  SpecialFlags */ 0);

REPLACE INTO `creature_queststarter` (`id`, `quest`) VALUES
(800052, 890002);

REPLACE INTO `creature_questender` (`id`, `quest`) VALUES
(800052, 890002);


