UPDATE `command` SET `permission`='194' WHERE `name`='additem';
UPDATE `command` SET `permission`='194' WHERE `name`='additemset';
UPDATE `command` SET `permission`='194' WHERE `name`='character rename';
UPDATE `command` SET `permission`='194' WHERE `name`='character customize';
UPDATE `command` SET `permission`='194' WHERE `name`='character reputation';
UPDATE `command` SET `permission`='194' WHERE `name`='levelup';
UPDATE `command` SET `permission`='194' WHERE `name`='lookup area';
UPDATE `command` SET `permission`='194' WHERE `name`='lookup creature';
UPDATE `command` SET `permission`='194' WHERE `name`='lookup event';
UPDATE `command` SET `permission`='194' WHERE `name`='lookup faction';
UPDATE `command` SET `permission`='194' WHERE `name`='lookup item';
UPDATE `command` SET `permission`='194' WHERE `name`='lookup itemset';
UPDATE `command` SET `permission`='194' WHERE `name`='lookup map';
UPDATE `command` SET `permission`='194' WHERE `name`='lookup object';
UPDATE `command` SET `permission`='194' WHERE `name`='lookup quest';
UPDATE `command` SET `permission`='194' WHERE `name`='lookup skill';
UPDATE `command` SET `permission`='194' WHERE `name`='lookup spell';
UPDATE `command` SET `permission`='194' WHERE `name`='lookup tele';
UPDATE `command` SET `permission`='194' WHERE `name`='lookup';
UPDATE `command` SET `permission`='194' WHERE `name`='modify bit';
UPDATE `command` SET `permission`='194' WHERE `name`='modify speed swim';
UPDATE `command` SET `permission`='194' WHERE `name`='modify drunk';
UPDATE `command` SET `permission`='194' WHERE `name`='modify energy';
UPDATE `command` SET `permission`='194' WHERE `name`='modify faction';
UPDATE `command` SET `permission`='194' WHERE `name`='modify speed fly';
UPDATE `command` SET `permission`='194' WHERE `name`='modify gender';
UPDATE `command` SET `permission`='194' WHERE `name`='modify honor';
UPDATE `command` SET `permission`='194' WHERE `name`='modify hp';
UPDATE `command` SET `permission`='194' WHERE `name`='modify mana';
UPDATE `command` SET `permission`='194' WHERE `name`='modify money';
UPDATE `command` SET `permission`='194' WHERE `name`='modify mount';
UPDATE `command` SET `permission`='194' WHERE `name`='modify phase';
UPDATE `command` SET `permission`='194' WHERE `name`='modify rage';
UPDATE `command` SET `permission`='194' WHERE `name`='modify reputation';
UPDATE `command` SET `permission`='194' WHERE `name`='modify runicpower';
UPDATE `command` SET `permission`='194' WHERE `name`='modify speed';
UPDATE `command` SET `permission`='568' WHERE `name`='modify spell';
UPDATE `command` SET `permission`='194' WHERE `name`='modify';
UPDATE `command` SET `permission`='194' WHERE `name`='revive';
UPDATE `command` SET `permission`='194' WHERE `name`='tele add';
UPDATE `command` SET `permission`='194' WHERE `name`='tele del';
UPDATE `command` SET `permission`='194' WHERE `name`='tele group';
UPDATE `command` SET `permission`='194' WHERE `name`='tele name';
UPDATE `command` SET `permission`='194' WHERE `name`='tele';
UPDATE `command` SET `permission`='194' WHERE `name`='ticket assign';
UPDATE `command` SET `permission`='194' WHERE `name`='ticket close';
UPDATE `command` SET `permission`='194' WHERE `name`='ticket closedlist';
UPDATE `command` SET `permission`='194' WHERE `name`='ticket comment';
UPDATE `command` SET `permission`='194' WHERE `name`='ticket list';
UPDATE `command` SET `permission`='194' WHERE `name`='ticket onlinelist';
UPDATE `command` SET `permission`='194' WHERE `name`='ticket unassign';
UPDATE `command` SET `permission`='194' WHERE `name`='ticket viewid';
UPDATE `command` SET `permission`='194' WHERE `name`='ticket viewname';
UPDATE `command` SET `permission`='194' WHERE `name`='ticket';
UPDATE `command` SET `permission`='194' WHERE `name`='unmute';
UPDATE `command` SET `permission`='194' WHERE `name`='mute';
UPDATE `command` SET `permission`='194' WHERE `name`='nameannounce';
UPDATE `command` SET `permission`='194' WHERE `name`='ban';
UPDATE `command` SET `permission`='194' WHERE `name`='ban account';
UPDATE `command` SET `permission`='194' WHERE `name`='ban character';
UPDATE `command` SET `permission`='194' WHERE `name`='ban playeraccount';
UPDATE `command` SET `permission`='194' WHERE `name`='baninfo';
UPDATE `command` SET `permission`='194' WHERE `name`='baninfo account';
UPDATE `command` SET `permission`='194' WHERE `name`='baninfo character';
UPDATE `command` SET `permission`='194' WHERE `name`='banlist';
UPDATE `command` SET `permission`='194' WHERE `name`='banlist account';
UPDATE `command` SET `permission`='194' WHERE `name`='banlist character';
UPDATE `command` SET `permission`='194' WHERE `name`='unban';
UPDATE `command` SET `permission`='194' WHERE `name`='unban account';
UPDATE `command` SET `permission`='194' WHERE `name`='unban character';
UPDATE `command` SET `permission`='193' WHERE `name`='event';
UPDATE `command` SET `permission`='194' WHERE `name`='event activelist';
UPDATE `command` SET `permission`='193' WHERE `name`='event start';
UPDATE `command` SET `permission`='193' WHERE `name`='event stop';
UPDATE `command` SET `permission`='193' WHERE `name`='gobject';
UPDATE `command` SET `permission`='193' WHERE `name`='gobject activate';
UPDATE `command` SET `permission`='193' WHERE `name`='gobject add';
UPDATE `command` SET `permission`='193' WHERE `name`='gobject add temp';
UPDATE `command` SET `permission`='193' WHERE `name`='gobject delete';
UPDATE `command` SET `permission`='193' WHERE `name`='gobject info';
UPDATE `command` SET `permission`='193' WHERE `name`='gobject move';
UPDATE `command` SET `permission`='193' WHERE `name`='gobject near';
UPDATE `command` SET `permission`='193' WHERE `name`='gobject set phase';
UPDATE `command` SET `permission`='193' WHERE `name`='gobject target';
UPDATE `command` SET `permission`='193' WHERE `name`='gobject turn';
UPDATE `command` SET `permission`='193' WHERE `name`='announce';
UPDATE `command` SET `permission`='193' WHERE `name`='npc';
UPDATE `command` SET `permission`='193' WHERE `name`='npc add';
UPDATE `command` SET `permission`='193' WHERE `name`='npc add formation';
UPDATE `command` SET `permission`='193' WHERE `name`='npc add item';
UPDATE `command` SET `permission`='193' WHERE `name`='npc add move';
UPDATE `command` SET `permission`='193' WHERE `name`='npc add temp';
UPDATE `command` SET `permission`='193' WHERE `name`='npc delete';
UPDATE `command` SET `permission`='193' WHERE `name`='npc delete item';
UPDATE `command` SET `permission`='193' WHERE `name`='npc follow';
UPDATE `command` SET `permission`='193' WHERE `name`='npc follow stop';
UPDATE `command` SET `permission`='193' WHERE `name`='npc set allowmove';
UPDATE `command` SET `permission`='193' WHERE `name`='npc set entry';
UPDATE `command` SET `permission`='193' WHERE `name`='npc set factionid';
UPDATE `command` SET `permission`='193' WHERE `name`='npc set flag';
UPDATE `command` SET `permission`='193' WHERE `name`='npc set level';
UPDATE `command` SET `permission`='193' WHERE `name`='npc set link';
UPDATE `command` SET `permission`='193' WHERE `name`='npc set model';
UPDATE `command` SET `permission`='193' WHERE `name`='npc set movetype';
UPDATE `command` SET `permission`='193' WHERE `name`='npc set phase';
UPDATE `command` SET `permission`='193' WHERE `name`='npc set spawndist';
UPDATE `command` SET `permission`='193' WHERE `name`='npc set spawntime';
UPDATE `command` SET `permission`='193' WHERE `name`='npc set data';
UPDATE `command` SET `permission`='193' WHERE `name`='npc info';
UPDATE `command` SET `permission`='193' WHERE `name`='npc move';
UPDATE `command` SET `permission`='193' WHERE `name`='npc playemote';
UPDATE `command` SET `permission`='193' WHERE `name`='npc say';
UPDATE `command` SET `permission`='193' WHERE `name`='npc textemote';
UPDATE `command` SET `permission`='193' WHERE `name`='npc whisper';
UPDATE `command` SET `permission`='193' WHERE `name`='npc yell';





