DELETE FROM  `locales_quest` where `id` IN (750000,803903, 803902,803901,803900,800537,800552,800553,800554,800555,800558,800559,800560,800561,802008,802016,802017,802027,890001,899000,900001,900300,900301,900500,900502,900503,900504,900807,900808
,900811,800554,900505,900506,900509,900809,900821,900836, 799996,799997,799998,799999,800000,800001,800002,800003,800004,800005,800006,800007,800008,800009,800010,800011,800012,800013,800014,800015,800016,800017,800018,800019,800020,800500,800501,800502,800503,800504,800505,
800506,800507,800508,800509,800510,800511,800512,800513,800514,800515,800516,800517,800518,800519,800520,800521,800522,800523,800524,800525,800526,800527,800528,800529,800530,800531,800532,800533,800534,800535,800536,800538,800539,800540,800541,800542,800543,
800544,800545,800546,800547,800548,800549,800550,800551,800552,800556,800557,802000,802001,802002,802003,802004,802005,802006,802007,802009,802010,802011,802012,802013,802014,802015,802017,802018,802019,802020,802021,802022,802023,802024,802025
,802026,802028,802029,802030,802031,802032,802033,802034,802035,802036,802037,802038,802039,802040,802041,802042,802300,802301,802302,802303,802304,802305,802306,802307,802308,802309,802310,802800,802801,802809,802810,802818,802819,802827,802828,802836,802837,802838,802839,802840,802841,802842
,802843,802844,804845,803000,803001,803002,803003,803004,803005,805000,805001,805002,805003,805004,805005,805006,805007,805008,805009,805010,805011,805012,805013,805014,805015,805016,805017,805018,805019,805020,805021,805022,805023,805024,870000,870001,870002,870003,870100,890000,890002,90000,900100,900101,900300,900500,900501,
900501,900503,900504,900508,900510,900800,900801,900802,900803,900804,900805,900806,900810,900820,900822,900823,900824,900825,900826,900827,900828,900829,900830,900831,900832,900833,900834,900835,900837,900838,900839,900840,802845,900000);

INSERT INTO `locales_quest` (`Id`, `Title_loc3`, `Details_loc3`, `Objectives_loc3`, `CompletedText_loc3`) VALUES
('799996', 'Die Faelschung', 'Findet die kleine Frau, die diese Faelschung in Umlauf gebracht hat.', '$C, scheinbar wurde eine Faelschung dieses wertvollen Gegenstands produziert.$B$BFindet dieses kleine Ungeziefer, dass diesen Gegenstand hergestellt hat.', 'Findet die kleine Frau in Dalaran.'),
('799997', 'Der Stein der kleinen Frau', 'Findet meinen Stein den ich verloren habe und bringt ihn mir zurueck.', 'Hallo $N, ich habe meinen Stein in der Seelenschmiede verloren als ich vor dem grausigen Verschlinger der Seelen davon rannte. Ich glaube er hat ihn an sich genommen. Koennt ihr ihn mir bitte zurueckholen? Vielleicht habe ich dann eine kleine Belohnung fuer Euch.', 'Es ist Eure Sache was ihr tut.'),
('799998', 'Der mysterioese Gegenstand', 'Findet den Mann der den mysterioesen Gegenstand besitzt.', 'Hey, ihr da.$BHabt ihr nichts zu tun?Ich haette da etwas fuer Euch. In letzter Zeit geht das Geruecht um, das ein Mann einen mysterioesen und seltenen Gegestand gefunden hat. Habt ihr das nicht mitbekommen? Anscheinend soll er sich in der Scherbenwelt befinden, aber auch das ist sehr wage. Ich glaube mich noch zu erinnern, dass der Bereich indem er sich befinden koennte, im Bereich des Nethersturm ist. Wenn Ihr ihn findet koenntet Ihr Euch von diesem Gegenstand ueberzeugen. Verzweifelt nicht zu schnell wenn ihr ihn nicht gleich am Anfang findet. Ich gebe Euch noch eine Replik des Gegenstandes mit. Diese hat leider keine besondere Macht. ', 'Es ist Eure Sache was ihr tut.'),
('799999', 'Der Gegenstand', 'Liefert diesen Gegenstand an einen Haendler in Dalaran.', '$N, Liefert diesen Gegenstand an einen Haendler in Dalaran. Geruechten zufolge steht dieser eine bestimmte Haendler im Untergrund von Dalaran. Schaut Euch dort doch einfach um und bringt im diesen Stein.', 'Bringt diesen Stein zu einem Haendler in Dalaran.'),
('800000', 'Der Anfang', 'Liefert 20 Goldbarren an mich um euren Ehrgeiz und Euer Interesse zu beweisen.', 'Guten Tag $N. Ich habe von einem Volk gehoert das in einem entlegenen Gebiet von Azeroth wohnt. Um mit diesem Volk in Kontakt treten zu koennen, bedarf es jedoch \r\neines kleinen Oboluses. Bringt mir 20 Goldbarren und ich werde Euch den Standort verraten.', 'Bringt die Goldbarren zurueck zu Thedrium Wyrmbraeu um den Standort zu erfahren.'),
('800001', 'Der Begin einer neuen Reise', 'Bringt den Astralen Kredit zu Extator Magista', 'Bringt den Astralen Kredit zu Extator Magista und zeigt ihm sofort Eure Bereitschaft sich Ihm anzuschliessen. Herr Magista befindet sich im Gebirge zwischen den Grizzlyhuegeln sowie dem Heulenden Fjord.', 'Bringt den Astralen Kredit zu Extator Magista.'),
('800002', 'Die erste Pruefung', 'Bringt mir 20 Abgeworfene Echsenhaeute, 20 Gorillafangzaehne,30 Seidenstoffe.', 'Dies ist Eure erste Pruefung. Es wird eine leichte Aufgabe sein. Bringt mir 20 Abgeworfene Echsenhaeute, 20 Gorillafangzaehne,30 Seidenstoffe. Wir muessen ein Zeichen setzen, dass trotz unserer aktuellen Lage mit uns zu rechnen ist.', 'Kehrt zu Extator Magista zurueck um Eure Belohnung zu erhalten.'),
('800003', 'Die zweite Pruefung', 'Toetet 10 gegnerische Spieler', 'Bei der zweiten Pruefung wird Eure Kampffaehigkeit gegen ebenbuertige Gegner auf die Probe gestellt. Tretet gegen 10 Spieler an um die Pruefung abzuschliessen.', 'Kehrt zurueck um die Pruefung abzuschliessen.'),
('800004', 'Die dritte Pruefung', 'Bringt mir 10 boreanische Leder und 10 Wollverbaende um mich zu unterstuetzen.', 'Mein Volk muss leiden, bringt mir daher die benoetigten Materialien, damit ich diese zu meinem Volk bringen kann.', 'Kehrt zurueck um Eure Belohnung abzuholen.'),
('800005', 'Die Aufnahme', 'Bringt die Schriftensammlung zu Destro MMOwning. Toetet zusaetzlich Geisselfuerst Tyrannus und den den Verschlinger der Seelen.', 'Bringt die Schriftensammlung zu Destro MMOwning. Ihr findet Ihn an der Kueste von Westfall. Aus seiner Sicht gesehen schaut er auf ein Schriffswrack. Meist hoert er im Wind die Schreie von Murlockreaturen. Zusaetzlich muesst ihr Geisselfuerst Tyrannus und den Verschlinger der Seelen zu toeten.', 'Destro Mowning ist erfreut Euch zu sehen. Toetet zusaetzlich Geisselfuerst Tyrannus, Den Verschlinger der Seelen sowie Sartharion.'),
('800006', 'Die Gesteinstinktur', 'Bringt 3 Sulfuronbloecke sowie 3000 Ehrenpunkte zu Sophie Mondhain', 'Wie ihr seht ist mein Mann mit der Worgenkrankheit befallen. Ich habe von einer Tinktur gehoert, fuer welche man in die Tiefen des geschmolzenen Kerns reissen muss.\r\nBringt mir von dort 3 Sulfuronbloecke und zusaetzlich 3000 Ehrenpunkte. Beachtet wohl, Sulfuronbloecke sind ein aeussert seltenes Gut. Dem Vernehmen nach sind die Sulfuronbloecke im Geschmolzenen Kern zu finden.', 'Sophie Mondhain erwartet Euch sehnsuechtig.'),
('800007', 'Die Essenz der ewigen Fuenf', 'Bringt die Essenzen der ewigen Fuenf zu Sophie Mondhain.', '$N,$BDie Tinktur der Sulforonbloecke war leider ein Fehlschlag. Ein  Vertrauter erzaehlte mir aber von Essenzen der ewigen Fuenf. Diese sollen ueber magische Heilkraefte verfuegen. Bitte helft mir und bringt mir diese 5 Essenzen. Die Essenzen der ewigen Fuenf sollen sich im Besitz der 5 grossen Weltendrachen befinden. Ein Name, an den ich mich errinern kann, war glaube ich Smariss.', 'Sophie Mondhain erwartet Euch sehnsuechtig.'),
('800009', 'PreQuest: Der Fall des verlorenen Herrschers', 'Hoert Euch die einleitende Erzaehlung von Exitare an.', '$N,$Bich habe eine wichtige Nachricht fuer Euch. Eine neue Bedrohung ist im Begriff unsere Welt zu bedrohen.', 'Ich warte auf Euch.'),
('800010', 'PreQuest: Der Fall des verlorenen Herrschers', 'Sammelt 200 Grobe Steine, 5 Hammelkoteletts, 2 Schlaeuche mit zwergischen Starkbier und toetet 10 Kuehe.', '$N,$Bdie ersten Schritte um das neue uebel aufzuhalten sind denkbar einfach. Bringt mir 5 Hammelkoteletts und 2 Schlaeuche mit zwergischen Starkbier. Ich habe naemlich Durst und Hunger. Waehrend ich mich verkoestige koennt Ihr mir gleich noch 200 grobe Steine bringen. Diese benoetigen wir fuer unser erstes Pulver, welches hoffentlich den gewuenschten Effekt ausloest.', 'Ich warte auf Euch.'),
('800011', 'PreQuest: Der Fall des verlorenen Herrschers', 'Meldet Euch bei Bryana Atkenur und bringt ihr die Tinktur.', '$N,$Bunsere Tinktur scheint gut zu sein. Wir muessen sie nun nur noch testen. Bringt die Tinktur zu Bryana Atkenur. Sie wird die Guete ueberpruefen. Seid aber bitte zuegig, den durch den Transport wird die Tinktur instabil.', 'Ich warte auf Euch.'),
('800012', 'Die Drachenmutter', 'Toetet Sindragosa', 'Hallo $N,toetet Sindragosa. Sindragosa ist die Mutter aller Drachen, die ihr schon bezwungen habt. Sie muss sterben damit ich die benoetigte Tinktur erstellen kann bzw sie wirksam werden kann.', 'Es ist Eure Sache was ihr tut.'),
('800013', 'Die Tinktur der 4 Elemente', 'Toetet die Verkoerperung der 4 Elemente.', 'Hallo $N,die 4 Elemente besitzen Maechte die wir fuer das erfolgreiche Einsetzen der Tinktur brauchen. Toetet sie daher alle und nehmt deren Kraft in Euch auf. Viel Erfolg fleissige Wanderer.', 'Es ist Eure Sache was ihr tut.'),
('800014', 'Ueberbringt die Tinkur meinem Mann', 'Bringt die Tinktur zu Destro Raisin.', 'Hallo $N, die Tinktur ist fertig und muss nun nur noch meinem Mann ueberbracht werden. Aber beeilt Euch.', 'Es ist Eure Sache was ihr tut.'),
('800500', 'Mehr Hilfe fuer das Volk', 'Liefert 100 Netherstoff und 75 Raptorkrallen an mich.', 'Wir haben einen taeglichen Bedarf an verschiedenen Guetern. Liefert 100 Netherstoff und 50 Raptorkrallen an mich.', 'Bringt Ihr mir die benoetigten Dinge?'),
('800501', 'Toetet den Verschlinger der Seelen ', 'Toetet den Verschlinger der Seelen', 'Dies Bedarf keiner langen Erklaerung! Toetet den Verschlinger der Seelen', 'Bringt Ihr mir die benoetigten Dinge?'),
('800502', 'Die neue Postlieferung', '$N bitte liefert diesen Stapel Briefe an Johann Orrig vor Orgrimmar.', 'Diese Briefe muessen unbedingt Johann Orrig zugestellt werden. Sie enthalten wichtige Nachrichten unserer Mitglieder des Stammes. Ihr findet ihn vor Orgrimmar. ', 'Bringt Ihr ihm die benoetigten Briefe?'),
('800503', 'Die neue Postlieferung', '$N bitte liefert diesen Stapel Briefe an Pi von Haar in Sturmwind.', 'Diese Briefe muessen unbedingt Pi von Haar in Sturmwind zugestellt werden. Sie enthalten wichtige Nachrichten unserer Mitglieder des Stammes. Ihr findet Pi von Haar auf dem Kathedralenplatz.', 'Bringt Ihr ihm die benoetigten Briefe?'),
('800504', 'Naxxramas Rally', '$N bitte toetet Saphiron und Kel´Thuzad.', '$N,$B bittet entledigt Euch dieser 2 Bestien. Sie zerstoeren unsere Doerfer und toeten unsere Kinder.', 'Fuehrt ihr meinen Auftrag aus?'),
('800505', 'Gepflegt zerlegt', 'Erledigt 20 Spieler im PVP', 'Noch niemand hat eine Kneipenschlaegerei geschadet. Also stuerzt euch mitten hinein.', 'Fuehrt ihr meinen Auftrag aus?'),
('800506', 'Zwergenfilet', '$N, toetet Magni Bronzebart', '$N, $B habt ihr Lust auf Zwergenfilet? Toetet Magni Bronzebart, den Koenig der verachtenswerten Zwerge.', 'Fuehrt ihr meinen Auftrag aus?'),
('800507', 'Hordenmassaker', '$N, toetet Thrall von Orgrimmar', '$N, $B habt ihr Lust auf ein Hordenmassaker? Toetet Thrall von Orgrimmar , den Hauptling der blutruenstigen Horde.', 'Fuehrt ihr meinen Auftrag aus?'),
('800508', 'Tot den Menschen', '$N, toetet Varian Wrynn', '$N, $B habt ihr Lust den Menschen Leid zuzufuegen? Toetet Varian Wrynn, den Koenig der hochnaessigen Menschen.', 'Fuehrt ihr meinen Auftrag aus?'),
('800509', 'Froststoff sammeln ', 'Sammelt 100 Froststoff', 'Wir benoetigen Froststoff zum Weben unserer Kleidung. Bitte helf uns dabei.', 'Bringt Ihr mir die benoetigten Dinge?'),
('800510', 'Orrig der dunkle Schatten ', 'Toetet Orrig den dunklen Schatten.', 'Wir koennen Orrig nicht weiter am Leben lassen. Er ist eine Gefahr fuer unser ganzes Volk. Vernichtet ihn. Geht zu Seruc von Lantus um zu Orrig zu gelangen.', 'Werdet ihr den Auftrag aufsfuehren?'),
('800511', 'Federn fuer mein Kleid', 'Bringt mir 30 raue Geiernfedern.', 'Bitte helft mir, ich benoetige neue Federn fuer mein Gefieder.', 'Werdet ihr den Auftrag aufsfuehren?'),
('800512', 'Sammelwut', 'Sammelt 100 Staehlerne Pfeilspitzen, 75 Netherstoff und taetet 10 Sonnenschuppenkreischer, 15 Fleischreisserhyjaenen, 20 Kluftmoosgiftspucker, 15 Blutsichelfelzhetzer.', 'Helft uns bitte beim Sammeln dieser wichtigen Gegenstaende. Wir benoetigen diese wirklich dringend.', 'Werdet ihr den Auftrag aufsfuehren?'),
('800513', 'Kupferpulver', 'Bringt mir 30 Kupferpulver', 'Ich beoetige Kupferpulver fuer meinen strahlenden Glanz des Gefieders', 'Werdet ihr den Auftrag aufsfuehren?'),
('800514', 'Weekly: Eiskronenzitadelle', 'Toetet den Lichkoenig in der Eiskronenzitadelle. Ihr werdet reich belohnt werden !', '', 'Werdet ihr den Auftrag aufsfuehren?'),
('800515', 'Weekly: Ulduar', 'Toetet Freya in Ulduar. Ihr werdet reich belohnt werden !', '', 'Werdet ihr den Auftrag aufsfuehren?'),
('800516', 'Weekly: Naxxramas', 'Toetet KelThuzad in Naxxramas. Ihr werdet reich belohnt werden !', '', 'Werdet ihr den Auftrag aufsfuehren?'),
('800517', 'Weekly: Archavons Kammer', 'Toetet Toravon der Eiswaechter in Archavons Kammer. Ihr werdet reich belohnt werden !', '', 'Werdet ihr den Auftrag aufsfuehren?'),
('800518', 'Weekly: Pruefung des Kreuzfahrers', 'Toetet Anubarak in der Pruefung des Kreuzfahrers. Ihr werdet reich belohnt werden !', '', 'Werdet ihr den Auftrag aufsfuehren?'),
('800519', 'Weekly: Das Obsidiansanktum', 'Toetet Sartharion im Obsidiansanktum. Ihr werdet reich belohnt werden !', '', 'Werdet ihr den Auftrag aufsfuehren?'),
('800520', 'Weekly: Das Auge der Ewigkeit', 'Toetet Malygos im Auge der Ewigkeit. Ihr werdet reich belohnt werden !', '', 'Werdet ihr den Auftrag aufsfuehren?'),
('800521', 'Weekly: ZulGurub', 'Toetet Hakkar in ZulGurub. Ihr werdet reich belohnt werden !', '', 'Werdet ihr den Auftrag aufsfuehren?'),
('800522', 'Weekly: Ruinen von AhnQiraj', 'Toetet Ossirian in den Ruinen von AhnQiraj. Ihr werdet reich belohnt werden !', '', 'Werdet ihr den Auftrag aufsfuehren?'),
('800523', 'Weekly: Gruuls Unterschlupf', 'Toetet Gruuls in Gruuls Unterschlupf. Ihr werdet reich belohnt werden !', '', 'Werdet ihr den Auftrag aufsfuehren?'),
('800524', 'Angeln: Kiefers Engelfisch', 'Angelt Kiefers Engelfisch.', 'Hallo $N, bitte angelt mir Kiefers Engelfisch. Ihr bekommt eine Belohnung dafuer.', 'Es ist Eure Sache was ihr tut.'),
('800525', 'Weekly: Das Rubinsanktum', 'Toetet Halion im Rubinsanktum. Ihr werdet reich belohnt werden !', '', 'Werdet ihr den Auftrag aufsfuehren?'),
('800526', 'Weekly: Onyxias Hort', 'Toetet Onyxia in Onyxias Hort. Ihr werdet reich belohnt werden !', '', 'Werdet ihr den Auftrag aufsfuehren?'),
('800527', 'Weekly: Der Schwarze Tempel', 'Toetet Illidan im schwarzen Tempel. Ihr werdet reich belohnt werden !', '', 'Werdet ihr den Auftrag aufsfuehren?'),
('800528', 'Weekly: Festung der Stuerme', 'Toetet KaelThas in der Festung der Stuerme. Ihr werdet reich belohnt werden !', '', 'Werdet ihr den Auftrag aufsfuehren?'),
('800529', 'Weekly: Hyjalgipfel', 'Toetet Archimonde im Hyjalgipfel. Ihr werdet reich belohnt werden !', '', 'Werdet ihr den Auftrag aufsfuehren?'),
('800530', 'Weekly: Hoehle des Schlangenschreins', 'Toetet Lady Vashj in der Hoehle des Schlangenschreins. Ihr werdet reich belohnt werden !', '', 'Werdet ihr den Auftrag aufsfuehren?'),
('800531', 'Weekly: Magtheridons Kammer', 'Toetet Magtheridon in Magtheridons Kammer. Ihr werdet reich belohnt werden !', '', 'Werdet ihr den Auftrag aufsfuehren?'),
('800532', 'Weekly: Karazhan', 'Toetet Malchezaar in Karazhan. Ihr werdet reich belohnt werden !', '', 'Werdet ihr den Auftrag aufsfuehren?'),
('800533', 'Weekly: Geschmolzener Kern', 'Toetet Ragnaros im Geschmolzener Kern. Ihr werdet reich belohnt werden !', '', 'Werdet ihr den Auftrag aufsfuehren?'),
('800534', 'Weekly: Pechschwingenhort', 'Toetet Nefarian im Pechschwingenhort. Ihr werdet reich belohnt werden !', '', 'Werdet ihr den Auftrag aufsfuehren?'),
('800535', 'Weekly: AhnQiraj', 'Toetet CThun in AhnQiraj. Ihr werdet reich belohnt werden !', '', 'Werdet ihr den Auftrag aufsfuehren?'),
('800536', 'Sammelwut extrem', 'Sammelt 300 Staehlerne Pfeilspitzen, 200 Netherstoff und toetet 60 Sonnenschuppenkreischer, 60 Fleischreisserhyjaenen, 40 Kluftmoosgiftspucker, 40 Blutsichelfelzhetzer.', 'Helft uns bitte beim Sammeln dieser wichtigen Gegenstaende. Wir benoetigen diese wirklich dringend.', 'Werdet ihr den Auftrag aufsfuehren?'),
('800538', 'Weekly: ICC Trash', 'Toetet die Diener in ICC vor dem erstem Boss!', '', 'Werdet ihr den Auftrag aufsfuehren?'),
('800539', 'Runenstoff', 'Bringt mir 50 Runenstoffe.', '$N,fuer meine magischen Runenworte brauche ich Runenstoff. Bringt mir diesen bitte. Da ich einen grossen Bedarf an Runenstoff habe, koennt ihr mir das jeden Tag vorbeibringen.', 'Es ist Eure Sache was ihr tut.'),
('800540', 'Grangolvar', 'Toetet 20 Schattenhafte Henker, 20 Schattenhafte Jaeger, 20 Schattenhafte Beschwoerer.', '$N,kennt ihr die Siedlung Grangol┬┤var? Dort haussen die, die vom rechten Weg abgekommen sind. Wir muessen sie liquidieren, da sie das Boese verbreiten. Schaut taeglich dort vorbei um sie dem Erdboden gleich zu machen.', 'Es ist Eure Sache was ihr tut.'),
('800541', 'Neue Kleidung', 'Bringt mir 35 Leichte Federn sowie 60 Netherstoffe.', '$N,hier draussen windet es stark. Meine Kleidung leidet darunter. Bitte helft mir, sonst muss ich erfrieren. Bringt mir 35 Leichte Federn sowie 60 Netherstoffe um meine Kleidung zu reparieren. Ich wuerde mich dafuer auch bedanken.', 'Es ist Eure Sache was ihr tut.'),
('800542', 'Spionageberichte', 'Bringt den Stapel Berichte zu Adal in Shattrath.', '$N,koennt ihr mir einen Gefallen machen? Bringt diese Berichte zu Adal. Sie sind wichtig und streng vertraulich. Ihr muesst Euch beeilen, den die Berichte muessen unverzueglich bei Adal ankommen.', 'Es ist Eure Sache was ihr tut.'),
('800543', 'Mehr Nahrung', 'Bringt mir 30 Talbukwildbret und 20 Becher Froschgiftbier.', '$N,mein Nahrungsvorrat ist begrenzt. Ich brauche daher immer neuen Nachschub. Bringt ihn mir Bitte.', 'Es ist Eure Sache was ihr tut.'),
('800544', 'Weekly: Kayoula', 'Toetet Kayoula.', 'Hallo $N, toetet Kayoula. Kayoula ist die verschollene Frau von Exitare. Sie muss sterben damit sich diese Brut nicht weiterentwickeln kann. Es ist notwendig!', 'Es ist Eure Sache was ihr tut.'),
('800545', 'Weekly: Therakin', 'Toetet Therakin.', 'Hallo $N, Toetet Therakin den Verraetern. Er ist ueber den Porter zu erreichen. Er muss vernichtet werden.', 'Es ist Eure Sache was ihr tut.'),
('800546', 'Weekly: Moon', 'Toetet Moon.', 'Hallo $N, Toetet Moon die Verraeterin. Sie ist ueber den Porter zu erreichen. Sie muss vernichtet werden.', 'Es ist Eure Sache was ihr tut.'),
('800548', 'Saeuberung vom Schlamm', 'Saeubert uns vom Schlamm und toetet 25 schwarzer Schlamm.', 'Dieser ekelhafte Schlamm verteilt ueberall seinen Unrat. Bitte bitte kuemmert Euch darum. Sie duerfen nicht wieder ihre schleimigen Spuren auf dem Boden hinterlassen', ''),
('800549', 'Die Moosfelle', 'Die Mossfelle und der Wollstoff muessen getoetet sowie gesammelt werden.', 'Die Mossfelle sammeln viel Wollstoff der uns fehlt, fuer Kleidung. Wir werden uns deren Wollstoffen aneignen. Toetet sie also alle, und klaut den Wollstoff.', ''),
('800550', 'Die Eulen', 'Toetet die primitiven Eulenbestien', 'Toete die primitiven Eulenbestien und die gifitgen Seuchenfledermaeuse um die Welt frei von Ungeziffer zu machen.', ''),
('800551', 'Der Geisselfuerst', 'Der Geisselfuerst muss sterben', 'Der Geisselfuerst Tyrannus ist mehr als nur ein Geschwuer in unserem Land. Holt die Grube zurueck. Sie war Teil unseres Reichtums. Dort haben wir unser Erz geschuerft, bis der Geisselfuerst sie uns abnahm.', ''),
('800556', 'Felicitas', 'Entledigt euch dem Schmiedemeister', 'Hallo $N, ich moechte das ihr euch Schmiedemeister Garfrost entledigt!', 'Es ist eure Sache was ihr tut.'),
('800557', 'Die 6 Aeonen', 'Bringt mir die Aeonen von Feuer, Schatten, Leben, Erde, Luft und Wasser.', 'Hallo $N, moechtet ihr Euch etwas verdienen? Bringt mir 6 Aeonen von Feuer, Schatten, Leben, Erde, Luft und Wasser. Die Marken die ihr bekommt, sind wichtig fuer spaeter.', 'Do what you like to do.'),
('802000', 'Die Gruenen Huegel Teil 1', 'Bringt mir die Seiten 1,4,6,8,10 der Gruenen Huegel des Schlingendorntals', 'Ich bin sehr an Geschichten interessiert, deswegen bitte ich Euch, mir diese 5 Seiten zu bringen. Ich bin leider nicht sehr reich, daher kann ich Euch keine grossen Belohnungen geben, aber ich kann Euch auf eine Reise schicken welche sich bestimmt fuer Euch lohnen wird.', 'Werdet ihr den Auftrag aufsfuehren?'),
('802001', 'Die Gruenen Huegel Teil 2', 'Bringt mir die Seiten 11,14,16,18,20 der Gruenen Huegel des Schlingendorntals', 'Die ersten fuenf Seiten waren sehr spannend und ereignisreich. Koennt ihr mir die weiteren Seiten bringen? Auf den ersten Blick wird es sich nur fuer manche lohnen, aber glaubt mir wenn ich Euch sage das dem nicht so ist.', 'Werdet ihr den Auftrag aufsfuehren?'),
('802002', 'Der Vogel', 'Toetet Sturmflamme im Krater von Un´goro', 'Guten Tag $N, $B Sturmflamme hat sich lange genug vor seinen Aufgaben ferngehalten. Er sollte den Berg unter Kontrolle halten, doch diese Aufgabe scheint ihm nun ueber den Kopf zu wachsen. Ihr muesst ihn liquidieren. Sofort!', 'Werdet ihr den Auftrag aufsfuehren?'),
('802003', 'Ein alter Bekannter', 'Bringt meinem alten Bekannten dieses Buch zurueck.', '$N, Ich habe mir vor langer Zeit ein Buch von einem alten Bekannten ausgeliehen.Koenntet ihr es zurueck bringen? Sie befindet sich an der Kueste in Desolace am Sartherisstrand.', 'Ich danke Euch von Herzen.'),
('802004', 'Geschenkuebermittlung', 'Bringt LokRegual auf der Insel mein Geschenk zurueck.', 'Hallo $N, ich danke Euch fuer das Zurueckbringen meines Buches. Wenn ihr ein Freund seid, uebermittelt LokRequal bitte dieses Geschenk. Ich wollte es ihm seit laengerer Zeit uebermitteln, fand aber nie die Zeit dazu. Seid also bitte so freundlich.', 'Es ist Eure Sache was ihr tut.'),
('802005', 'Der Strand', 'Toetet 10 tobende Donnerechsen und nehmt Euch ihre undichten Muskelmagen.', 'Hallo $N, bitte saeubert den Strand von den tobenden Donnerechsen. Sie haben die ganze Kueste verwuestet.', 'Es ist Eure Sache was ihr tut.'),
('802006', 'Friede sei mit uns.', 'Um Frieden zu wahren muessen wir unsere Feinde besiegen.', 'Hallo $N,toetet die Pusteligen Schrecken der hier am Strand entlang laeuft. Ich bitte Euch instaendig um Eure Hilfe. Wenn ihr das erledigt habt, geht bitte zu Silvaria Tularia in Beutebucht. Sie ist am Anleger fuer kleinere Schiffe zu finden z.b fuer Fischerboote.', 'Es ist Eure Sache was ihr tut.'),
('802007', 'Seltsame Fragmente', 'Bringt mir 10 Kristallene Fragmente', 'Hallo $N, ich bitte Euch mit 10 Kristallene Fragmente zu bringen. Es wird sich aufjedenfall lohnen. Wenn ihr nicht wisst wo ihr suchen sollt, gebe ich Euch einen Tipp. In Nagrand soll es Wesen geben die diese Fragmente fallen lassen. ', 'Es ist Eure Sache was ihr tut.'),
('802009', 'Kriecherfleisch', 'Sammelt 15 Stueck Kriecherfleisch.', '$N, ihr habt 15 Minuten Zeit um 15 Kriecherfleisch zu sammeln. Bitte schafft es in dieser Zeit,sonst ist das Fleisch leider wieder schlecht.', 'Es ist Eure Sache was ihr tut.'),
('802010', 'Der Fremde', 'Bringt mir 5000 Ehrenpunkte sowie 15 Embleme des Triumphs.', '$N,in den tiefen Waeldern des Daemmerwaldes haust Rumu, ein alter weisser Schamane. Er ist schon sehr alt, wird Euch aber bestimmt ein offenes Ohr leihen. Wenn ihr mir 5000 Ehrenpunkte sowie 15 Embleme des Triumps bringt, sage Ich Euch welches Abzeichen Rumu von Euch haben moechte.', 'Es ist Eure Sache was ihr tut.'),
('802011', 'Findet Rumu', 'Findet Rumu und gebt ihm das Abzeichen des Wyrmruhpaktes.', '$N,Rumu ist in der Naehe der Rabenflucht. Meist laeuft er dort an seinem Lagerfeuer herum. Das koennen manchmal laengere Wege sein, also verzagt nicht wenn er beim ersten Mal nicht anzutreffen ist. Er erwartet Euch bestimmt schon.', 'Es ist Eure Sache was ihr tut.'),
('802012', 'Rattenplage', 'Toetet 15 Ratten der Schattenseite.', '$N,in den Staedten herrscht eine Rattenplage. Befreit Dalaran von der Rattenplage. Toetet daher 15 Ratten.', 'Es ist Eure Sache was ihr tut.'),
('802013', 'Alchemie', 'Bringt mir 1 Elixier der Weisen, 1 Elixier der Schattenmacht sowie 1 Instabiles Flaeschen des Banditen.', '$N,ich beobachte schon laengere Zeit die Banditen des Defias in Westefall. Ein ungemuetlicher Haufen, der zu allem faehig ist. Deswegen benoetige ich diese Utensilien um mich bei ihnen heimlich einschleichen zu koennen. Bitte bringt mir alles so schnell wie moeglich.', 'Es ist Eure Sache was ihr tut.'),
('802014', 'Das Raetsel', 'Akzeptiert die Herausforderung.', '$N,Moechtet Ihr ein bisschen Abwechslung? Ich habe ein paar Raetsel fuer Euch. Diese sind unterschiedlich schwer. Es ist nicht wichtig wie lange Ihr dafuer braucht oder ob Ihr diese alleine macht oder nicht. Nehmt Euch Zeit um sie zu loesen. ', 'Ich warte auf Euch.'),
('802015', 'Das erste Raetsel', 'Loest das Raetsel.', '$N,im Norden des oestlichen Koenigreiches gibt es eine Halbmondformation auf der Karte. Rechts daneben gibt es 5 groessere Punkte, auf der Karte, die einen weiteren Halbkreis bilden.Der 2te Fleck von oben ist Euer Ziel. Dort findet ihr was ihr sucht. Wenn ihr das Raetsel geloest habt, wird Euch die Rueckkehrquest automatisch hinzugefuegt. Brecht diese also nicht ab.', 'Ich warte auf Euch.'),
('802018', 'Sammlung Teil Eins', 'Bringt Moon 75 Goldklee, 50 Wildstahlblumen sowie 30 Stueck Beulengras. ', '$N,$Bbringt mir 75 Goldklee, 50 Wildstahlblumen sowie 30 Stueck Beulengras. Das ganze vermahlen wir zu einem neuen Trank, welchen ihr von mir bekommt. ', 'Ich warte auf Euch.'),
('802019', 'Sammlung Teil Zwei', 'Bringt Moon 15 Feuersaat, 40 Junges Gemuese sowie 100 Stueck schweres Leder.', '$N,$Bbringt mir 15 Feuersaaten,40 Junges Gemuese sowie 100 Stueck schweres Leder. Ich hoffe Ihr seid willens alles benoetigte zu mir zu bringen.', 'Ich warte auf Euch.'),
('802020', 'Sammlung Teil Drei', 'Bringt Moon 20 blutige Spinnenfangzaehne, 20 Brocken Eberfleisch sowie 10 raue Eberhauer ', '$N,$Bas Sammeln geht weiter. Ich hoffe Ihr seid willens alles benoetigte zu mir zu bringen. Ihr findet die benoetigten Dinge bei Dun Morog, sowie im Schattenmondtal.', 'Ich warte auf Euch.'),
('802021', 'Sammlung Teil Vier', 'Bringt Moon 50 Spinnenseide, 100 Seidenstoffe und toetet 20 Domestizierter Krabbler und 20 verseuchte Baeren.', '$N,$Bbringt mir 50 Spinnenseide, 100 Seidenstoffe und toetet 20 Domestizierter Krabbler und 20 verseuchte Baeren. Ihr findet alles im Vorgebirge des Huegellandes.', 'Ich warte auf Euch.'),
('802022', 'Sammlung Teil Fuenf', 'Bringt Moon 4 eisige Taschen und 10.000 Gold.', '$N,$Bbringt mir 4 eisige Taschen um alle meine Gewuerze verstauen zu koennen und zusaetzlich 10.000 Gold. Langsam werden meine braunen Ruecksacke zu klein.', 'Ich warte auf Euch.'),
('802023', 'Sammlung Teil Sechs', 'Bringt Moon 5 frostige Kugel und 150 Froststoffverbaende.', '$N,$Bbringt mir 2 frostige Kugeln und 150 Froststoffverbaende. Ihr erreicht langsam aber sicher die erste Belohnung.', 'Ich warte auf Euch.'),
('802024', 'Die Saeuberung von Mondbruch', 'Loescht alle Besatzer von Mondbruch aus. Mindestens 20 Auspluenderer , 20 Pluenderer und 20 Boten der Defias.', '$N,ich habe euch ja schon erzaehlt das die Defias ein groesseres Problem in Westfall darstellen. Sie ueberfallen Haendler und pluendern unsere Farmen. Ich wurde geschickt um diesem Treiben ein Ende zu setzen. Und das werden wir nun gemeinsam umsetzen. Loescht alle Besatzer von Mondbruch aus. Mindestens 20 Auspluenderer , 20 Pluenderer und 20 Boten der Defias.', 'Es ist Eure Sache was ihr tut.'),
('802025', 'Fortschreiten der Saeuberung', 'Toetet 30 Beschwoerer der Defias, 30 Buddler der Defias sowie 30 Handlanger der Defias.', '$N,es ist an der Zeit tiefer in die Gebiete der Defias vorzuruecken. Mir muessen ihr Versteck oder das was sie so nennen, vernichten. Geht also in den Eingang der Todesminen und toetet 30 Beschwoerer der Defias, 20 Buddler der Defias sowie 30 Handlanger der Defias.', 'Es ist Eure Sache was ihr tut.'),
('802026', 'Eine neue Reise', 'Reist zu Krasus dem Gemahl der Koenigin.', 'Hallo $N,reist bitte zu Krasus dem Gemahl der Koenigin im Wyrmruhtempel in der Drachenoede. Er sollte Aufgaben fuer Euch haben.', 'Es ist Eure Sache was ihr tut.'),
('802028', 'Die Verjuengung', 'Bringt Krasus die Glyphe der Verjuengung.', 'Hallo $N,bringt mir bitte die Glyphe der Verjuengung. Es ist Zeit  mein ewiges Leben um ein weiteres Stueck zu verlaengern. Helft mir bitte.', 'Es ist Eure Sache was ihr tut.'),
('802029', 'Der Kommandant', 'Toetet den Nerubischen Kommandanten.', 'Hallo $N,der Nerubische Kommandant wacht auf seinem Berg und schuechtert seine ganze Umgebung ein. Wir muessen ihn loswerden. Toetet ihn. Ihr findet ihn auf der Anhoehe kurz hinter Gallgrimm in der Drachenoede. Es liegt zwischen der Feste Wintergarde und Gallgrimm.', 'Es ist Eure Sache was ihr tut.'),
('802030', 'Suche nach Exitares Frau', 'Findet und untersucht die Stelle an welcher Exitares Frau zuletzt gesehen wurde.', 'Hallo $N,Exitares Frau wurde entfuehrt. Er bat mich um Hilfe und ich werde ihm helfen. Sucht die Stelle auf, an der Kayoula zuletzt gesehen wurde und bringt mir erste Indizien fuer ihr verschwinden. Sucht nach ihren Federschmuck. Es kann sein, das dieser nicht mehr verstreut auf dem Boden liegt, sondern von den dort vorkommenden Drachenknochenkondoren aufgelesen wurde. Der letzte Ort an dem Kayoula gesehen wurde war links vom Obsidiandrachenschrein. Helft uns und ihr werdet reich belohnt.', 'Es ist Eure Sache was ihr tut.'),
('802031', 'Folgt der Spur', 'Folgt der Spur die Exitares Frau hinterlassen hat.', 'Hallo $N,zum Glueck seid ihr zurueckgekommen. Sucht nach einem weiteren Anhaltspunkt zum Verschwinden von Exitares Frau. Ich weiss das sie einen Zwischenstopp in der Gegend zwischen Granitquell und der Venturebucht machen wollten. Aber aus Sicherheitsgruenden wurde mir der genaue Ort verschwiegen.', 'Es ist Eure Sache was ihr tut.'),
('802032', 'Verlagerung der Truppen', 'Reist zur Hoellenfeuerhalbinsel und verstaerkt unsere Aushilfstruppen.', 'Hallo $N,wir muessen die Suche leider ruhen lassen. Unsere Aushilfstruppen sind in grosser Bedraengnis. Ihr muesst sie Unterstuetzen. Reisst zur Hoellenfeuerhalbinsel zum Posten des Cenarius und meldet Euch bei Tiah Rotmaehne.', 'Es ist Eure Sache was ihr tut.'),
('802033', 'Angriff auf die Angreifer', 'Toetet 40 Sumpflichtbluter und 25 Verhungender Fungusgiganten.', 'Hallo $N, Euere erste Schlacht wird in Zangarmarschen stattfinden. Geht dorthin und toetet 40 Sumpflichtbluter sowie 25 Verhungende Fungusgiganten. Sie koorperieren mit unserem eigentlichen Feind. Daher muessen sie vernichtet werden.', 'Es ist Eure Sache was ihr tut.'),
('802034', 'Die zweite Welle abfangen', 'Toetet Kael┤thas, Murmur, Magheridon sowie das Grauen aus der Tiefe.', 'Hallo $N, die zweite Welle werden wir abfangen. Die 4 Kommandanten muessem dazu vernichtet werden. Hoffen wir das ihre Anstrengungen dadurch durcheinander gebracht werden.', 'Es ist Eure Sache was ihr tut.'),
('802035', 'Erfolg oder doch nicht?', 'Um den Erfolg zu garantieren muessen wir Auktionspapiere erlangen.', 'Hallo $N, wir haben von Auktionspapieren erfunden, welche unser Feind nutzt um seine Geschaefte auf den Maerkten geheim zu halten. Wir muessen diese Papiere erlangen um deren Transaktionen folgen zu koennen. Bitte bringt uns 10 solcher Papiere, das sollte uns reichen.', 'Es ist Eure Sache was ihr tut.'),
('802036', 'Die erste Spur', 'Wir haben eine erste Spur, bringt Kayoulas zerbrochene Anhaengerstuecke zu mir.', 'Hallo $N, ich habe aufregende Neuigkeiten fuer Euch. Wir haben durch die Auktionspapiere einen ersten Unterhaendler ausfindig machen koennen. Anscheinend soll er am ueberfall auf Exitares Frau beteiligt gewesen sein. Geht zu ihm und prueft ob er beteiligt war, und bringt entsprechende Beweise zu mir zurueck. Ob er dabei am Leben bleibt oder nicht, ist mir egal. Macht was ihr wollt mit ihm.', 'Es ist Eure Sache was ihr tut.'),
('802037', 'Die Verfeinerung', 'Bringt mir die glitzernde Spinnenseide.', 'Hallo $N, wir haben den fertiggestellten Anhaenger hier. Nun muss er mit glitzernder Spinnenseide umgarnt werden. Diese koennen wir nur bei der Koenigin der Spinnen finden. Maexxa. Geht zu ihr und entwedet ihr diesen extrem seltenen Seidenstoff. ', 'Es ist Eure Sache was ihr tut.'),
('802038', 'Rueckkehr', 'Bringt Krasus den seidenen Anhaenger', 'Hallo $N, bringt den seidenen Anhaenger zu Krasus zurueck. Er wird wissen was zu tun ist.', 'Es ist eure Sache was ihr tut.'),
('802039', 'Neue Informationen', 'Schaut Euch die neuen Informationen im Questlog an.', 'Hallo $N, hier ist der aktuelle und neueste Stand. Wir haben den ersten Aufenhaltspunkt gefunden und haben den Angaenger wieder zusammengesetzt. Wir haben Klingenspuren an dem Anhaenger gefunden, die wir leider noch nicht richtig zuordnen koennen. Die Indizien verdichten sich aber in eine bestimmte Richtung. Dazu moechte ich aber nicht zu viel sagen. Wir sollten Anhaenger zu einem Schmied bringen, um die Spuren zu ueberpruefen.', 'Es ist Eure Sache was ihr tut.'),
('802040', 'Neue Informationen', 'Bringt Krasus die Informationen zurueck.', 'Hallo $N, ich konnte die Kerbe nicht genau identifizieren, glaube aber das sie durch ein Schwert verursacht worden ist. Dieses Schwert hatte ein alte Klinge. Sie war aber nicht aus gewoehnlichem Metall. Ich hab so eine Klinge erst einmal zuvor gesehen. Aber das.... ist nicht moeglich. Bringt meinen Befund so schnell es geht fort und nehmt diesen Anhaenger mit, ich will das nicht mehr hier haben! ', 'Es ist Eure Sache was ihr tut.'),
('802041', 'Die Reise zu Exitare', 'Geht zu Exitare und teilt ihm alles mit.', 'Hallo $N, bitte bringt die schlechten Nachrichten zu Exitare auf der Insel. Ich hoffe fuer Euch das er euch nicht den Kopf abschlaegt bei diesen Neuigkeiten.', 'Es ist Eure Sache was ihr tut.'),
('802042', 'Der Schmerz', 'Bringt Exitare die Taschentuecher.', 'Ich brauche Taschentuecher von Euch. Geht sofort. Ich kann die Trauer kaum verkraften, obwohl wir immer noch nicht genau wissen was eigentlich passiert ist. Bringt mir diese Taschentuecher. ', 'Es ist Eure Sache was ihr tut.'),
('802300', 'Beutebucht', 'Toetet Mok┤rash den Spalter', 'Hallo $N, Mok┤rash der Spalter versperrt die Bucht zu Beutebucht. Er muss getoetet werden, damit wir weitere Handelslieferungen erhalten koennen.', 'Es ist Eure Sache was ihr tut.'),
('802301', 'Meldung in Ratchet', 'Meldet Euch bei Kapitaen Thalo`thas Blendsoon', 'Hallo $N, meldet Euch bei Kapitaen Thalo`thas Blendsoon. Er hat weitere Instruktionen fuer Euch. Es ist sehr sehr wichtig. ', 'Es ist Eure Sache was ihr tut.'),
('802302', 'Alte Rechnungen begleichen', 'Begleicht meine alten Rechnungen', 'Hallo $N, ich hab noch ein paar Rechnungen mit alten Bekannten offen. Koennt ihr Euch darum kuemmern bitte? Ich finde es sehr sehr wichtig. Ich wurde hintergangen, waehrend unserer gemeinsamen Zeit. Koennt ihr mir bei der Gelegenheit gleich noch etwas fuer meinen Eintopf bringen? Ich danke $N.', 'Es ist Eure Sache was ihr tut.'),
('802303', 'Die Mechanar', 'Nehmt Euch den Mechanar an', 'Piep, Piep, Piep....... *Roll* *Roll* *Roll* Oh hallo $N. Ich habe gerade versucht die Mechanar ironisch zu vertonen. Naja war nicht so erfolgreich. Aber lassen wir das. Meine Freunde von den Sha`tar hassen dieses Gesocks von verhassten Leuten. Wenn ihr Euch bei den Sha`tar beliebt machen wollt, fuehrt ihr diese Aufgabe aus. ', 'Es ist Eure Sache was ihr tut.'),
('802304', 'Reise durch die Zeit', 'Toetet die Intriganten', 'Ich danke Euch fuer das Ausfuehren der Aufgabe. Ich habe auch sofort eine naechste fuer Euch. Im Scharlachroten Kloster gibt es Wesen, wenn man das so sagen darf, welche des Lebens nicht wuerdig sind.', 'Es ist Eure Sache was ihr tut.'),
('802305', 'Torvan von Doom', 'Reise zu einem alten Freund', 'Arggh $R. Ihr muesst unbedingt zu Tovan von Doom dem Unerreichbaren reisen. Torvan ist ein alter Reisegeselle aus unseren Seemanszeiten. Geht zu ihm und berichtet ihm, dass sein alter Freund Raubein noch lebt. Er wird sich an mich erinnern. Vielleicht moechtet ihr ihm aber noch etwas zu trinken bringen. Wir Seemaenner sind ja ein Trinkervoelkchen.', 'Es ist Eure Sache was ihr tut.'),
('802306', 'Die geheime Nachricht', 'Bringt die geheime Nachricht zu Rumus Diener', 'Bringt die geheime Nachricht an einen von Rumu┤s Dienern. Ich moechte das ihr mir beweist, das ihr zu eurem Wort steht. Bringt einem Diener von Rumu die Nachricht. Geht jetzt Landratten!', 'Es ist Eure Sache was ihr tut.'),
('802307', 'Die Rueckkehr', 'Bringt die mysterioese Nachricht zurueck zu Torvan.', 'Bringt die mysterioese Nachricht zurueck zu Tovan von Doom. In der Nachricht ist bestimmt bescheinigt das ihr loyal und ausdauernd seid.', 'Es ist Eure Sache was ihr tut.'),
('802308', 'Der Pirat in Torvan', 'Stillt Torvans Verlangen nach Gold', 'Hey ihr da. Ich bin ein Pirat und ihr seht reich aus. Bringt mir Gold, Gold, Gold, Gold. .....Moment, ich will Gold von Euch. Ohne das Gold, werde ich nicht mehr mit Euch reden.', 'Es ist Eure Sache was ihr tut.'),
('802309', 'Das flammende Herz', 'Bringt Torvan das flammende Herz', 'Jetzt wo ihr mir mein Gold gebracht habt, kann ich ja normal mit Euch reden. Bringt mir das flammende Herz des Verdammniswandlers! ╔s ist ein wertvolles episches Stueck! Damit laesst sich auf dem Schwarzmarkt ein guter Preis erzielen.', 'Es ist Eure Sache was ihr tut.'),
('802310', 'Das brennende Herz', 'Bringt Torvan das brennende Herz', 'Der Verkauf des flammenden Herzen hat mir eine Menge Gold eingebracht. Ich habe von einem weiteren Herzen gehoert. Bringt mir das brennende Herz des Verdammniswandlers Kazzak! ╔s ist ein wertvolles episches Stueck! Damit laesst sich auf dem Schwarzmarkt ein guter Preis erzielen. Wenn ihr mir beides gebracht habt, bekommt ihr ein Teil des Erloeses.', 'Es ist Eure Sache was ihr tut.'),
('802800', 'Der Pfad zum Powerranger', 'Toetet den Schmiedemeister Garfrost sowie 10 unbaendige Seher im Kristallsangwald.', 'Hallo $C $N, eure erste Aufgabe besteht aus folgenden Teilen. Toetet den Schmiedemeister Garfrost sowie 10 unbaendige Seher im Kristallsangwald. Ich wuensche viel Erfolg. Hoffentlich besteht ihr alle Pruefungen auf dem Weg zum Powerranger.', 'Es ist Eure Sache was ihr tut.'),
('802801', 'Die Ausbildung beginnt', 'Loescht das kommplete Obsidiansanktum aus. ', 'Hallo $C $N, es ist schoen das ihr Eure erste Aufgabe bestanden habt. Beginnen wir nun mit der Ausbildung zum Powerranger, damit ihr eurer Ruestung wuerdig erscheint. So kommen wir nun zur 2ten. Loescht das Obsidiansanktum ein fuer alle mal komplett aus. Diese Drachen verpesten mit ihrem ewigen Feuer nur unsere Umwelt. Drum rauft euch zusammen und entledigt Euch diesen Kreaturen.', 'Es ist Eure Sache was ihr tut.'),
('802809', 'Der Pfad eines echten Kriegers', 'Toetet den Schmiedemeister Garfrost sowie 10 unbaendige Seher im Kristallsangwald.', 'Hallo $C $N, eure erste Aufgabe besteht aus folgenden Teilen. Toetet den Schmiedemeister Garfrost sowie 10 unbaendige Seher im Kristallsangwald. Ich wuensche viel Erfolg. Hoffentlich besteht ihr alle Pruefungen auf dem Weg um ein echter Krieger zu werden.', 'Es ist Eure Sache was ihr tut.'),
('802810', 'Die Ausbildung beginnt', 'Loescht das kommplete Obsidiansanktum aus. ', 'Hallo $C $N, es ist schoen das ihr Eure erste Aufgabe bestanden habt. Beginnen wir nun mit der Ausbildung zum erstarkten Krieger, damit ihr eurer Ruestung wuerdig erscheint. So kommen wir nun zur 2ten. Loescht das Obsidiansanktum ein fuer alle mal komplett aus. Diese Drachen verpesten mit ihrem ewigen Feuer nur unsere Umwelt. Drum rauft euch zusammen und entledigt Euch diesen Kreaturen.', 'Es ist Eure Sache was ihr tut.'),
('802818', 'Der Pfad zum gelaeuterter Magier', 'Toetet den Schmiedemeister Garfrost sowie 10 unbaendige Seher im Kristallsangwald.', 'Hallo $C $N, eure erste Aufgabe besteht aus folgenden Teilen. Toetet den Schmiedemeister Garfrost sowie 10 unbaendige Seher im Kristallsangwald. Ich wuensche viel Erfolg. Hoffentlich besteht ihr alle Pruefungen auf dem Weg zum gelaeuterten Magier.', 'Es ist Eure Sache was ihr tut.'),
('802819', 'Die Ausbildung beginnt', 'Loescht das kommplete Obsidiansanktum aus. ', 'Hallo $C $N, es ist schoen das ihr Eure erste Aufgabe bestanden habt. Beginnen wir nun mit der Ausbildung zum gelaeuterten Magier, damit ihr eurer Ruestung wuerdig erscheint. So kommen wir nun zur 2ten. Loescht das Obsidiansanktum ein fuer alle mal komplett aus. Diese Drachen verpesten mit ihrem ewigen Feuer nur unsere Umwelt. Drum rauft euch zusammen und entledigt Euch diesen Kreaturen.', 'Es ist Eure Sache was ihr tut.'),
('802827', 'Der Pfad zum lederhungrigen Schurken', 'Toetet den Schmiedemeister Garfrost sowie 10 unbaendige Seher im Kristalsangwald.', 'Hallo $C $N, eure erste Aufgabe besteht aus folgenden Teilen. Toetet den Schmiedemeister Garfrost sowie 10 unbaendige Seher im Kristallsangwald. Ich wuensche viel Erfolg. Hoffentlich besteht ihr alle Pruefungen auf dem Weg zum lederhungrigen Schurken.', 'Es ist Eure Sache was ihr tut.'),
('802828', 'Die Ausbildung beginnt', 'Loescht das kommplete Obsidiansanktum aus. ', 'Hallo $C $N, es ist schoen das ihr Eure erste Aufgabe bestanden habt. Beginnen wir nun mit der Ausbildung zum gelaeuterten Magier, damit ihr eurer Ruestung wuerdig erscheint. So kommen wir nun zur 2ten. Loescht das Obsidiansanktum ein fuer alle mal komplett aus. Diese Drachen verpesten mit ihrem ewigen Feuer nur unsere Umwelt. Drum rauft euch zusammen und entledigt Euch diesen Kreaturen.', 'Es ist Eure Sache was ihr tut.'),
('802836', 'Der Pfad zum treffsicheren Jaeger ', 'Toetet den Schmiedemeister Garfrost sowie 10 unbaendige Seher im Kristallsangwald.', 'Hallo $C $N, eure erste Aufgabe besteht aus folgenden Teilen. Toetet den Schmiedemeister Garfrost sowie 10 unbaendige Seher im Kristallsangwald. Ich wuensche viel Erfolg. Hoffentlich besteht ihr alle Pruefungen auf dem Weg zum treffsicheren Jaeger.', 'Es ist Eure Sache was ihr tut.'),
('802837', 'Die Ausbildung beginnt', 'Loescht das kommplete Obsidiansanktum aus. ', 'Hallo $C $N, es ist schoen das ihr Eure erste Aufgabe bestanden habt. Beginnen wir nun mit der Ausbildung zum treffsicheren Jaeger, damit ihr eurer Ruestung wuerdig erscheint. So kommen wir nun zur 2ten. Loescht das Obsidiansanktum ein fuer alle mal komplett aus. Diese Drachen verpesten mit ihrem ewigen Feuer nur unsere Umwelt. Drum rauft euch zusammen und entledigt Euch diesen Kreaturen.', 'Es ist Eure Sache was ihr tut.'),
('802838', 'Der Pfad zum Schamane ', 'Toetet den Schmiedemeister Garfrost sowie 10 unbaendige Seher im Kristallsangwald.', 'Hallo $C $N, eure erste Aufgabe besteht aus folgenden Teilen. Toetet den Schmiedemeister Garfrost sowie 10 unbaendige Seher im Kristallsangwald. Ich wuensche viel Erfolg. Hoffentlich besteht ihr alle Pruefungen auf dem Weg zum maechtigen Schamanen.', 'Es ist Eure Sache was ihr tut.'),
('802839', 'Die Ausbildung beginnt', 'Loescht das kommplete Obsidiansanktum aus. ', 'Hallo $C $N, es ist schoen das ihr Eure erste Aufgabe bestanden habt. Beginnen wir nun mit der Ausbildung zum maechtigen Schamanen, damit ihr eurer Ruestung wuerdig erscheint. So kommen wir nun zur 2ten. Loescht das Obsidiansanktum ein fuer alle mal komplett aus. Diese Drachen verpesten mit ihrem ewigen Feuer nur unsere Umwelt. Drum rauft euch zusammen und entledigt Euch diesen Kreaturen.', 'Es ist Eure Sache was ihr tut.'),
('802840', 'Der Pfad zum Priester ', 'Toetet den Schmiedemeister Garfrost sowie 10 unbaendige Seher im Kristallsangwald.', 'Hallo $C $N, eure erste Aufgabe besteht aus folgenden Teilen. Toetet den Schmiedemeister Garfrost sowie 10 unbaendige Seher im Kristallsangwald. Ich wuensche viel Erfolg. Hoffentlich besteht ihr alle Pruefungen auf dem Weg zum maechtigen Schamanen.', 'Es ist Eure Sache was ihr tut.'),
('802841', 'Die Ausbildung beginnt', 'Loescht das kommplete Obsidiansanktum aus. ', 'Hallo $C $N, es ist schoen das ihr Eure erste Aufgabe bestanden habt. Beginnen wir nun mit der Ausbildung zum Priester, damit ihr eurer Ruestung wuerdig erscheint. So kommen wir nun zur 2ten. Loescht das Obsidiansanktum ein fuer alle mal komplett aus. Diese Drachen verpesten mit ihrem ewigen Feuer nur unsere Umwelt. Drum rauft euch zusammen und entledigt Euch diesen Kreaturen.', 'Es ist Eure Sache was ihr tut.'),
('802842', 'Der Pfad zum Hexer ', 'Toetet den Schmiedemeister Garfrost sowie 10 unbaendige Seher im Kristallsangwald.', 'Hallo $C $N, eure erste Aufgabe besteht aus folgenden Teilen. Toetet den Schmiedemeister Garfrost sowie 10 unbaendige Seher im Kristallsangwald. Ich wuensche viel Erfolg. Hoffentlich besteht ihr alle Pruefungen auf dem Weg zum Hexer.', 'Es ist Eure Sache was ihr tut.'),
('802843', 'Die Ausbildung beginnt', 'Loescht das kommplete Obsidiansanktum aus. ', 'Hallo $C $N, es ist schoen das ihr Eure erste Aufgabe bestanden habt. Beginnen wir nun mit der Ausbildung zum Hexer, damit ihr eurer Ruestung wuerdig erscheint. So kommen wir nun zur 2ten. Loescht das Obsidiansanktum ein fuer alle mal komplett aus. Diese Drachen verpesten mit ihrem ewigen Feuer nur unsere Umwelt. Drum rauft euch zusammen und entledigt Euch diesen Kreaturen.', 'Es ist Eure Sache was ihr tut.'),
('802844', 'Der Pfad zum Druide ', 'Toetet den Schmiedemeister Garfrost sowie 10 unbaendige Seher im Kristallsangwald.', 'Hallo $C $N, eure erste Aufgabe besteht aus folgenden Teilen. Toetet den Schmiedemeister Garfrost sowie 10 unbaendige Seher im Kristallsangwald. Ich wuensche viel Erfolg. Hoffentlich besteht ihr alle Pruefungen auf dem Weg zum Druide.', 'Es ist Eure Sache was ihr tut.'),
('802845', 'Die Ausbildung beginnt', 'Loescht das kommplete Obsidiansanktum aus. ', 'Hallo $C $N, es ist schoen das ihr Eure erste Aufgabe bestanden habt. Beginnen wir nun mit der Ausbildung zum Druide, damit ihr eurer Ruestung wuerdig erscheint. So kommen wir nun zur 2ten. Loescht das Obsidiansanktum ein fuer alle mal komplett aus. Diese Drachen verpesten mit ihrem ewigen Feuer nur unsere Umwelt. Drum rauft euch zusammen und entledigt Euch diesen Kreaturen.', 'Es ist Eure Sache was ihr tut.'),
('803000', 'Der Novize', 'Bringt 1500 Ehrenpunkte zum Goldenen Schwein Yasio im Kreis der Maechte in Dalaran.', '$N, Sei gegruesst. Ich bin Therakin. Ich moechte dich einladen bei unseren blutigen Wettkaempfen teilzunehmen. Wenn du das moechtest bringe, als Zeichen deines Willens, 1500 Ehrenpunkte zu Yasio. Yasio ist ein goldenes Schwein , welches sich im Kreis der Maechte in Dalaran befindet.', 'Ihr seid wohl nicht so einfach gestrickt wie ich dachte.'),
('803001', 'Der erste Tag', 'Bringt mir 50 Splitter des Steinbewahrers', '$N, Heute bricht der erste Tag an. Ich moechte das Ihr mir 50 Splitter eines Steinbewahrers bringt. Zeigt mir wie talentiert Ihr im Toeten Eurer Feinde seid. Ich moechte das Blut Eurer Feinde an Eurer Kleidung sehen.', 'Ihr seid wohl nicht so einfach gestrickt wie ich dachte.'),
('803002', 'Der zweite Tag', 'Sammelt die benoetigten Materialien damit wir unsere Kraefte wieder finden koennen um uns ins naechste Gemetzel stuerzen zu koennen.', '$N,bringt mir 10 aeonenwasser,10 aeonenerde,10 aeonenfeuer,10 aeonenleben, 10 aeonenluft, 300 Altersgraue Kristalle. Bringt diese anschliessend zur Insel zu Therakin. Dieser wird Euch weitere Instruktionen geben.', 'Ihr seid wohl nicht so einfach gestrickt wie ich dachte.'),
('803003', 'Der Haertetest', 'Toetet die Wachen der Allianz in Tausenwinter. ', '$N, Ich moechte das ihr 200 Wachen der Allianz toetet. Lasst keine Gnade walten. Verschont keinen! Die Horde wird obsiegen.', 'Ihr seid wohl nicht so einfach gestrickt wie ich dachte.'),
('803004', 'Der Haertetest', 'Toetet die Wachen der Horde in Tausenwinter.', '$N, Ich moechte das ihr 200 Wachen der Horde toetet. Es wird Zeit das wir der Horde einen schweren Schlag versetzen.', 'Ihr seid wohl nicht so einfach gestrickt wie ich dachte.'),
('803005', 'Meldung beim Obersten Kriegsfuerst Therakin Irael', 'Meldet Euch beim Obersten Kriegsfuerst Therakin Irael im PVP Areal.', '$N, Ich moechte das ihr Euch bei Therakin Irael dem obersten Kriegsfuersten meldet. Geht zu Seruc von Lantus um Euch zum PVP-Areal bringen zu lassen.', 'Ihr seid wohl nicht so einfach gestrickt wie ich dachte.'),
('805000', 'Der Aufbau', 'Geht zu Marlerian Vanduin und hoert Euch an was er zu sagen hat.', '$N,$BMarlerian Vanduin hat Euch etwas wichtiges zu sagen. Geht zu ihm und hoert es Euch an.', 'Ich warte auf Euch.'),
('805001', 'Wir brauchen Plaene!', 'Finde die Plaene!', 'Wir wollen  unser neues Areal aufbauen und dazu benoetigen wir zu Beginn mal drei Bauplaene.$BDiese Bauplaene koennt ihr in den ersten Instanzen finden, welche ihr in eurer Laufbahn betreten konntet.', 'Verflixt nochmal, wie lange soll ich den warten?'),
('805002', 'Meine Leute brauchen Ausdauer', 'Sie sind geschwaecht, bringt mir diese Verzauberungen mit Ausdauer fuer sie.', 'Meine Leute brauchen fuer die naechsten Schritte unseres Bauvorhabens viel Ausdauer. Hilf mir indem du mir diese Verzauberungen besorgst!', 'Verflixt nochmal, die Leute haben keine Ausdauer!'),
('805003', 'Murlocs stoeren die Transportarbeiten', 'Findet und toetet sie alle!', 'Wir koennen nicht zuegig voran kommen.$BDiese Murlocs am Strand im Vorgebirge des Huegellands stoeren den Transport unserer Ressourcen.$B$N bereinigt den Strand und kommt wieder zu mir.', 'Verflixt nochmal, wir kommen nicht voran!'),
('805004', 'Multifunktionswerkzeug', 'Bringt mir dieses Werkzeug.', 'Man munkelt, dass es ein paar Spezialisten gibt, welche dieses Gnomische Armeemesser herstellen koennen.$B$BBringt mir 5 Stueck von diesem Werkzeug.', 'Wir brauchen mehr Werkzeuge.'),
('805005', 'Bauplaene fuer Dynamit', 'Fuer den Steinbruch brauchen wir Dynamit um die Steine zu loesen die wir transportieren muessen.$BEs fehlt uns jedoch an den Bauplaenen dafuer, besorgt mir diese.', 'Soweit ich informiert bin findest du eines dieser Rezepte ihr in Gnomeregan, dass andere kann man irgendwo in Tanaris kaufen.$BBeeilt euch, wir muessen mehr Steine fuer die Mauern besorgen!', 'Wir brauchen die Bauplaene fuer das Dynamit.'),
('805006', 'Das Rennen', 'Renn, renn, RENN so schnell du kannst!', 'Renn und toete Hogger, beeil dich!', 'Renn und toete Hogger!'),
('805007', 'Von wegen erschoepft!', 'Sammle diverse Kraeuter fuer die Anti-Erschoepfungs-Therapie', 'Bringe mir doch paar von diesen Kraeutern, $N.$B$BAnschliessend braue ich fuer euch einige aufputschende Traenke.', 'Hast du schon alle Kraeuter?'),
('805008', 'Ein Rat von einem alten Freund', 'Reist zu Devastor Saurutor und fragt ihn um den Rat.', 'Mein alter Freund Devastor Saurutor ist in Nagrand ueber dem Konstruktionslager: Furcht.$BEr ist ein alter Meister der Alchemie.$BReist dorthin und fragt ihn um den Rat zu den neuen Rezepten fuer unerloeschbare Kraft.', 'Reist zu Devastor Saurutor und fragt ihn um den Rat.'),
('805009', 'Verrat', 'Kehrt zu Rumu zurueck.', '$NWie sich heraus stellte ist Devastor Saurutor auf die andere Seite gewechselt, scheinbar haben wir ein Problem.$B$N, kehrt zu Rumu zurueck und berichtet ihm unverzueglich von den Ereignissen.', 'Kehrt zu Rumu zurueck.'),
('805010', 'Hilfe von Exitare', 'Geht zu Exitare, berichtet ihm was gerade geschehen ist und bittet ihn um Hilfe im Falle eines Verrats.', 'Devastor Saurutor war einstmalig ein Feind, jedoch hatte er vor langer Zeit seine Loyalitaet uns gezeigt.$Bscheinbar war dies schon vor langer Zeit geplant, dass er sich in unseren Zirkel einschliesst und uns von Innen angreift.$B$B$C reist zu Exitare auf die Insel und bittet ihn um Hilfe!', 'Reist zu Exitare.'),
('805011', 'Sucht Rat bei A\'dal', 'Ihr findet ihn in bei der Terrasse des Lichts.', 'In solch einem Fall von Verat muessen wir uns Hilfe von A\'dal besorgen. A\'dal wird jedoch nicht sofort uns helfen, er wird Vieles von uns erwarten, bevor er ueberhaupt sich unser Problem anhoeren wird.$B$BA\'dal ist in der Scherbenwelt, bei der Terrasse des Lichts.', 'Reist zur Terrasse des Lichts.'),
('805012', 'Loyalitaetsbeweis', 'Beweist mir eure Loyalitaet indem ihr mir paar Marken abgebt.', '$R, bevor ich mir ueberhaupt euer Problem anhoeren werde, muesst ihr den langen Prozess des Loyalitaetsbeweis bewaeltigen.$BFangen wir mal mit etwas Leichtem an. Nachdem Lich King an die Herrschaft gekommen ist, sind scheinbar neue Marken in den Umlauf gekommen, ich moechte mir diese genauer ansehen, besorgt mir einige von denen, $N.', ''),
('805013', 'Das Reskkversteck', 'Vor nicht all zu langer Zeit sind diese ekligen Kraehen dort eingezogen und haben sich breit gemacht. Hilf mir bei meinen Plaenen.', 'Fliegt zum Reskkversteck, welches oestlich von Shattrath liegt und besorgt mir paar Federn dieser Kraehen, damit ich diese untersuchen kann. Und wenn ihr schon da seid, dann zeigt ihnen wie stark wir sind.', ''),
('805014', 'Ein Anliegen', 'Zul\'Aman ist euer naechstes Ziel auf dem Pfad der Intrigen.', 'Reist als starke Gruppe nach Zul\'Aman und erledigt die Besatzung. Sie haben vor langer Zeit meine Familie getoetet und ich bin allein zu schwach dafuer. Helft mir bitte, $C.', 'test3'),
('805015', 'Findet unseren Spion', 'Wir haben einige Spione ausgesandt welche die aktuelle Lage in der Scherbenwelt beobachten. Findet einen bestimmten Spion.', 'Findet einen Spion von uns in der Scherbenwelt, er ist nach Schergrat geschickt worden. Ich kann mich nicht mehr gut daran erinnern. Er wurde aber in den Norden geschickt, ich glaube, er war auf einem separaten Plateau. Ich weiss aber, dass es gruen ist und lauter Kraehen dort stehen.', 'Findet den Spion in Schergrat.'),
('805016', 'Hilfe bei der Spionage', 'Ich bin hier schon seit Ewigkeiten, koenntest du mir nicht etwas helfen?', 'Es waere sehr hilfreich, wenn mir jemand meine Verpflegung wieder auffrischen koennte. Ich sitze hier schon seit... seit sehr langer Zeit und muss diese Kraehen beobachten.$B$BBesorgt mir doch bitte etwas Fleisch und Pflaster. Aber bitte kein Rohes, ich kann hier kein Lagerfeuer aufschlagen.', 'Reist zurueck zu dem Spion.'),
('805017', 'Berichterstattung', 'Du hast mir nun schon geholfen, jetzt hab ich endlich wieder Nahrung und Verbaende. Nur weiss ich nicht wohin ich all diese Sachen packen soll.', 'Ich habe hier ungewoehnliche Bewegungen festgestellt, ich vermute da wird etwas Grosses geplant, aber ich kann es noch nicht genau sagen. Es wird noch etwas dauern, bis ich genaueres weiss.$B$BDamit meine Vorraete nicht zu faulen, brauche ich noch Taschen. Waert ihr so nett und wuerdet mir zwei dieser Taschen spaeter mitbringen?', 'Nun besorgt euch den Bericht.'),
('805018', 'Meldung an Exitare', 'Geht zurueck zur Insel und leitet die Informationen an Exitare weiter.', 'Reist unverzueglich zurueck zur Insel und berichtet Exitare von den neuen Errungenschaften.', 'Berichtet von den Errungenschaften.'),
('805019', 'Berichte an Rumu', 'Informiert Rumu ueber die aktuelle Entwicklung.', '$N, Rumu muss unbedingt die aktuelle Entwicklung erfahren. Er ist ein guter Freund, daher moechte ich das er auf dem aktuellsten Stand ist. Er hat auch meistens gute Ideen zur Problemloesung. Daher geht bitte so schnell wie moeglich zu Rumu. ', 'Es ist Eure Sache was ihr tut.'),
('805020', 'Messung der Staerke', 'Macht euch auf den Weg nach Grishnath, kaempft gegen deren Einwohner und dokumentiert deren Staerke.', 'Damit ich uns auf den Kampf vorbereiten kann, muessen wir herausfinden wie stark diese Kraehen sind. Begebt euch nach Grishnath und toetet ein paar von den Einwohnern.$B$BPasst jedoch auf, dass ihr nicht den Falken von Grishna toetet, er ist einer von uns und kundschaftet das Gebiet aus.', 'Berichtet von den Errungenschaften.'),
('805021', 'Aufruestung Teil: 1', 'Fuer Trainingszwecke brauchen wir einige Gegenstaende um unsere Kraefte zu staerken.', 'Wir werden hart trainieren muessen, deswegen brauchen wir bestimmte Gegenstaende die uns helfen werden dabei unsere Kampfkuenste zu verbessern.$B$BWir sollten damit beginnen, dass wir Verzauberungen und Staerkungsrollen sammeln und horten. Macht euch auf den Weg und besorgt mir diese Gegenstaende.', 'Gebt diese Gegenstaende ab.'),
('805022', 'Aufruestung Teil: 2', 'Meine Schueler sind am Verhungern, wir brauchen mehr Nahrung.', 'Wir machen gute Fortschritte, aber das Training ist auch sehr hart und macht meine Schueler hungrig... $BIhr habt doch ein Reittier, koenntet ihr nicht etwas Obst und Wasser besorgen?', 'Gebt diese Gegenstaende ab.'),
('805023', 'Magie aufladen', 'Um ueberhaupt diese maechtige Magie einsetzen zu koennen bedarf es wichtiger Vorbereitungen.', 'Es scheint als muessten wir alte Zauber aus den Lehrbuechern verwenden um diese Kraehen los zu werden, ich hab in den Buechern schon nachgelesen und brauche dadurch noch einige Materialen. Ihr findet diese Gegenstaende in der Scherbenwelt.', 'Gebt diese Gegenstaende ab.'),
('805024', 'Rumus Zeitvertreib', 'Angeln, angeln, angeln - Ruhe, psssht.', 'Taeglich muss ich meinen Bedarf an Kohlenhydraten decken, deswegen gehe ich regelmaessig fischen. Mittlerweile schaffe ich nicht alleine die Menge zu fischen, die ich fuer die Nahrungszufuhr brauch.$B$BHelft mir bitte beim Fischen.', 'Gebt die Fische ab.'),
('870000', 'Sammlung Teil Sieben', 'Bringt mir 100 Thoriumpatronen sowie 25 Frostgranaten.', 'Hallo $N. Nach euren vergangenen Erfolgen, muss ich Euch bitte ich euch mir 100 Thoriumpatronen sowie 50 Frostgranaten zu bringen.', ''),
('870001', 'Sammlung Teil Acht', 'Bringt mir 75 Sonnenpartikel und toetet Selin Feuerherz sowie Mutantus den Verschlinger.', 'Hallo $N. Ich moechte Euch auf der Reise zu den Sammlern eine weitere Aufgabe geben. Bringt mir 75 Sonnenpartikel und toetet Selin Feuerherz sowie Mutantus den Verschlinger. Diese sind uns schon lange ein Dorn im Auge. Aber ihr habt es bald geschafft und koennt dann bald in die Feste der Sammler aufbrechen.', ''),
('870002', 'Reise zum Aussenposten der Sammler', 'Reist zum Aussenposten der Sammler um Euch dort mit Moons Stellvertreter zu treffen.', 'Hallo $N. Ihr habt es geschafft. Ihr habt bewiesen das ihr wuerdig seid den Sammlern gegenueber treten zu koennen. Am Flussnabel ist unser erster Aussenposten. Reisst dorthin um in unsere Gemeinschaft aufgenommen zu werden.', ''),
('870003', 'Die Prinzessin', 'Geht zur Prinzessin der Sammler und hoert Euch ihre Geschichte an.', 'Hallo $N. Willkommen im Aussenposten der Sammler. Macht es Euch bequem, und wenn ihr Interesse habt geht zu Prinzessin Alanna. Sie braucht bestimmt ein offenes Ohr. Wenn ihr Zeit habt, wird sie Euch vielleicht etwas erzaehlen.', ''),
('870100', 'Die verlorene Scherbe', 'Bringt mir meine Scherbe zurueck sofort.', 'Hey $c. Ich hab meine Scherbe verloren und da ich gehoert habe ihr muesst fuer uns arbeiten und vorallem fuer mich, die wunderschoene Prinzessin, sollt ihr mir die Scherbe zurueckholen. Und wenn ihr sie auch nur ein bisschen verkratzt braucht ihr gar nicht zurueck kommen. Ich werde mich dann bei Moon beschweren.', ''),
('890000', 'Orca', 'Geht zu Orca und begruesst ihn hier auf Azeroth.', 'Ein neuer Mitstreiter ist in Azeroth eingetroffen. Geht zu ihm und begruesst ihn.', ''),
('890002', 'EXTREME WORLD', 'Sammelt 600 Koenigstinte, 600 Loewentinte, 450 Meerestinte', 'Hallo $N. Heute muesst ihr mir Tinten sammeln. Ich brauche einiges an Tinten da ich die Bibel neu schreiben moechte. Und das per Hand. Da braucht man eben unter Wasser einiges an Tinten.', ''),
('900000', 'Frohe Weihnachten', 'Exitare sowie das komplette Team wuenscht euch Frohe Feiertage.', 'Hallo $N, so sind wir nun zusammengekommen um gemeinsam das Weihnachtsfest zu feiern. Dazu hat das Team in gemeinsamer Arbeit ein paar Aufmerksamkeiten fuer Euch versteckt. Wir wuenschen Euch viel Spa├ƒ beim Suchen dieser Teile. Exitare und das gesammte Team wuenschen Euch nochmals Frohe Feiertage.', 'Frohe Weihnachten.'),
('900100', 'Frohes Neujahr', 'Wir feiern gemeinsam Neujahr. Begebt Euch als erstes zum Labyrinth.', 'Willkommen beim Neujahrsevent. Begebt Euch als erstes zum Labyrinth. Ihr muesst nur euren Weg suchen, den benoetigten NPC werden ihr finden.', 'Es ist eure Sache was ihr tut.'),
('900101', 'Frohes Neujahr', 'Wir feiern gemeinsam Neujahr. Begebt Euch nun durch das Labyrinth.', 'Willkommen beim Neujahrsevent. Begebt Euch nun durch das Labyrinth. Ihr muesst nur euren Weg suchen, den benoetigten NPC werden ihr finden.', 'Es ist eure Sache was ihr tut.'),
('900501', 'Und weiter gehts mit dem Halloweenspass', 'Hey $N, heute veranstalten wir unser erstes Blutbad. Toetet die Kuerbissoldaten die auf einer Insel an der Kueste von Westfall stehen.', 'Hallo $N, die Kuerbissoldaten gehen mir betraechtlich auf die Nerven. Toetet sie und veranstaltet ein wundervolles Kuerbiskratzfest!', 'Erfolg!'),
('900508', 'Halloween Schabernack', 'Hey $N, bringt mir Bier in rauen Mengen.', 'Hallo $N, dieses Jahr feiern wir Halloween mit Bier. Viel Bier! Die Dunkeleisenzwerge haben ihr Gebraeu verloren. Also los schnappt es Euch. In Dalaran, Insel, Orgrimmar, Ratchet sowie Sturmwind solltest du fuendig werden.', 'Erfolg!'),
('900510', 'Ich bin Halloweeny', 'Hey $N, Halloweeny ist mein Name. Ich sehe zwar aus wie der Kerl links neben mir aber naja, ich bin viel cooler. Das werdet ihr aber noch im Laufe der Zeit merken.', 'Hallo $N,Halloween ist mein Metier. Deswegen bin ich erst jetzt vorbeigekommen. Verzeiht mir das. Aber hey, jetzt bin ich hier also lasst uns loslegen. Der Kerl neben mir wird spaetestens in ein paar Tagen dicht ohne Ende sein. Naja dann los die erste Aufgabe wartet.', 'Erfolg!'),
('900800', 'Ein neues Volk', 'Hey du. Wir kennen uns ja bereits. Ich denke es wird Zeit euch einem besonderem Volk vorzustellen. Geht zu Eowyn und sprecht mit ihr.', 'Hallo $N, na wir sehen uns aber oft. Na dann schicke ich Euch zu eurem ersten Autraggeber. Geht zu Eowyn und gebt die Quest ab.', 'Erfolg!'),
('900801', 'Das Wandervolk!', 'Das Wandervolk ist ein interessantes Volk. Um das Volk kennenzulernen braucht ihr 2 Auktionspapiere und 50 Feine Gewuerze', 'Hallo $N, das Wandervolk ist ein interessantes Volk, welches im Dunkel der Welten hausst. Erfuellt die Quest und ihr steht in ihrer Gunst.', 'Erfolg!'),
('900802', 'Die Gunst', 'Nehmt den Port zum Wandervolk und meldet Euch dort beim ersten der Euch ueber den Weg laeuft.', 'Hallo $N, bitte reist zum Wandervolk und meldet Euch dort beim Ersten der Euch ueber den Weg laeuft.', 'Es ist eure Sache was ihr tut.'),
('900803', 'Leandaria', 'Bringt mir 50 Stueck Kupferpulver.', 'Hallo $N, Leandaria braucht Kupferpulver. Bitte bringt mir, als Vertretung fuer sie, 50 Stueck davon.', 'Es ist eure Sache was ihr tut.'),
('900804', 'Der Spezialhaendler', 'Bringt dem Spezialhaendler 5 Embleme des Triumphs und 20 Wandervolkmarken.', 'Hallo $N, ich bin der Spezialhaendler des Wandevolkes. Wenn ihr mich kennen lernen wollt, dann erfuellt ein paar Aufgaben fuer mich.', 'Es ist eure Sache was ihr tut.'),
('900805', 'Das Schwert', 'Bezahlt mir einen kleinen Obulus und die Sache hat sich erledigt. So als kleines \"Geschenk\".', 'Hallo $N, seit ich beim Wandervolk aufgenommen wurde, hat sich mein Leben verbessert.', 'Es ist eure Sache was ihr tut.'),
('900806', 'Der Stein', 'Toetet 20 Spieler der gegnerischen Fraktion.', 'Hallo $N, was belebt das Geschaeft besser, als potentielle Konkurrenten aus dem Weg zu raeumen? Richtig, nichts. Deswegen toetet sie.', 'Es ist eure Sache was ihr tut.'),
('900810', 'Elostraio', 'Elostraio braucht Gold! Gebt mir Gold!', 'Hallo $N, ich bin ein armer Schlucker. Ich brauche Gold. Gebt mir bitte Gold. Bitte Bitte Bitte....', 'Es ist eure Sache was ihr tut.'),
('900820', 'Das Wandervolk ruft', 'Ein neues Stueck Geschichte wird auf MMOwning geschrieben.', 'Hallo $N, zusammen gehen wir auf eine Reise durch die Welt von Azeroth. Es werden Euch Steine in den Weg gelegt werden, vielleicht werdet ihr verzweifeln. Aber der Weg lohnt sich.', 'Es ist eure Sache was ihr tut.'),
('900822', 'Der Weg beginnt.', 'Geht zu Lucion dem Hochlord der Sammler.', 'Hallo $N, begeben wir uns auf den ersten Weg. Geht zu Lucion dem Hochlord der Sammler. Finden koennt ihr ihn an der Flussnabel, beim kleinen Lager des Wandervolkes.', 'Es ist eure Sache was ihr tut.'),
('900823', 'Sammeln der Vorraete.', 'Sammelt die unten angegeben Vorraete um die Reise fortzusetzen.', 'Hallo $N, fuer unsere beschwerliche Reise benoetigen wir Vorraete. Diese sind auf der Welt verstreut. Bitte besorgt sie uns, damit wir uns auf die folgenden Aufgaben vorbereiten koennen. ', 'Es ist eure Sache was ihr tut.'),
('900824', 'Entledigen der Konkurrenz.', 'Wir muessen unsere Konkurrenz abschuettlen.', 'Hallo $N, unsere Konkurrenz holt auf. Diese Trolle, nun gut ich verkneife mir jedes Wort, schliesslich kaempfen wir ja gemeinsam gegen diese stinkenden Bestien. Aber unser Vorteil ist wichtiger. Toetet also Daakara! Jetzt sofort und fuer immer.', 'Es ist Eure Sache was ihr tut.'),
('900825', 'Die Fakten kennen.', 'Hoert mir zu.', 'Hallo $N, ich muss euch etwas wichtiges erzaehlen bevor wir hier weitermachen koennen. Groot und Kraserius von den Sammlern verdaechtigen mich, das ich ein Verraeter sei und nicht im Interesse von uns handeln wuerde. Aber ich kann Euch versichern, dem ist nicht so. Es ist eher anders, die beiden betruegen uns und das gesamte Volk. Sie nutzen uns aus und berreichern sich selbst. Glaubt mir! Ich moechte nicht das auch ihr ausgenutzt werdet.', 'Es ist eure Sache was ihr tut.'),
('900826', 'Wir brauchen mehr Materialien.', 'Besorgt mir mehr Materialien. Ich brauche diese.', 'Hallo $N, diese glitzernden Gegenstaende wie Gold, Silber. Ich brauche sie, ich will sie haben. Oh aber natuerlich bekommt ihr euren Teil der Beute ab. Nur wie viel das wolllen wir nochmal ueberdenken. Sammelt also fuer mich die nachfolgenden Dinge.', 'Es ist eure Sache was ihr tut.'),
('900827', 'Die Raren sind die Wichtigen.', 'Wer hat nicht gerne seltene Dinge?', 'Hallo $N, ein weiteres Mal habe ich seltene Dinge ausgemacht, die von grossem Wert sind. Bitte seid so gut und bringt sie mir. Ich entschuldige mich fuer die vorrangegangene Abzocke. Es wird nicht mehr passieren.', 'Es ist Eure Sache was ihr tut.'),
('900828', 'Brutaler als Brutallus?', 'Geht hin und bringt Brutallus zur Strecke.', 'Hallo $N, ich hoffe ihr seid mir nicht mehr abgeneigt und wohlgesonnener nach meinem Geschenk an euch. Toetet also Brutallus im Sonnenbrunnenplateau um mir zu beweisen das ihr treu zu mir steht.', 'Es ist Eure Sache was ihr tut.'),
('900829', 'Bericht an Indomata.', 'Geht zu Indomata und berichtet.', 'Hallo $N, dieser feige Verrat war nicht vorherzusehen. Geht zu Indomata und berichtet ihm davon.', 'Es ist eure Sache was ihr tut.'),
('900830', 'Der Rachefeldzug beginnt.', 'Toetet den Geisselfuerst Tyrannus.', 'Hallo $N, Ich finde keine Worte. Fuehrt den Auftrag aus und kommt zurueck wenn ihr fertig seid!', 'Es ist Eure Sache was ihr tut.'),
('900831', 'Der Rachfeldzug geht weiter.', 'Toetet den Verschlinger der Seelen.', 'Hallo $N, nachdem nun der erste Intrigant gefallen ist, wollen wir uns den Naechsten vorknoepfen. Toetet den Verschlinger der Seelen.', 'Es ist Eure Sache was ihr tut.'),
('900832', 'Der Rachfeldzug spitzt sich zu.', 'Toetet Hochnethermant Zerevor.', 'Hallo $N, der Hochnethermant ist eine fuehrende Person der Marionetten in diesem Spiel aber nicht die wahre Bedrohung. Dennoch muss er ausgeschaltet werden. Geht also hin und besiegt den Rat der Illidari im Schwarzen Tempel im Schattenmondtal. Bringt mir dazu noch 30 Male der Illidari.', 'Es ist Eure Sache was ihr tut.'),
('900833', 'Einhalt muss geboten werden.', 'Toetet Satharion im Obsidiansanktum.', 'Hallo $N, Satharion ein maechtiger Drache muss getoetet werden. Durchforstet seinen Leichnam nach einem komischen Objekt und bringt es mir. Beeilt Euch!', 'Es ist Eure Sache was ihr tut.'),
('900834', 'Entspannung fuer Indomata.', 'Besorgt mit beruhigendes Gift II damit ich mich wieder beruhigen kann.', 'Hallo $N, die ganze Rache ist mir ueber den Kopf gewachsen. Bringt mir bitte 10 beruhigendes Gift II, damit ich wieder ruhig bin.', 'Es ist eure Sache was ihr tut.'),
('900835', 'Der Statusbericht.', 'Bringt Janarius meinen Bericht.', 'Hallo $N, bringt Janarius beim Wandervolk bitte meinen Spionbericht. Er befindet sich auf der Hauptplattform des Wandervolkes.', 'Es ist eure Sache was ihr tut.'),
('900837', 'Die Verzauberung.', 'Bringt mir Arkanen Staub, Tiefenkristalle, Schleierstaub sowie grosse Prismasplitter.', 'Hallo $N, da wir einige Verraeter identifizieren konnten, muesst ihr mir einige Dinge bringen. Einen davon haben wir zum Tode verurteilt. Bringt mir Arkanen Staub, Tiefenkristalle, Schleierstaub sowie grosse Prismasplitter. Damit werde ich den Verraeter verzaubern koennen und seine Todesstrafe wird vollstreckt werden.', 'Es ist eure Sache was ihr tut.'),
('900838', 'Die Steinigung.', 'Bringt mir Verdichtete Steine, robuste Steine, schwere Steine sowie Raue Steine.', 'Hallo $N, die Verzauberung war erfolgreich. Daher tritt nun die naechste Stufe in Kraft. Bringt mir Verdichtete Steine, robuste Steine, schwere Steine sowie Raue Steine. Wir werden den Verraeter nun steinigen. ', 'Es ist eure Sache was ihr tut.'),
('900839', 'Die Einbalsamierung.', 'Bringt mir Frostlotus, Goldklee, Silberblatt, Teufelsgras.', 'Hallo $N, der Verraeter wurde erfolgreich liqiudiert. Bringt mir Frostlotus, Goldklee, Silberblatt, Teufelsgras. Wir werden ihn nun einbalsamieren damit sein Koerper auf ewig auf dieser Welt verweilen muss.', 'Es ist eure Sache was ihr tut.'),
('900840', 'Die Mumifizierung.', 'Bringt mir Frostoff, Netherstoff, Arktische Pelze sowie Boreanisches Leder.', 'Hallo $N, der Verraeter wurde erfolgreich einbalsamiert.Bringt mir Frostoff, Netherstoff, Arktische Pelze sowie Boreanisches Leder damit wir den Leichnam nun einwickeln koennen und somit schuetzen koennen. Die Mumifizierung muss erfolgreich sein! Vielleicht entdecken wird ja etwas in seinem Koerper, das uns weiterbringt um der Verschwoerung auf die Spur zu kommen.', 'Es ist eure Sache was ihr tut.');



INSERT INTO `locales_quest` (`Id`, `Title_loc3`, `Details_loc3`, `Objectives_loc3`, `CompletedText_loc3`)
VALUES ('750000', 'Willkommen auf dem Server', 'Willkommen auf unserem Server. Um dir einen besseren Ueberblick ueber alle Funktionen geben zu koennen, ist das hier die Einfuehrungquest. Als Spieler hast du verschiedene Commands zur Verfuegung. Am besten fragst du Exaltor genauer aus. Er weis sicher Bescheid. Wenn du dir alles durchgelesen hast, beende die Quest!', 'Beende diese Quest fuer deine Belohnung!', 'Es ist Eure Sache was Ihr tut!');

INSERT INTO `locales_quest` (`Id`, `Title_loc3`, `Details_loc3`, `Objectives_loc3`, `CompletedText_loc3`)
VALUES ('803903', 'Toetet 100 Spieler', '$N, Ich moechte das Ihr 100 Feinde abschlachtet. Nehmt keine Ruecksicht auf Verluste. Ihr seid Meister der Vernichtung. Ihr werdet Euren Feinden das Fuerchten lehren. Geht jetzt.',
'Toetet 100 Spieler. Egal wo. Egal wie! Toetet sie einfach.', 'Es ist Eure Sache was Ihr tut!');

INSERT INTO `locales_quest` (`Id`, `Title_loc3`, `Details_loc3`, `Objectives_loc3`, `CompletedText_loc3`)
VALUES ('803902', 'Toetet 50 Spieler', '$N, Ich moechte das Ihr 50 Feinde abschlachtet. Nehmt keine Ruecksicht auf Verluste. Ihr seid Meister der Vernichtung. Ihr werdet Euren Feinden das Fuerchten lehren. Geht jetzt.',
'Toetet 50 Spieler. Egal wo. Egal wie! Toetet sie einfach.', 'Es ist Eure Sache was Ihr tut!');

INSERT INTO `locales_quest` (`Id`, `Title_loc3`, `Details_loc3`, `Objectives_loc3`, `CompletedText_loc3`)
VALUES ('803901', 'Toetet 20 Spieler', '$N, Ich moechte das Ihr 20 Feinde abschlachtet. Nehmt keine Ruecksicht auf Verluste. Ihr seid Meister der Vernichtung. Ihr werdet Euren Feinden das Fuerchten lehren. Geht jetzt.', 
'Toetet 20 Spieler. Egal wo. Egal wie! Toetet sie einfach.', 'Es ist Eure Sache was Ihr tut!');

INSERT INTO `locales_quest` (`Id`, `Title_loc3`, `Details_loc3`, `Objectives_loc3`, `CompletedText_loc3`)
VALUES ('803900', 'Toetet 10 Spieler', '$N, Ich moechte das Ihr 10 Feinde abschlachtet. Nehmt keine Ruecksicht auf Verluste. Ihr seid Meister der Vernichtung. Ihr werdet Euren Feinden das Fuerchten lehren. Geht jetzt.', 
'Toetet 10 Spieler. Egal wo. Egal wie! Toetet sie einfach.', 'Es ist Eure Sache was Ihr tut!');

INSERT INTO `locales_quest` (`Id`, `Title_loc3`, `Objectives_loc3`, `Details_loc3`, `CompletedText_loc3`)
VALUES ('800537', 'Weekly: Exitares Schatten', 'Toetet den Schatten von Exitare.', 
'Hallo $N, toetet Exitare den dunklen Schatten. Er war lange genug am Leben. Seine Zeit ist nun vorrueber. Meine korrumpierte Seele hat genug Schaden angerichtet.', 'Es ist Eure Sache was Ihr tut!');

INSERT INTO `locales_quest` (`Id`, `Title_loc3`, `Objectives_loc3`, `Details_loc3`, `CompletedText_loc3`)
VALUES ('800547', 'Weekly: Maltyriun', 'Toetet Maltyriun.', 
'Hallo $N, Toetet Maltyriun den Verraetern. Er ist ueber den Porter zu erreichen. Er muss vernichtet werden.', 'Es ist Eure Sache was Ihr tut!');

INSERT INTO `locales_quest` (`Id`, `Title_loc3`, `Objectives_loc3`, `Details_loc3`, `CompletedText_loc3`)
VALUES ('800552', 'Weekly: Tyranium', 'Toetet Tyranium.', 
'Hallo $N, Toetet Tyranium den gefluegelten Schrecken. Er ist ueber den Porter zu erreichen. Er muss vernichtet werden.', 'Es ist Eure Sache was Ihr tut!');

INSERT INTO `locales_quest` (`Id`, `Title_loc3`, `Objectives_loc3`, `Details_loc3`, `CompletedText_loc3`)
VALUES ('800553', 'Kristallisierte Steinsplitter', 'Sammelt 60 Stueck der Steinsplitter', 
'Hallo $C, schoen Euch hier begruessen zu duerfen. Bringt mir kristallierste Steinsplitter damit ich meine Klinge wieder schaerfen kann. Sie ist im Kampf gegen unseren Feid ganz stumpf geworden.', 'Es ist Eure Sache was Ihr tut!');

INSERT INTO `locales_quest` (`Id`, `Title_loc3`, `Objectives_loc3`, `Details_loc3`, `CompletedText_loc3`)
VALUES ('800554', 'Erweisst Euch wuerdig', 'Sammelt 30 Wandervolkmarken!', 
'Hallo $C $N, schoen das ihr euren Weg hierher gefunden habt. Ich hab eine wichtige Aufgabe fuer Euch, die fuer das Koenigshaus ernorm wichtig ist. Sammelt 30 Marken des Wandervolkes. Leider wurden einige unserer Freunde des Wandervolkes von Gestalten der Scherbenwelt und ganz Azeroth getoetet. Dadurch koennt ihr diese Marken nun bei diesen Kreaturen finden!
', 'Es ist Eure Sache was Ihr tut!');

INSERT INTO `locales_quest` (`Id`, `Title_loc3`, `Objectives_loc3`, `Details_loc3`, `CompletedText_loc3`)
VALUES ('800555', 'Die Waffen', 'Bringt mir 30 Waffen der Horde!',
'Hallo $N, ich moechte unbedingt diese Waffen haben. Ich bereite einen geheimen Plan vor. Vielleicht werde ich Euch diesen Plan in der Zukunft mitteilen!', 'Es ist Eure Sache was Ihr tut!');
 


INSERT INTO `locales_quest` (`Id`, `Title_loc3`, `Objectives_loc3`, `Details_loc3`, `CompletedText_loc3`)
VALUES ('800558', 'Kampf: Leandaria', 'Fordert Leandaria heraus und besiegt Sie in diesem Duell.',
'Leandaria kann ganz gut austeilen. Beweist das Ihr haerter seid!', 'Es ist Eure Sache was Ihr tut!');

INSERT INTO `locales_quest` (`Id`, `Title_loc3`, `Objectives_loc3`, `Details_loc3`, `CompletedText_loc3`)
VALUES ('800559', 'Gold fuer das Wandervolk', 'Helft dem Wandervolk mit 2000 Gold aus. Diese werde es Euch danken.',
'Das Wandervolk braucht auch Hilfe in Form von Gold. Ohne dieses geht es einfach nicht weiter. Helft uns und Ihr werdet gut belohnt!', 'Es ist Eure Sache was Ihr tut!');

INSERT INTO `locales_quest` (`Id`, `Title_loc3`, `Objectives_loc3`, `Details_loc3`, `CompletedText_loc3`)
VALUES ('800560', 'Bekaempft eure Feinde', 'Toetet 20 euerer schlimmsten Feinde.',
'Wer hat nicht schon nachgedacht sich seiner Feinde zu entledigen? Nun bekommt ihr die Chance.', 'Es ist Eure Sache was Ihr tut!');

INSERT INTO `locales_quest` (`Id`, `Title_loc3`, `Objectives_loc3`, `Details_loc3`, `CompletedText_loc3`)
VALUES ('800561', 'Das Massaker', 'Toetet 200 euerer schlimmsten Feinde.',
'Richtet ein Massaker unter euren Feinden an! Nichts ist besser als sie alle zu dezimieren!', 'Es ist Eure Sache was Ihr tut!');

INSERT INTO `locales_quest` (`Id`, `Title_loc3`, `Objectives_loc3`, `Details_loc3`, `CompletedText_loc3`)
VALUES ('802008', 'Der weitere Weg', 'Exitare erwartet Euch.',
'$N, Exitare wartet auf Euch. Er moechte Euch in den weiteren Lehren eurer Ausbildung unterstuetzen. Bitte geht zu Ihm auf der "Insel".', 'Es ist Eure Sache was Ihr tut!');

INSERT INTO `locales_quest` (`Id`, `Title_loc3`, `Objectives_loc3`, `Details_loc3`, `CompletedText_loc3`)
VALUES ('802016', 'Die Rueckkehr', 'Kehrt zu Rumu zurueck.',
'$N,kehrt zu Rumu zurueck um eure Belohnung abzuholen.', 'Es ist Eure Sache was Ihr tut!');

INSERT INTO `locales_quest` (`Id`, `Title_loc3`, `Objectives_loc3`, `Details_loc3`, `CompletedText_loc3`)
VALUES ('802017', 'Willkommen bei den Farmern', 'Bringt Moon 20 Kupferbarren, 10 Eisenbarren sowie 50 Leichte Leder.',
'$N,$Bich bin Moon die unermuedliche Sammlerin. Bei mir koennt ihr viel sammeln und viel zusammenfarmen. Es wird lange dauern alles zusammenzubekommen. Bringt mir als erstes 20 Kupferbarren, 10 Eisenbarren sowie 50 Leichte Leder.', 'Es ist Eure Sache was Ihr tut!');

INSERT INTO `locales_quest` (`Id`, `Title_loc3`, `Objectives_loc3`, `Details_loc3`, `CompletedText_loc3`)
VALUES ('802027', 'Das zweite Raetsel', 'Loest das Raetsel.',
'$N,kehrt zurueck zu Rumu um Eure Belohnung abzuholen.', 'Es ist Eure Sache was Ihr tut!');

INSERT INTO `locales_quest` (`Id`, `Title_loc3`, `Objectives_loc3`, `Details_loc3`, `CompletedText_loc3`)
VALUES ('890001', 'EXTREME WORLD', 'Sammelt 1000 Emblem des Triumphs.',
'Hallo $N. Ich begruesse Euch. Ich soll Euch einen Gruss von Exitare und Rumu hier lassen. Sie wuenschen Euch viel Spass beim bestreiten dieser Questreihe. Diese Questreihe ist absichtlich extrem gewaehlt und soll extreme Belohnungen gewaehren. Ihr koennt darauf einstellen, fiesse, langwierige, sowie schwere Quests zu bekommen. Verzweifelt aber nicht. Es warten gute Belohnung auf Euch.', 'Es ist Eure Sache was Ihr tut!');

INSERT INTO `locales_quest` (`Id`, `Title_loc3`, `Objectives_loc3`, `Details_loc3`, `CompletedText_loc3`)
VALUES ('899000', 'Das dritte Raetsel', 'Loest das Raetsel.',
'$N,hier euer drittes Raetsel. Ihr muesst Lightshadow in einem bestimmten Modus toeten, sowie bestimmte Faktoren erreichen. Viel Erfolg beim Erfolg des Raetsels. ', 'Es ist Eure Sache was Ihr tut!');

INSERT INTO `locales_quest` (`Id`, `Title_loc3`, `Objectives_loc3`, `Details_loc3`, `CompletedText_loc3`)
VALUES ('900001', 'Frohe Weihnachten', 'Wir wuenschen dir eine Frohe Weihnacht.',
'Viel Spass dir beim Weihnachtsevent. Erreiche das Ende und geniesse es.', 'Es ist Eure Sache was Ihr tut!');

INSERT INTO `locales_quest` (`Id`, `Title_loc3`, `Objectives_loc3`, `Details_loc3`, `CompletedText_loc3`)
VALUES ('900300', 'Das Jumpevent', 'Macht Euch mit dem Jumpevent vertraut um spaeter ueber Eure Grenzen hinauszuwachsen und grosse Erfolge zu erreichen.',
'Hallo $N, damit ihr nicht ins kalte Wasser fallt, sollt ihr Euch erstmal in Ruhe mit diesem Event auseinander setzen. Erreicht das Ende um Eure Belohnung abzuholen.', 'Es ist Eure Sache was Ihr tut!');

INSERT INTO `locales_quest` (`Id`, `Title_loc3`, `Objectives_loc3`, `Details_loc3`, `CompletedText_loc3`)
VALUES ('900301', 'Das Portalevent', 'Macht Euch mit dem Portalevent vertraut um spaeter ueber Eure Grenzen hinauszuwachsen und grosse Erfolge zu erreichen.',
'Hallo $N, damit ihr nicht ins kalte Wasser fallt, sollt ihr Euch erstmal in Ruhe mit diesem Event auseinander setzen. Erreicht das Ende um Eure Belohnung abzuholen.', 'Es ist Eure Sache was Ihr tut!');

INSERT INTO `locales_quest` (`Id`, `Title_loc3`, `Objectives_loc3`, `Details_loc3`, `CompletedText_loc3`)
VALUES ('900500', 'Happy Halloween', 'Wir feiern Halloween mit Euch. Unser eigenes Halloweenfest startet hier und heute.',
'Hallo $N, bringt mir bitte 5 Kuerbiskuchen, um unser Halloweenfest zu unterstuetzen.', 'Es ist Eure Sache was Ihr tut!');

INSERT INTO `locales_quest` (`Id`, `Title_loc3`, `Objectives_loc3`, `Details_loc3`, `CompletedText_loc3`)
VALUES ('900502', 'Halloween Gestoehne', 'Hey $N, das es zu Halloween auch wirklich ein Grauen gibt, duerft ihr mir 100 Kupferpulver bringen.',
'Hallo $N, Ihr findet Kupferpulver auf der Insel in Westfall und im umliegenden Wasser. Tauchen lohnt sicht. Ich wuensche Euch viel Erfolg.', 'Es ist Eure Sache was Ihr tut!');

INSERT INTO `locales_quest` (`Id`, `Title_loc3`, `Objectives_loc3`, `Details_loc3`, `CompletedText_loc3`)
VALUES ('900503', 'Halloween Rally', 'Hey $N, wir wollen ein bisschen Action zu Halloween oder nicht ? Bringt mir 20 Grobes Gorillahaar und 15 Gorillafangzaehne. Geht danach zu Orrig vor Orgrimmar.',
'Hallo $N, Gorillas hausen meistens im Wald.', 'Es ist Eure Sache was Ihr tut!');

INSERT INTO `locales_quest` (`Id`, `Title_loc3`, `Objectives_loc3`, `Details_loc3`, `CompletedText_loc3`)
VALUES ('900504', 'Orrig Halloween', 'Hey $N, toetet Orrig! Zu Halloween muss es ein Schlachtfest geben und wer eigenet sich besser dafuer als dieser fette Zwerg?',
'Hallo $N, Orrig hat Fleisch. Viel Fleisch!! Los holt es mir!', 'Es ist Eure Sache was Ihr tut!');

INSERT INTO `locales_quest` (`Id`, `Title_loc3`, `Objectives_loc3`, `Details_loc3`, `CompletedText_loc3`)
VALUES ('900807', 'Die Marken', 'Bringt mir 10 Embleme des Frosts.',
'Hallo $N, ich moechte das ihr mir die Embleme des Frostes bringt. Diese sind der begehrenswert. Daher moechte ich sie auch haben.', 'Es ist Eure Sache was Ihr tut!');

INSERT INTO `locales_quest` (`Id`, `Title_loc3`, `Objectives_loc3`, `Details_loc3`, `CompletedText_loc3`)
VALUES ('900808', 'Gib mir Marken', 'Bringt mir 10 Embleme des Triumphs sowie 4 Arktische Pelze.',
'Bringt mir 10 Embleme des Triumphs sowie 4 Arktische Pelze.', 'Es ist Eure Sache was Ihr tut!');

INSERT INTO `locales_quest` (`Id`, `Title_loc3`, `Objectives_loc3`, `Details_loc3`, `CompletedText_loc3`)
VALUES ('900811', 'Der Wyrm', 'Bringt Leandaria 20 Wandervolkmarken!',
'Hallo $N, damit ihr in meiner Gunst steht muesst ihr mir 20 Wandervolkmarken. Habt ihr das geschafft gebe ich Euch etwas frei was Euch freuen wird.', 'Es ist Eure Sache was Ihr tut!');

INSERT INTO `locales_quest` (`Id`, `Title_loc3`, `Objectives_loc3`, `Details_loc3`, `CompletedText_loc3`)
VALUES ('900809', 'Felicitas', 'Das Mysterium beginnt. Bringt mir die Wandervolkmarken.',
'Hallo $N, um sie erfahren wer Felicitas ist, muessen wir ein paar Vorbereitungen treffen.', 'Es ist Eure Sache was Ihr tut!');

INSERT INTO `locales_quest` (`Id`, `Title_loc3`, `Objectives_loc3`, `Details_loc3`, `CompletedText_loc3`)
VALUES ('900506', 'Astraler Spuck', 'Hey $N, habt ihr schon die noetigen Halloweenmarken zusammen bekommen? Nein? Schade.',
'Hallo $N, um diese Quest zu beenden, muesst ihr Euch dem Halloweenevent stellen und die Quest abarbeiten. Es wird sich aber definitiv lohnen. Sammelt die Halloweenmarken und gebt sie bei mir ab. Bei mir sind sie sicher, und ihr bekommt sogar eine schaurig schoene Belohnung.', 'Es ist Eure Sache was Ihr tut!');

INSERT INTO `locales_quest` (`Id`, `Title_loc3`, `Objectives_loc3`, `Details_loc3`, `CompletedText_loc3`)
VALUES ('900509', 'Halloweeny hat Aufgaben', 'Hey $N, meine erste Aufgabe an Euch wird etwas schwierigier dafuer hat sie einen tollen Nebeneffekt. Bringt mir 20 Halloweenabzeichen.',
'Hallo $N, ich bin scharf auf diese Abzeichen. Bringt mir daher 20 Stueck. Wenn ihr mir diese gebracht habt, werden eure taeglichen Quests wieder auf 25 aufgefuellt, daher entscheidet euch gut wann ihr diese Quest abgebt. Sie kann ein maechtiges Werkzeug beim Questen sein.', 'Es ist Eure Sache was Ihr tut!');

INSERT INTO `locales_quest` (`Id`, `Title_loc3`, `Objectives_loc3`, `Details_loc3`, `CompletedText_loc3`)
VALUES ('900821', 'Wer ist den nun Felicitas?', 'Das kleine Geheimnis um Felicitas wird gelueftet werden.',
'Hallo $N, hast du dich nicht auch schonmal gefragt wer oder was Felicitas ist? Wenn ja wirst du der Antwort immer naeher kommen, wenn wir hier gemeinsam arbeiten. Bringt mir daher bitte 5 Titanstahlbarren.', 'Es ist Eure Sache was Ihr tut!');

INSERT INTO `locales_quest` (`Id`, `Title_loc3`, `Objectives_loc3`, `Details_loc3`, `CompletedText_loc3`)
VALUES ('900836', 'Der Vertrauensbeweis', 'Bringt mir 5 Wandervolkmarken.',
'Hallo $N, es ist ja gut das Euch Indomata vertraut. Aber ich bin nicht Indomata. Ich moechte das ihr mir zeigt das ihr Euch fuer die Sache einsetzt. Bringt mir daher 5 Wandervolkmarken.', 'Es ist Eure Sache was Ihr tut!');

INSERT INTO `locales_quest` (`Id`, `Title_loc3`, `Objectives_loc3`, `Details_loc3`, `CompletedText_loc3`)
VALUES ('900505', 'Halloween geht weiter', 'Hey $N, habt ihr schon einmal von den Sammlern gehoert? Die Sammler haben Gegenstaende mit unschaetzbarem Wert. Bringt mir die Wandervolkmarken!!',
'Hallo $N, diese Abzeichen haben einen unschaetzbaren Wert fuer mich. Wenn ihr mir diese besorgt, werde ich Euch reich belohnen.', 'Es ist Eure Sache was Ihr tut!');












